### ISSUE TITLE
Sponge API 8

### ISSUE THREAD

**Issue by Ad973z** [LuckPerms/LuckPerms#3096]
### Description

LuckPerms support Sponge API-9

### Proposed behaviour

Please upgrade luckperms to api-9！

**Comment by johnfriedrich** [comment]
@lucko What is the status on this one? There are preview builds of SpongeForge out there.

Builds:
https://repo.spongepowered.org/#browse/search=attributes.maven2.artifactId%3Dspongeforge%20AND%20version%3D1.16.5*

Announcement:
https://forums.spongepowered.org/t/spongies-7th-birthday-status-update-8th-september-2021/39520

**Comment by lucko** [comment]
Progress updates and beta builds are in #2728
