### ISSUE TITLE
Include LuckPerms ExtraContexts in LuckPerms itself

### ISSUE THREAD

**Issue by Chris6ix** [LuckPerms/LuckPerms#3100]
### Description
Include LuckPerms ExtraContexts (https://github.com/LuckPerms/ExtraContexts) in LuckPerms itself as some of the extra contexts (especially the worldguard ones) are extremely important to some servers and including them in the main LuckPerms plugin would make them easier to keep updated and would make the entire LuckPerms "Experience" more integrated and in my opinion better.
This removes the need to have an additional add-on for an in my opinion very important feature.

### Proposed behaviour
Same behavior as before i guess, just now better integrated/updated :)

**Comment by Username404-59** [comment]
this would be useless for Fabric servers though

**Comment by benwoo1110** [comment]
Well, it just needs its context implementation that's all. Things that are not dependent on other plugins such as gamemode or world should be built-in and I believe it's already present (at least for bukkit). 

However, for other contexts, such as those related to worldguard will be dependent on worldguard plugin and may result in a maintainability issue. E.g. if worldguard API change, luckperms will need an update as well which doesn't make sense. These should then be implemented in a separate module or into worldguard itself. EssentialsX does that, so I don't see why not.

**Comment by Laarryy** [comment]
Ben's right - the add-on is an add-on for a good reason, in that it entirely relies on external plugins and is also not something that *should* be an integral part of LuckPerms. Other plugins should ideally be registering their own contexts and not relying on a LuckPerms extension! It makes things maintainable by each project and ensures that they can update things on their end when major changes happen, without having to go through LuckPerms. If you've got some special plugins that EC covers and you'd like them specially integrated, let the maintainers of the other plugin know!
