### ISSUE TITLE
Add placeholders

### ISSUE THREAD

**Issue by PanHaskins** [LuckPerms/LuckPerms#3163]
Please add placeholder %luckperms_highest_group_by_weight_expiration% or %luckperms_exipration_group%
So that "VIP" players know when their best VIP ends. + so that it is possible to somehow set the expiration format eg 1w 1d 1h to another language for example or just limit the format to 1w / 1d only, ... From what I've looked at placeholders, none of that is what I imagine. Just to show you the expiration time of the highest group you have, and if it doesn't find your expiration time, it will tell you that you have that group forever.

**Comment by Laarryy** [comment]
Ben's right - I'm going to close this issue and recommend you place it in the above-mentioned repository.
