### ISSUE TITLE
/lp main command only be suggested if player has permission

### ISSUE THREAD

**Issue by DevJoey** [LuckPerms/LuckPerms#3176]
### Description

Players can see the luckperms command suggested in servers >= 1.13. It would be nice if the command could be hidden from players without permissions for luckperms.

### Proposed behaviour

It makes the tab suggestions more clean and free from unwanted commands to which a user dont have access to.

**Comment by lucko** [comment]
This is already the case - if a player doesn't have permission for *any* LuckPerms command, the completions data is not sent.

If they have permission for at least one, the data is sent. Unfortunately, it's not (easily) possible to make this any more granular.

**Comment by DevJoey** [comment]
No, the /luckperms main command is still suggested in bungeecord and spigot even with no permission
