### ISSUE TITLE
LUCKPERMS [Server thread] INFO me.lucko.luckperms.lib.hikari.HikariDataSource - luckperms-hikari - Shutdown completed.

### ISSUE THREAD

**Issue by Baguettejr** [LuckPerms/LuckPerms#3182]
When I try to connect my luckperms database (not localhost) to my entire network (lobby & skywars) when starting skywars I get this error:

[Server thread] INFO me.lucko.luckperms.lib.hikari.HikariDataSource - luckperms-hikari - Shutdown completed.

Which causes the server to close, although it appears that it is on, when trying to enter from the bungeecord with the modalities menu, it crashes

If anyone can help me I would appreciate it, I am quite desperate.

**Comment by Laarryy** [comment]
Going to assume this is fixed as inactive - if it isn't please open a new issue with the appropriate (earlier-requested) logs, and follow the issue template! Thanks!
