### ISSUE TITLE
Unable to perform editor

### ISSUE THREAD

**Issue by MinerCoffee** [LuckPerms/LuckPerms#3200]
### Description

05.11 23:47:58 [Server] INFO MinerCoffee97 issued server command: /lp editor
05.11 23:47:58 [Server] WARN java.lang.RuntimeException: Error uploading data to bytebin
05.11 23:47:58 [Server] WARN at me.lucko.luckperms.common.webeditor.WebEditorRequest.createSession(WebEditorRequest.java:179)
05.11 23:47:58 [Server] WARN at me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:111)
05.11 23:47:58 [Server] WARN at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:56)
05.11 23:47:58 [Server] WARN at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:48)
05.11 23:47:58 [Server] WARN at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:263)
05.11 23:47:58 [Server] WARN at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:167)
05.11 23:47:58 [Server] WARN at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
05.11 23:47:58 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
05.11 23:47:58 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
05.11 23:47:58 [Server] WARN at java.base/java.lang.Thread.run(Unknown Source)
05.11 23:47:58 [Server] WARN Caused by: java.net.UnknownHostException: No such host is known (bytebin.lucko.me)
05.11 23:47:58 [Server] WARN at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
05.11 23:47:58 [Server] WARN at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source)
05.11 23:47:58 [Server] WARN at java.base/java.net.InetAddress.getAddressesFromNameService(Unknown Source)
05.11 23:47:58 [Server] WARN at java.base/java.net.InetAddress$NameServiceAddresses.get(Unknown Source)
05.11 23:47:58 [Server] WARN at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
05.11 23:47:58 [Server] WARN at java.base/java.net.InetAddress.getAllByName(Unknown Source)
05.11 23:47:58 [Server] WARN at java.base/java.net.InetAddress.getAllByName(Unknown Source)
05.11 23:47:58 [Server] WARN at me.lucko.luckperms.lib.okhttp3.Dns.lambda$static$0(Dns.java:39)
05.11 23:47:58 [Server] WARN at me.lucko.luckperms.lib.okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:171)
05.11 23:47:58 [Server] WARN at me.lucko.luckperms.lib.okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:135)
05.11 23:47:58 [Server] WARN at me.lucko.luckperms.lib.okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
05.11 23:47:58 [Server] WARN at me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:187)
05.11 23:47:58 [Server] WARN at me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
05.11 23:47:58 [Server] WARN at me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
05.11 23:47:58 [Server] WARN at me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
05.11 23:47:58 [Server] WARN at me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
05.11 23:47:58 [Server] WARN at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
05.11 23:47:59 [Multicraft] Skipped 13 lines due to rate limit (30/s)
05.11 23:48:31 [Server] WARN at me.lucko.luckperms.common.http.BytebinClient.postContent(BytebinClient.java:98)
05.11 23:48:31 [Server] WARN at me.lucko.luckperms.common.webeditor.WebEditorRequest.createSession(WebEditorRequest.java:174)

### Reproduction Steps

1. Start server.
2. Run the command /lp editor
3. See error message.

### Expected Behaviour

Lets us edit permission on the web ui.

### Server Details

paper-1.17.1-372.jar

### LuckPerms Version

v5.3.74

### Logs and Configs

https://gist.github.com/MinerCoffee/bc57064a663edbade2c3733943af206c

**Comment by Laarryy** [comment]
It appears to be the case that your server does not have an internet connection. It could be simply that it is unable to connect to bytebin, but several other plugins in the log are experiencing connection problems as well. You need to be able to access bytebin/the internet to be able to use the editor.
