### ISSUE TITLE
It is not possible to use commands blocks with LuckPerms

### ISSUE THREAD

**Issue by SundayMC** [LuckPerms/LuckPerms#3204]
### Description

Hello, I have installed LuckPerms on my server. I need to disable the vanilla op system for other plugins. But according to Minecraft to use command block you have to be op, so I'm appealing to you because if I want to use a command block, I can't open the interface and so I can't use it.

### Reproduction Steps

- Disable the vanilla op system
- Set the '*' permission on the WebEditor
- Try to open a command block (isn't work)

### Expected Behaviour

I would have liked to use the block commands to create ice blocks under the boats

### Server Details

CraftBukkit version 3277-Spigot-3892929-2071671 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)

### LuckPerms Version

LuckPerms version 5.3.65

### Logs and Configs

**LOGS :**
[latest.log](https://github.com/LuckPerms/LuckPerms/files/7529377/latest.log)

**CONFIG :**
[config.txt](https://github.com/LuckPerms/LuckPerms/files/7529387/config.txt)

### Extra Details

I'm sorry if my English is weird, I used a translator.

Regards, SundayMC

**Comment by Laarryy** [comment]
There are settings for command blocks that must be changed in the `server.properties` file that deal with command blocks. Try enabling them there.

**Comment by SundayMC** [comment]
If the option you are talking about is : `enable-command-block`, it is already set to **true**.

**Comment by Laarryy** [comment]
If you give yourself the node `luckperms.autoop` and ensure it's set to true, does perhaps that work?

**Comment by SundayMC** [comment]
I am really sorry for the time of absence. To answer your question, despite the fact that in the configuration the vanilla op is activated. It is impossible to /op or /deop a player. I test tonight for the perm autoop.

Have a good day, SundayMC

**Comment by SundayMC** [comment]
I tested it, it works. Thank you very much!

Have a nice day!
