### ISSUE TITLE
Mixin apply for mod luckperms failed luckperms.mixins.json:ClientSettingsC2SPacketAccessor

### ISSUE THREAD

**Issue by Wamens** [LuckPerms/LuckPerms#3210]
### Description

Server fails to start up and display this error 

### Reproduction Steps

Use fabric 1.18-pre4
Fabric Api 0.42.7
and Fabric Load 0.12.5

### Expected Behaviour

Server should start up

### Server Details

Fabric 1.18

### LuckPerms Version

v5.3.70

### Logs and Configs

https://paste.lucko.me/O18fXdi58h

**Comment by emilyy-dev** [comment]
Hey there! LP for Fabric will be updated when stable versions of 1.18 are released! Keep an eye on the [downloads page](https://luckperms.net/download) for when that happens! :smile:
