### ISSUE TITLE
Placeholder back to the question

### ISSUE THREAD

**Issue by liaojinmin** [LuckPerms/LuckPerms#3213]
### Description

papi variable returns an exception

### Reproduction Steps

Set certain permissions for players, such as: [RandomlvStore.use]
  lp user player_name perm settemp RandomlvStore.use true 360s
Reuse: [%luckperms_expiry_time_RandomIvStore.use%] will not return the valid time normally

### Expected Behaviour

Back to the countdown correctly

### Server Details

paper1.16.5

### LuckPerms Version

v5.3.77

**Comment by OmegaWeaponDev** [comment]
Hi @liaojinmin 

Make sure you are using PlaceholderAPI (or MVDWPapi) depending which plugin you're displaying the placeholder in and make sure you have the Luckperms Expansion installed if you're using PlaceholderAPI

**Comment by liaojinmin** [comment]
I am pretty sure that I have used PlaceholderAPI and installed the extension. When I set other temporary permissions, I didn’t find any exceptions.
An accident occurred when I used this special special statement [RandomlvStore.use]
You can test to make sure I am telling the truth.

**Comment by 157946a** [comment]
@OmegaWeaponDev This reason has been identified, it is caused by the case of the letter, no matter where the letter is capitalized, it can never be detected

**Comment by Laarryy** [comment]
if you use lowercase placeholders, everything works?

**Comment by 157946a** [comment]
> if you use lowercase placeholders, everything works?

yes

**Comment by lucko** [comment]
This is technically a bug with the placeholder expansion, but to be honest you should just lowercase all of your permissions 😛
