### ISSUE TITLE
Issue with Extra Contexts and World Guard

### ISSUE THREAD

**Issue by soupcoup** [LuckPerms/LuckPerms#3215]
### Description

any attempt to permit a specific group to have any sort of permission to build in a world guard region (either adding the group to members, or owners of an area or adding the permission to that group specifically manually) Crashes my server once any block is actually broken, even blocks outside of that region once the player is in the region will result in a crash. the log is insanely long the console flips out for a few minutes every time it happens preventing me from obtaining most of it but i will get what i can

### Reproduction Steps

Install luck perms
install world guard
install Extra contexts
Ensure Permissions are in place
Create a region

/rg addmember -w world test g:default 

break a block as a default member within that region

wait a few seconds after no block drops

### Expected Behaviour

Default player should receive item and the server should continue to work

### Server Details

Spigot Latest Version

### LuckPerms Version

v5.3.74

### Logs and Configs

https://gist.github.com/6d78ef6182b28fb6e2c0d8bf08a41dd1#file-minecraft-crash-log

### Extra Details

I Do have a lot of plugins that could be causing problems but i have nothing else related to permissions or block/region management and it seems to me that there is some sort of communication issue that is the problem between world guard and luck perms because i had a really hard time getting it to acknowledge luck perms groups existed at first and don't remember how i got that to work

**Comment by Laarryy** [comment]
As this issue may crash certain low-powered browsers, could I please ask you to copy the log into a GitHub gist, and send the link for the gist instead? Make sure to edit the issue to delete the log here and replace it with a link to the gist. Thanks!

**Comment by soupcoup** [comment]
can do thank you for giving me a heads up

**Comment by soupcoup** [comment]
The mininimum amount of plugins i was able to recreate this with was 
DiscordSRV
ExtraContexts
GriefPrevention
Luckperms
MythicMobs
WorldEdit
WorldGuard
Was the error i got this time

https://gist.github.com/soupcoup/986101d843f8189a60ff85df40bbc3bb#file-gistfile1-txt

**Comment by Laarryy** [comment]
The way you described adding permissions originally is through the `/rg` command mentioned in the issue. To use LP's extracontexts, you create the region and then give a permission with the appropriate context (iirc it's something like `wg-region=namehere`). Make sure it's also enabled in the ExtraContexts config.
