### ISSUE TITLE
1.18 update - Fabric

### ISSUE THREAD

**Issue by Aurelien30000** [LuckPerms/LuckPerms#3217]
### Description

Due to the changes in 1.18 update, ``luckperms-fabric`` needs adaptations and fixes, here is an error I faced with:

Thanks!

### Reproduction Steps

Start a 1.18-pre server using latest LuckPerms fabric.

### Expected Behaviour

No server error on login and ability to join the game.

### Server Details

Fabric 1.18-pre8

### LuckPerms Version

v5.3.77

### Logs and Configs

https://paste.domicraft.fr/agolerabud.php

**Comment by emilyy-dev** [comment]
Hey there! Thanks for sharing the error with us, however LP for Fabric (and other platforms) will be updated when stable versions of 1.18 are released.

**Comment by Aurelien30000** [comment]
Thanks anyways, mc 1.18 is in release-candidate state so stable release is near ;)
