### ISSUE TITLE
add some to group

### ISSUE THREAD

**Issue by splatchoot** [LuckPerms/LuckPerms#3218]
### Description

hi. i tried to add someone to the member group, and everytime, luckpers say that the operation is done, but the players is still not in the group.

information : 
server version : 1.17.1
server hoster : https://server.pro
server : spigot / buckit ( i am not shure wish one)
online=false

### Reproduction Steps

none

### Expected Behaviour

none

### Server Details

Bukkit 1.17.1

### LuckPerms Version

v5.3.47

**Comment by ZeromaniacMc** [comment]
Hi there. 
Would you mind checking the following command please `/lp user <name> info`? Does the group show up in this info command? If so, then luckperms works perfectly fine. Remember that luckperms does not add prefixes to chat or the player list by itself. If the group does not get listed in that command, let us know so we can investigate further together :)

**Comment by Laarryy** [comment]
Closed for inactivity - assuming that things are working now. If they aren't, please open a new issue after testing with the latest version from https://luckperms.net/
