### ISSUE TITLE
RGB with Sunlight plugin

### ISSUE THREAD

**Issue by Bricec6** [LuckPerms/LuckPerms#3222]
### Description

Hello I have a problem with the RGB of luckperms and the SunLight plugin.

The RGB is not displayed when calling the placeholder, it should translate the colors in the placeholders before returning it.
the sunlight plugin works with the rgb code; #rrggbb 

![image](https://user-images.githubusercontent.com/51750055/143719865-6e5ed13d-b8e6-4e74-bfa9-9bcd7bcb77bc.png)
![image](https://user-images.githubusercontent.com/51750055/143719873-41456cda-7cff-47a7-bf7c-25e2c2b1048d.png)

the developer told me that LuckPerms should normally translate the colors before returning them in the placeholder

thank you for support!

### Reproduction Steps

explained above

### Expected Behaviour

explained above

### Server Details

git-Purpur-1423 (MC 1.17.1)

### LuckPerms Version

v5.3.74

**Comment by emilyy-dev** [comment]
> the developer told me that LuckPerms should normally translate the colors before returning them in the placeholder

This is untrue, LuckPerms does not perform any formatting when it gets and returns a prefix/suffix/other meta, **that is the job of each plugin that *uses*  those features**.
Keep in mind that LuckPerms has to work and be compatible with not just one plugin using one format, but with many dozens of chat/tab/name-tag/scoreboard plugins using multiple formats (legacy formatting, JSON, MiniMessage, ...); some plugins will use `#rrggbb`, others `&#rrggbb`, others use `<#rrggbb>` or `&x&r&r&g&g&b&b`, LP simply cannot conform to all of those non-standard formats.
For this reason LP simply does not perform any formatting and just provides the prefix/suffix/other meta "as-is", exactly as stored, and it's the plugin asking for those elements to apply the formatting according to their formats after receiving them.
