### ISSUE TITLE
Luckperms MySQL not working 

### ISSUE THREAD

**Issue by dytdyt123** [LuckPerms/LuckPerms#3227]
### Description

ERROR java.util.concurrent.CompletionException: java.sql.SQLException: Unable to get a connection from the pool. (hikari is null)
01.12 18:30:15 [Server] ERROR at me.lucko.luckperms.common.storage.Storage.lambda$future$0(Storage.java:93)
01.12 18:30:15 [Server] ERROR at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
01.12 18:30:15 [Server] ERROR at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
01.12 18:30:15 [Server] ERROR at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
01.12 18:30:15 [Server] ERROR at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
01.12 18:30:15 [Server] ERROR at java.base/java.lang.Thread.run(Thread.java:831)
01.12 18:30:15 [Server] ERROR Caused by: java.sql.SQLException: Unable to get a connection from the pool. (hikari is null)
01.12 18:30:15 [Server] ERROR at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:171)
01.12 18:30:15 [Server] ERROR at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.getPlayerUniqueId(SqlStorage.java:676)
01.12 18:30:15 [Server] ERROR at me.lucko.luckperms.common.storage.Storage.lambda$getPlayerUniqueId$22(Storage.java:272)
01.12 18:30:15 [Server] ERROR at me.lucko.luckperms.common.storage.Storage.lambda$future$0(Storage.java:88)
01.12 18:30:15 [Server] ERROR ... 5 more
01.12 18:30:16 [Multicraft] Nightmare__TW ran command: lpb user Dyavid permission set luckperms.* true
01.12 18:30:19 [Server] ERROR java.util.concurrent.CompletionException: java.sql.SQLException: Unable to get a connection from the pool. (hikari is null)
01.12 18:30:19 [Server] ERROR at me.lucko.luckperms.common.storage.Storage.lambda$future$0(Storage.java:93)
01.12 18:30:19 [Server] ERROR at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
01.12 18:30:19 [Server] ERROR at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
01.12 18:30:19 [Server] ERROR at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
01.12 18:30:19 [Server] ERROR at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
01.12 18:30:19 [Server] ERROR at java.base/java.lang.Thread.run(Thread.java:831)
01.12 18:30:19 [Server] ERROR Caused by: java.sql.SQLException: Unable to get a connection from the pool. (hikari is null)
01.12 18:30:19 [Server] ERROR at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:171)
01.12 18:30:19 [Server] ERROR at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.getPlayerUniqueId(SqlStorage.java:676)
01.12 18:30:19 [Server] ERROR at me.lucko.luckperms.common.storage.Storage.lambda$getPlayerUniqueId$22(Storage.java:272)
01.12 18:30:19 [Server] ERROR at me.lucko.luckperms.common.storage.Storage.lambda$future$0(Storage.java:88)
01.12 18:30:19 [Server] ERROR ... 5 more

config:

storage-method: MySQL
data:
  address: host:mysql.apexhosting.gdn
  database: apexMC1073799
  username: root
  password: '-'
  pool-settings:
    maximum-pool-size: 10
    minimum-idle: 10
    maximum-lifetime: 1800000 # 30 minutes
    keepalive-time: 0
    connection-timeout: 5000 # 5 seconds
    properties:
      useUnicode: true
      characterEncoding: utf8
      #useSSL: false
      #verifyServerCertificate: false
  table-prefix: 'luckperms_'
  mongodb-collection-prefix: ''
split-storage:
  enabled: false
  methods:
    user: h2
    group: h2
    track: h2
    uuid: h2
    log: h2

### Reproduction Steps

idk

### Expected Behaviour

idk

### Server Details

papermc 1.17.1

### LuckPerms Version

v5.3.83

**Comment by PoolPirate** [comment]
I have a somewhat similar issue on Luckperms Velocity using postgres as storage engine.
The storage fails to initialize because of a missing class. (I have no idea why it is missing, I have just downloaded the latest version of LP) After that all attempts to use the storage obviously fail with the same error as above as there just is no instance available.
<img src="https://s.playwo.de/v/bXqmX"/>

**Comment by Laarryy** [comment]
@PoolPirate all you need to do is delete the `LuckPerms/libs` folder and restart the server. 

@dytdyt123 the issue is unfortunately not with LP, but with hikari/your database/connection setup. You may have some other plugin which is connected to the database freezing or using connections without properly disposing of them. Try reproducing without anything else connected to the database, and ensure your own connection is solid.

**Comment by dytdyt123** [comment]
fixed
