### ISSUE TITLE
Can't set minecraft commands in Fabric 1.18

### ISSUE THREAD

**Issue by Bambanah** [LuckPerms/LuckPerms#3228]
### Description

LuckPerms is unable to set any minecraft.* commands in Fabric

### Reproduction Steps

Assign minecraft.* permission to any user, and attempt to use a built-in minecraft command

### Expected Behaviour

I expect to be able to use any of the built-in minecraft commands.

### Server Details

Fabric 1.18

### LuckPerms Version

5.3.86

**Comment by lucko** [comment]
Use https://github.com/TjeuKayim/minecraft-command-permissions-fabric
