### ISSUE TITLE
PERMS NOT KEPT ON DEATH

### ISSUE THREAD

**Issue by VovelPunch** [LuckPerms/LuckPerms#3230]
### Description

I use Multiverse and especially Mohist with Mods and for some of reason permissions from LuckPerms are not kept when I or others die very weird.

### Reproduction Steps

download latest mods file from curseforge https://www.curseforge.com/minecraft/modpacks/last-man-standing and then join thelastman.nodecraft.gg then go factions and do /ec you will see you can access your personal enderchest from essentials but if you then die by anymeans you will nolonger have access to /ec and I assume this will happen in future too I have used other plugins but none are as nearly as decent as LuckPerms

### Expected Behaviour

well to put it simple permissions should not change if you die for any servers modded or not modded but then again am I doing something wrong?

### Server Details

thelastman.nodecraft.gg

### LuckPerms Version

v5.3.1

### Logs and Configs

https://gist.github.com/VovelPunch/2c756c47e84e61cfd0dc551b4ddfc3d1

### Extra Details

FORGE CLIENT

**Comment by underscore11code** [comment]
You are on an extremely outdated version. Please try the [latest version](https://luckperms.net/download).

**Comment by Laarryy** [comment]
You may also have another mod interfering. Please do try on the latest version as _11 suggests, but also do it with only LP and one other well-trusted mod only, testing its permissions that way.

**Comment by VovelPunch** [comment]
it is a issue with EssesntialsX and Mohist... They have some kinda disbute.
