### ISSUE TITLE
lp user info not showing type support for Microsoft accounts

### ISSUE THREAD

**Issue by Greymagic27** [LuckPerms/LuckPerms#3233]
### Description

When using the command ``/lp user Greymagic27 info`` it displays the account type as 'type: mojang'. This, however, is false as the account is migrated so should display as 'type: microsoft'

### Reproduction Steps

1) Run the command ``/lp user [USERNAME] info`` with any migrated Minecraft account
2) Observe that the account type still displays as 'mojang' despite the account being migrated

### Expected Behaviour

The account should display as 'type: microsoft' as it has been migrated and is no longer a microsoft account

### Server Details

git-Paper-66 (MC: 1.18) - 1.18-R0.1-SNAPSHOT

### LuckPerms Version

LuckPerms v5.3.88

**Comment by lucko** [comment]
This feature purely distinguises between accounts that are "official" (i.e. actual Minecraft accounts) and cracked accounts (i.e. players who have connected to an offline-mode/cracked server and chosen their own username)

**Comment by Greymagic27** [comment]
Ah ok. So it's not meant to distinguise between a Mojang and a Microsoft account? Just between official and cracked?

**Comment by lucko** [comment]
Correct.

I've made some changes in the commit above to clarify this (changed the wording and added a short description on hover)

<img width="966" alt="Screenshot 2021-12-10 at 23 45 29" src="https://user-images.githubusercontent.com/8352868/145654706-2829fcc0-883c-41aa-b89f-566820a544f7.png">
