### ISSUE TITLE
Language always English on console

### ISSUE THREAD

**Issue by myunco** [LuckPerms/LuckPerms#3236]
### Description

As of version 5.3.86, language always English

### Reproduction Steps

use v5.3.86 or newer version:
![86](https://user-images.githubusercontent.com/26001944/145676395-93746c39-3ffd-4f96-a357-65cd6ae0be00.png)
![89](https://user-images.githubusercontent.com/26001944/145676397-2edda73e-63ba-42da-99c3-ce02fd2a8fe0.png)

### Expected Behaviour

use system default language:
![85](https://user-images.githubusercontent.com/26001944/145676373-faf24590-1bd5-4f24-80ed-6015db91923a.png)

### Server Details

git-Paper-399 (MC: 1.17.1)

### LuckPerms Version

v5.3.89

### Extra Details

It seems to be caused by update dependencies

**Comment by lucko** [comment]
Thanks for reporting, I've opened an issue in the text library LP uses to track the issue, as it was introduced there.
