### ISSUE TITLE
No error messages when exporting without filename

### ISSUE THREAD

**Issue by omit01** [LuckPerms/LuckPerms#3239]
### Description

When exporting permissions with the command `/lp export --without-users` and fogetting the name of the file to export to, there is no output to the user in the chat. But there is an error in the console because there is no name given

### Reproduction Steps

1. Go into a server (in this case a Purpur 1.17. Hotfix 2) with luckperms
2. Try to export with `/lp export --without-users`, don't give a name for the file
3. Wonder why you don't get feedback in chat and look in the console to see the error

### Expected Behaviour

An error is given in chat where Luckperms says: Command Usage ....

### Server Details

purpur-1.17.1-hotfix2

### LuckPerms Version

V5.3.70

### Logs and Configs

https://gist.github.com/omit01/39ecc407d77d971f488b29be3b82bf75

**Comment by lucko** [comment]
This is now resolved, thanks to @OmegaWeaponDev
