### ISSUE TITLE
Provide new API to access permission and meta result origin data

### ISSUE THREAD

**Issue by bloodmc** [LuckPerms/LuckPerms#3243]
### Description

While debugging permission issues for my plugin GriefDefender, it can sometimes be very hard to track down exactly what permission or meta is causing a bad result. The verbose tool definitely helps but I cannot take the data to use for my own debugger. 

### Proposed Behaviour

A new API method to access more contextual information regarding a permission or meta lookup result. The extra information would include the origin holder and contexts where the permission was found. This would allow plugins, such as GriefDefender, to provide this additional data in their own debugger for users to easily identify a permission causing an issue.

**Comment by Rasgnarok** [comment]
Following
