### ISSUE TITLE
prefix

### ISSUE THREAD

**Issue by MayOPR823** [LuckPerms/LuckPerms#3246]
### Description

Hi, I'm Ratio and I want to report a problem, when I put / lp group God meta setprefix 1 and my display, it tells me that it is already there, but when I set the range and put something in the chat, it only put {PREFIX} Ratio

### Reproduction Steps

That the {PREFIX} disappears and just put the range and name

### Expected Behaviour

I thought I would put my range

### Server Details

MultiCraft Aternos MC:1.17.1

### LuckPerms Version

5.3.86

**Comment by OmegaWeaponDev** [comment]
Hi,
Luckperms does not handle displaying anything in chat or any other place. If the player displays correctly in `/lp user <name> info` than luckperms is doing it's job and it's upto your chat plugin to correctly display the prefix.
