### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by TenReeez** [LuckPerms/LuckPerms#3249]
### Description

I was told by #Read the Wiki to post this here as they have never seen this error before.

https://pastebin.com/0UcVGmb1

### Reproduction Steps

When I do /lp editor in game, the error appears in console.

### Expected Behaviour

for no errors appear when I do /lp editor

### Server Details

git-paper-81  (1.18.1)

### LuckPerms Version

LuckPerms-Bukkit-5.3.89.jar

### Logs and Configs

https://pastebin.com/0UcVGmb1

### Extra Details

I think it is also taking to long between /lp editor and the link to appear

**Comment by OmegaWeaponDev** [comment]
Hi @TenReeez 
Can you please try either restarting the server or updating luckperms to the latest version and see if it helps to resolve the issue. If not, could you please provide the output from `/lp info`

**Comment by Laarryy** [comment]
The pastebins in this issue are removed or expired - please use a GitHub Gist or similar to re-upload the information if you're still facing this issue. If not, this issue will be closed shortly.

**Comment by TenReeez** [comment]
https://pastebin.com/CPWYMvhK

Sorry my fault, Here it is ^ 
It also takes around 5 seconds to bring up link, when lp editor is run

**Comment by OmegaWeaponDev** [comment]
Hi,
Can you please show me the output from `/lp info`

**Comment by OmegaWeaponDev** [comment]
The error is just basically caused by there being a delay between your database and the server. Which is why it takes a while for it to generate the link for you. As it's taking longer than normal to retrieve the data from the database. It's something you'll need to look into from your database side of things.

**Comment by TenReeez** [comment]
To easy. thank you Omega!
