### ISSUE TITLE
Spaces in the nickname

### ISSUE THREAD

**Issue by Egor-Ermolaev** [LuckPerms/LuckPerms#3252]
### Description

Actions with players who have gaps in the nickname are impossible.

### Proposed Behaviour

You can enter player names with spaces.

### Extra Details

I use Nukkit.

**Comment by OmegaWeaponDev** [comment]
Hi @Egor-Ermolaev 

There is an allow-invalid-names option in the config.yml that you can set to true, then you can try wrapping the username in `" "` and see if that works.

**Comment by Egor-Ermolaev** [comment]
> Привет @Егор-Ермолаев
> 
> В файле config.yml есть опция разрешить недопустимые имена, которую вы можете установить в значение true, затем вы можете попробовать обернуть имя пользователя в `" "` и посмотрим, сработает ли это.



> Hi @Egor-Ermolaev
> 
> There is an allow-invalid-names option in the config.yml that you can set to true, then you can try wrapping the username in `" "` and see if that works.

This feature is enabled. I use the command (lsuser "friday yt" permission set global.yt ), but it outputs [LP] Command not recognized. This happens to everyone who has a gap in the nickname.

**Comment by OmegaWeaponDev** [comment]
The command is `lp user` not `lsuser`

**Comment by Egor-Ermolaev** [comment]
my translator decided to translate it differently) This doesn't work either

**Comment by OmegaWeaponDev** [comment]
It may not be possible then. It might be something to look into later. You can use the players UUID if the username does not work. So try that.

**Comment by Egor-Ermolaev** [comment]
Thanks, it works
