### ISSUE TITLE
Tab complete/command error

### ISSUE THREAD

**Issue by Altruiis** [LuckPerms/LuckPerms#3256]
### Description

When trying to tab complete or perform pretty much any command, an error is given. Permissions still currently work, but I cannot add or remove permissions to groups or users, or use the editor. Doing just the base command, `/lp` also throws an error.

### Reproduction Steps

1. Attempt /lp group <group> or /lp user <user> or any other command with arguments
2. Tab complete causes errors
3. Pressing enter also throws an error and does not run the command

### Expected Behaviour

It should tab complete and run the command successfully.

### Server Details

git-Paper-99 (MC: 1.18.1)

### LuckPerms Version

v5.3.89

### Logs and Configs

Tab Complete error:
https://pastebin.com/Jqq7N9BX

Command error:
https://pastebin.com/hABK9Pcj

### Extra Details

Before 1.18, the plugin worked flawlessly, so I assume it has something to do with 1.18(.1).

**Comment by OmegaWeaponDev** [comment]
Hi @Altruiis 

Please firstly try restarting the server. If that fails to work please try re-downloading Luckperms and install it again and see if that resolves the issue.

**Comment by Classicalad** [comment]
I had this same exact issue, and a restart resolved it.

**Comment by Altruiis** [comment]
It was still occurring after a couple restarts, but updating Paper seemed to work for whatever reason. Thanks!
