### ISSUE TITLE
TImed group

### ISSUE THREAD

**Issue by PanHaskins** [LuckPerms/LuckPerms#3260]
### Description

Good day. You could add the time to add to the current timing group/permissions. 

### Proposed Behaviour

Because for example, if he buys a VIP for 30 days and then buys another one for 30 days (30+30 = 60 days), but only the first 30 days remain. Well thank you.

**Comment by OmegaWeaponDev** [comment]
This is already currently a thing. https://luckperms.net/wiki/Permission-Commands#lp-usergroup-usergroup-permission-settemp-node-truefalse-duration-temporary-modifier-context

Just add a temporary modifier of accumulate and it wi add the extra time.
