### ISSUE TITLE
NullPointerException on /lp editor

### ISSUE THREAD

**Issue by bouchbi** [LuckPerms/LuckPerms#3263]
### Description

Hi, I have a weird issue with LuckPerms, everything was working fine until eventually I wasn't able to run /lp editor anymore

### Reproduction Steps

Connect to a server with luckperms, and execute the command /lp editor

### Expected Behaviour

I was expecting this command to send the message with the link of the web editor

### Server Details

mohist-1.16.5-865

### LuckPerms Version

5.3.97

### Logs and Configs

https://gist.github.com/bouchbi/26e44a8293bb438d1f02bc44afd3be08

**Comment by lucko** [comment]
Should be fixed in v2.3.98, thanks
