### ISSUE TITLE
setting * to false does not disable all commands on fabric server

### ISSUE THREAD

**Issue by juusukun** [LuckPerms/LuckPerms#3265]
### Description

Minecraft 1.18.1
Fabric loader 0.12.12
fabric-api 0.45.0+1.18

I've got my groups set up and I started with the lowest one players will default to. Trying to disable all in game commands, and then enable them one by one. I've tried setting .* to false (thats how it was done on Player Roles which I had to switch from), * . * (without spaces, the * disappear here for some reason) to false, and even * to false (suggested on a spigot forum here https://www.spigotmc.org/threads/luckyperms-disable-all-default-permissions.409235/) and I'm not having any luck

user is not op, user is only in the group that I'm working on, and all non-op commands are still accessible.

### Reproduction Steps

set up groups
add player to group
set * permission to false for group

group still has access to non OP commands

### Expected Behaviour

all commands should be blocked by setting * to false, and then individually enabled by setting each one to true

### Server Details

fabric 1.18.1

### LuckPerms Version

v5.3.86

**Comment by juusukun** [comment]
seems like the problem is bigger than I thought, even manually specifying permissions doesn't work, most of the time.

examples:
setting c2me.* to false doesn't stop access to /c2me commands
setting c2me.notick to false doesnt stop the specific command /c2me notick
setting servercore to false DOES stop any /servercore commands from being accessible
     setting it to true gives access
setting servercore.reload to false does not remove access from running /servercore reload

it seems some plugins work, some don't. also basic op game commands like /stop or /give cannot be enabled. only four mods/commands show up as an option to autocomplete by hitting tab: entityviewdistance, healthcare, servercore, and styledchat. I'm running a lot of other mods that don't show up and LuckPerms seems to have no effect on. Here's my full mod list:

https://pastebin.com/ExUrhAbR

**Comment by emilyy-dev** [comment]
resolved in discord
