### ISSUE TITLE
Big thread worker pool allocations?

### ISSUE THREAD

**Issue by LucidAPs** [LuckPerms/LuckPerms#3268]
### Description

I run jprofiler on a local server, I recorded memory call stacks and other allocations, I am not quite sure what I am seeing but I wanted to share.
![Screenshot 2022-01-06 123134](https://user-images.githubusercontent.com/42933023/148369837-a3dd434c-dfbd-43f0-a830-fe25d2b63fb3.png)
![Screenshot 2022-01-06 123007](https://user-images.githubusercontent.com/42933023/148369842-bddca5f1-9cbe-4000-8b54-726cc34d118b.png)
![Screenshot 2022-01-06 122950](https://user-images.githubusercontent.com/42933023/148369844-64b49cdb-1520-4dc3-811d-94165577af9e.png)
![Screenshot 2022-01-06 122928](https://user-images.githubusercontent.com/42933023/148369846-eb0cad9c-3fb1-4ae3-a179-d561c039a9fd.png)

### Reproduction Steps

[LP] Running LuckPerms v5.3.98.

### Expected Behaviour

I am not sure

### Server Details

git-Purpur-1489 (MC: 1.18.1)

### LuckPerms Version

LuckPerms v5.3.98

**Comment by Laarryy** [comment]
Nothing here indicates something wrong, unless I'm missing something. What you're seeing is expected and very low in terms of performance impact for what LP is actually doing!
