### ISSUE TITLE
Best Suggestion Ever. LuckPerms Database

### ISSUE THREAD

**Issue by FullSendMCdev** [LuckPerms/LuckPerms#3272]
### Description

Make a LuckPermsDB.exe program like a SQL but its only functionality is syncing servers. For a newer server dev like me who is running a network on my own pc setting up a SQL database is too big of a task. It could also have a new plugin or a config file accompany it to make it very easy. I have been working on databse setup for days and can not get it right. Sometimes I think it is working but then it doesnt. If someone wants to help I need it!

### Proposed Behaviour

Having this would give users a much better luckperms experience during bungeecord server setup.

**Comment by underscore11code** [comment]
There's very little chance this will ever happen, as LP wouldn't be able to maintain something that could even begin to compare with the industry standards like MySQL.

If you need help getting LP set up, we're more than happy to help here in a new issue, or [on our Discord](https://discord.gg/luckperms). If you need help getting a SQL DB set up, we can probably also help you.

**Comment by FullSendMCdev** [comment]
I did get it figured out eventually. Not very good documentation on how to connect each specific database.

**Comment by underscore11code** [comment]
On LP's end connection should be as simple as just putting the connection details in the appropriate places in the config. If that was the piece that you were experiencing issues with, then the suggestion of a LP-specific DB server wouldn't solve that issue, as it'd still need connection details to be configured.

If the issues you were experiencing were to do with getting the remote DB set up, then there's not much LP can do about it.

**Comment by Laarryy** [comment]
Marking this as out of scope - LP is not a database software and relies on industry standards to keep things working for everyone.
