### ISSUE TITLE
[LuckPerms] Command execution [editor] has not completed. Trace: 

### ISSUE THREAD

**Issue by haroldrc** [LuckPerms/LuckPerms#3273]
### Description

  java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method)
  java.base@17.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
  java.base@17.0.1/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
  java.base@17.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
  java.base@17.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
  java.base@17.0.1/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
  java.base@17.0.1/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2117)
  me.lucko.luckperms.common.webeditor.WebEditorRequest.lambda$findMatchingOfflineUsers$9(WebEditorRequest.java:258)
  me.lucko.luckperms.common.webeditor.WebEditorRequest$$Lambda$11112/0x0000000802e78248.accept(Unknown Source)
  java.base@17.0.1/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
  java.base@17.0.1/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
  java.base@17.0.1/java.util.stream.SliceOps$1$1.accept(SliceOps.java:200)
  java.base@17.0.1/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:400)
  java.base@17.0.1/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
  java.base@17.0.1/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:528)
  java.base@17.0.1/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
  java.base@17.0.1/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
  java.base@17.0.1/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
  java.base@17.0.1/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
  java.base@17.0.1/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  java.base@17.0.1/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
  me.lucko.luckperms.common.webeditor.WebEditorRequest.findMatchingOfflineUsers(WebEditorRequest.java:257)
  me.lucko.luckperms.common.webeditor.WebEditorRequest.includeMatchingUsers(WebEditorRequest.java:219)
  me.lucko.luckperms.common.webeditor.WebEditorRequest.includeMatchingUsers(WebEditorRequest.java:200)
  me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:90)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:56)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:48)
  me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:263)
  me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:167)
  me.lucko.luckperms.common.command.CommandManager$$Lambda$11100/0x0000000802cf7b20.run(Unknown Source)
  java.base@17.0.1/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
  java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  java.base@17.0.1/java.lang.Thread.run(Thread.java:833)

### Reproduction Steps

/lp editor

### Expected Behaviour

editor

### Server Details

paper 1.18

### LuckPerms Version

v5.3.68

**Comment by TenReeez** [comment]
I get the same line of error:
0.01 12:29:06 [Server] WARN [LuckPerms] Command execution [editor] has not completed. Trace: 

I have also made a bug report

**Comment by OmegaWeaponDev** [comment]
Hi,
Can you please show me the output from `/lp info` 

Thanks,
OmegaWeaponDev

**Comment by cj1705** [comment]
I'm getting the same issue here too with the same stack trace. 
Below is my /lp info

[LP] Running LuckPerms v5.3.98 by Luck.
[LP] -  Platform: Bukkit
[LP] -  Server Brand: Paper
[LP] -  Server Version:
[LP]      git-Paper-408 (MC: 1.17.1) - 1.17.1-R0.1-SNAPSHOT
[LP] -  Storage:
[LP]      Type: MySQL
[LP]      Ping: 71ms
[LP]      Connected: true
[LP] -  Extensions:
[LP]      None
[LP] -  Messaging: Sql
[LP] -  Instance:
[LP]      Static contexts: None
[LP]      Online Players: 1 (3 unique)
[LP]      Uptime: 15m 41s
[LP]      Local Data: 1 users, 54 groups, 0 tracks

**Comment by haroldrc** [comment]
[03:51:47 INFO]: [LP] Running LuckPerms v5.3.68 by Luck.
[03:51:47 INFO]: [LP] -  Platform: Bukkit
[03:51:47 INFO]: [LP] -  Server Brand: Airplane
[03:51:47 INFO]: [LP] -  Server Version:
[03:51:47 INFO]: [LP]      git-Airplane-"74774a0" (MC: 1.17.1) - 1.17.1-R0.1-SNAPSHOT
[03:51:47 INFO]: [LP] -  Storage:
[03:51:47 INFO]: [LP]      Type: MySQL
[03:51:47 INFO]: [LP]      Ping: 4ms
[03:51:47 INFO]: [LP]      Connected: true
[03:51:47 INFO]: [LP] -  Extensions:
[03:51:47 INFO]: [LP]      None
[03:51:47 INFO]: [LP] -  Messaging: Redis
[03:51:47 INFO]: [LP] -  Instance:
[03:51:47 INFO]: [LP]      Static contexts: (server=realms)
[03:51:47 INFO]: [LP]      Online Players: 10 (114 unique)
[03:51:47 INFO]: [LP]      Uptime: 6h 32m 35s
[03:51:47 INFO]: [LP]      Local Data: 10 users, 286 groups, 19 tracks

**Comment by lucko** [comment]
Ok - LuckPerms will now run two SQL queries to load all users for an editor session instead of two per user. This should resolve the problem people are seeing here :)
