### ISSUE TITLE
Crash on server shutdown

### ISSUE THREAD

**Issue by r4nx** [LuckPerms/LuckPerms#3275]
### Description

EXCEPTION_ACCESS_VIOLATION is raised on server shutdown during saving the players; SQLite is used as a storage. I'm not sure if it's a fault of LuckPerms per se, maybe the problem lies in underlying SQLite driver or SQLite itself.

### Reproduction Steps

Set the storage type to SQLite, shutdown the server with `stop` command.

### Expected Behaviour

Absence of crash

### Server Details

git-Paper-132 (MC: 1.18.1)

### LuckPerms Version

v5.3.98

### Logs and Configs

[Crash log](https://gist.github.com/r4nx/e947a1a1fab3da3f6e9262d81211af12)
[Config](https://gist.github.com/r4nx/302666d66f9becc443591ea2ecdd670a)

Config is almost default, the only changed options are
- `storage-method: sqlite`
- `enable-ops: false`
- `auto-op: true`
- `commands-allow-op: false`

**Comment by r4nx** [comment]
.. And [another crash](https://gist.github.com/r4nx/2ccead37643367948b138a897a90dfe0) when started the server and shutdown it again

**Comment by OmegaWeaponDev** [comment]
Hi,
When you changed the storage-method to `sqlite` did you stop the server, then make the change, then start up the server? Or did you make the change then use something like a plugin manager plugin (i.e. plugMan) or use a /reload

Thanks,
OmegaWeaponDev
