### ISSUE TITLE
BungeeCoord does not accept commands ingame with user who has all perms.

### ISSUE THREAD

**Issue by vishyvishal14** [LuckPerms/LuckPerms#3279]
### Description

Latest version, broken

### Reproduction Steps

/lpb editor when logged in as user

### Expected Behaviour

some awt error

### Server Details

git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:21e4c1d:475

### LuckPerms Version

v5.3.98

### Logs and Configs

https://pastes.dev/Zi13wcq1pv

**Comment by benwoo1110** [comment]
Your logs show LuckPerms v5.3.5, please update first.

**Comment by vishyvishal14** [comment]
Yeah i realized that, close pls
