### ISSUE TITLE
Preffix and Suffix problem

### ISSUE THREAD

**Issue by Marek2810** [LuckPerms/LuckPerms#3280]
### Description

The server will incredibly lag and crash. Putting some prefix error on consle. 

### Reproduction Steps

idk

### Expected Behaviour

no crash

### Server Details

git-Paper-140

### LuckPerms Version

LuckPerms-Bukkit-5.3.86

### Logs and Configs

https://pastebin.com/E3f7jPyX

**Comment by OmegaWeaponDev** [comment]
Hi,
Those permission lag notice errors just mean that the server is lagging so it is taking longer for plugins to communicate with each other to receive player data. There isn't really anything we can do plugin side. It's more upto you to reduce or solve the lag that is happening on your server.

**Comment by Marek2810** [comment]
Idk, how... Start happening some days ago... With 2-4 players. I have 3 CPUs and 4GB ram. But thanks for answer.

**Comment by OmegaWeaponDev** [comment]
There are many things that can cause your server to lag. A good idea would be to review a timings or spark report so you can see what is happening and help narrow down where the lag is coming from.

**Comment by Marek2810** [comment]
Im new with VPS, linux and staf. Idk how to get spark report. I will try to google that. Thanks for help!
