### ISSUE TITLE
NoSuchMethodError:  net.luckperms.api.query.meta.MetaValueSelector.selectValue

### ISSUE THREAD

**Issue by Dockter** [LuckPerms/LuckPerms#3281]
### Description

Getting the following error in my IDE environment while working on a mod in conjunction with LuckPerms and Nucleus.

https://gist.github.com/Dockter/2f89566fbb8c515902df6360c1a4526b

### Reproduction Steps

- Minecraft 1.12.2
- Luckperms 5.3.98
- Nucleus (latest bleeding from repo + single player PR)

### Expected Behaviour

The task scheduler is running a process in Nucleus which is making API calls back to Sponge, Luckperms is then creating this NoSuchMethodError.

### Server Details

SpongeForge-1.12.2-7.4.5

### LuckPerms Version

v5.3.98

### Logs and Configs

https://gist.github.com/Dockter/2f89566fbb8c515902df6360c1a4526b

**Comment by lucko** [comment]
Most likely due to a misconfigured classpath in your dev environment.

The error suggests an older version of the LuckPerms API (it's a separate artifact that other mods/plugins can depend on) is on the classpath compared to the one the LuckPerms plugin is providing.

**Comment by lucko** [comment]
59f3866e3625842c26f2eafdc5c00871570a43c0 might help too.
