### ISSUE TITLE
Error - java.lang.RuntimeException: Error uploading data to bytebin

### ISSUE THREAD

**Issue by MrDciBelia** [LuckPerms/LuckPerms#3283]
### Description

As soon as a grade change is made, a big error appears in the console and nothing happens. I changed version for a higher version but still the same problem.

### Reproduction Steps

I use /lp editor

### Expected Behaviour

Editor and update group

### Server Details

CraftBukkit-Spigot (MC:1.16.5)

### LuckPerms Version

v5.3.98

### Logs and Configs

https://gist.github.com/MrDciBelia/949d55bfef0ddf073d8f1dcda4eb1a69

### Extra Details

![lp-info](https://user-images.githubusercontent.com/94740517/149640991-2fd8abba-2d83-41c4-a48e-fbb0d5b07f69.png)

**Comment by katorly** [comment]
Same issue occured to me.

**Comment by lucko** [comment]
`java.net.SocketTimeoutException: timeout`

Either an issue at my end or at yours.

It's stable now, so if it's still not working then most likely the problem is with the internet connection at your end :)
