### ISSUE TITLE
Add Pocketmine Support

### ISSUE THREAD

**Issue by BensaTV** [LuckPerms/LuckPerms#3284]
### Description

I know it would need a whole rewrite and a lot of time since all the other supported plattforms are java based but I think that Pocketmine support is really important since a lot of servers are running it on bedrock and there is no good permission system. Also there are plugins that only work on either Nukkit or Pocketmine which means some gamemodes run nukkit while others run Pocketmine but without Luckperms for Pocketmine I would need to use 2 sepereated permission system.

### Proposed Behaviour

It won't really affect the project itself. This Suggestion is just adding something without removing/changing anything.

**Comment by lucko** [comment]
Sorry, I'm not interested in a rewrite in a different programming language :)

maybe someone else can give it a try!
