### ISSUE TITLE
Multi prefix calculation is not well concatened on the bungee

### ISSUE THREAD

**Issue by Uharn** [LuckPerms/LuckPerms#3288]
### Description

Players have 4 tracks with prefix set to take the highest of each one
When I do /lp user <user> info, the prefix is nicely calculated
When I do /lpb user <sameuser> info, the prefix only takes one prefix instead of all

### Reproduction Steps

-have 4 tracks

-use the following prefix config on both bukkit and bungee
prefix:
  format:
    - 'highest_on_track_employe'
    - 'highest_on_track_vip'
    - 'highest_on_track_staff'
    - 'highest_on_track_joueur'
  duplicates: first-only
  
  parent add one player to a group of each track
  
 Compare /lp user info and /lpb user info

### Expected Behaviour

The prefix calculated on the bungee should be identical to the prefix calculated on the bukkit

### Server Details

Waterfall 1.18.1 + Pufferfish 1.18.1

### LuckPerms Version

LuckPerms-Bungee-5.3.98.jar

**Comment by Uharn** [comment]
I've tried using another redis and same behaviour: the bungee prefix only takes 1 prefix, no more.

**Comment by lucko** [comment]
If the prefixes are set in specific servers (using context) - then the contexts on Bungee must match for them to apply.

Check using `/lp(b) user <u> info` and the problem should be clear :)

**Comment by Uharn** [comment]
@lucko  i have nothing on specific server all prefixes are global

look at my issue i di check both /lp user info and /lpb user info and noticed a difference.

Please try me reproduction steps
