### ISSUE TITLE
Problem with permission staff chat plugin

### ISSUE THREAD

**Issue by TymekSL** [LuckPerms/LuckPerms#3290]
### Description

i have problem with luckperms bungeecord when i give helper (and moderator by group.helper) permission to staffchat.join and .read (with message [SC] [+] Nick join the lobby) but they didn't see it
but when i give permission to see afk message they can read it. I wrote to staff chat support they wrote its problem with luckperms, i wrote 5x message on support in 2 days - 0 help, can someone help?

### Reproduction Steps

I don't know, help?

### Expected Behaviour

All will working

### Server Details

bungeecord

### LuckPerms Version

v98

**Comment by lucko** [comment]
You can use the verbose command to debug what's going on :)

https://luckperms.net/wiki/Verbose
