### ISSUE TITLE
Minecraft Forge version

### ISSUE THREAD

**Issue by Minecraftschurli** [LuckPerms/LuckPerms#3291]
### Description

Since SpongeForge is still not available in versions > 1.12 a dedicated version of LuckPerms for forge would be nice.
Also since Forge in newer versions now has a proper Permissions API it would be nice to have a good permission manager like LuckPerms for it.

### Proposed Behaviour

Integrate LuckPerms with the Forge Permissions API

**Comment by LordSamosa** [comment]
I believe there is already a PR being worked on for this: https://github.com/LuckPerms/LuckPerms/pull/3262

**Comment by lucko** [comment]
Closing in favour of the PR
