### ISSUE TITLE
web editor idea

### ISSUE THREAD

**Issue by LeitoCc187** [LuckPerms/LuckPerms#3292]
### Description

okay so the idea is that you can make groups of perms and apply them to players as parents right but if your running a bungee you can either tie ever perm to specific servers or you can make a new group for each Rank(rank will be what I will say when I mean the main group) and you can add this new group to the rank and tie that group to the specific server. Now what if we could make categories and could apply those categories to a player as a parent and that category would then hold all the different groups that are tied to the specific servers and could make the web editor look nicer.

### Proposed Behaviour

![idea](https://user-images.githubusercontent.com/84422709/150663705-f4c6022f-57fa-4c6a-a251-1cd22c7eb1d7.png)
This is what it may look like.
i only did the owner role since that all i really needed to change to show
the categorys would be like folders you can open and close maybe with there own witgh or then maybe a thing that inly exists on the web editor to make it look cleaner 
Edit:
tecnickly the categorys could be used in tracks and group so that you could make a track that will  give you categorys and not groups this is to say yous add this idea ofc

### Extra Details

as you can see from what i didnt edit i use a group per server so that if plugins are added/removed i can find the perms that i need to remove/add easyer and faster this is the way i do it and categorys would help me idk how much it may help others but i think its somthing worth saying

**Comment by underscore11code** [comment]
This sounds like an overcomplicated way of per-server permissions, which we have [context](https://luckperms.net/wiki/Context) for.

**Comment by LeitoCc187** [comment]
it would be more of a visual way to separate the permissons by server insted of having multiple servers perms stuffed into one group

**Comment by Laarryy** [comment]
If you want to do this, all you need to do is nest your groups - make a 'category' group for each category and add all the parent groups and permissions you want to be a part of that category as a parent/permission of that group. Taking the idea of groups as-is and adding effectively groups to group the groups (when it can already be done) is out of scope for this plugin - sorry!
