### ISSUE TITLE
better analyze of Permission Calculation / debug methods for Permission Problems

### ISSUE THREAD

**Issue by RedstoneFuture** [LuckPerms/LuckPerms#3293]
### Description

This feature-resquest is an addition to my primary thread about problems with the permission calculation documentation: LuckPerms/wiki#132 **Please read this main thread before for all the context. I described the difficulties and listed an example why permission analyzing needs to be addressed and improved.**

### Proposed Behaviour

- Maybe a command that analyses the priority of a permission with a useful order list as chat output or web-interface.
- Make `/lp user/group <user|group> permission check <node>` check for contexts, like server or world, because it currently doesn't help with analyzing complex permission priorities.

![2022-01-22_17 58 30](https://user-images.githubusercontent.com/4140635/150649659-93ab53a9-782f-40cc-8f18-80e235b3c951.png)

**Comment by lucko** [comment]
The current `permission check` output is already pretty good imo.

2d662cbab960c73dbbccc780a50c39203cfb0fd7 has helped to decent extent too, not sure there's much more I can give in terms of info without it becoming overly complex.
