### ISSUE TITLE
Support env var

### ISSUE THREAD

**Issue by HookWoods** [LuckPerms/LuckPerms#3294]
### Description

Hello,
It would be really useful to have support for variable env. Actually, my company uses Kubernetes to auto-deploy server and we actually use var env to configure database credentials because they are dynamically created each time we redeploy our database and we can't modify them in the config every time.

### Proposed Behaviour

At the start of the plugin, it could use the java env API to take the value from the var env, or the one from the config if not found.
`System.getenv().getOrDefault("LP_XX", ...);`
The only problem with the actual system would be the object cast.

**Comment by lucko** [comment]
Closing in favour of your pull request
