### ISSUE TITLE
support UUID bedrock players

### ISSUE THREAD

**Issue by TOWUK** [LuckPerms/LuckPerms#3297]
### Description

![image](https://user-images.githubusercontent.com/28830162/151665191-1495fd1f-9143-43f7-adb9-7aec097eef01.png)
bedrock username not supported in LP, i set in config:

> 568 |...
> 569 | **allow-invalid-usernames: true**
> 570 |...

### Proposed Behaviour

just support nicknames and uuids bedrock users (geyserMC + floodgate)

**Comment by lucko** [comment]
See #2449

I think the floodgate authors were looking into it. I've added API which allows 3rd party plugins to override the UUID type detected by LP with their own. For now though, LP targets MC: Java Edition only, and the UUID hacks performed by Geyser/Floodgate/etc aren't officially supported.
