### ISSUE TITLE
Luckperm server side commands not recognized with client running Forge version 39.0.46 or later.

### ISSUE THREAD

**Issue by TheMethodicalJosh** [LuckPerms/LuckPerms#3299]
### Description

It seems that there may be a command precedence issue with the LuckPerms server plugin (Latest: v5.3.98) and Forge client mod (39.0.46 or later). 

**Forge developers state that plugin is not sending commands for client to register - https://github.com/MinecraftForge/MinecraftForge/issues/8438#issuecomment-1025177911**

----------------------------------------------------------------------------------------------------------------

https://github.com/MinecraftForge/MinecraftForge/pull/7754 - Add Client Commands

PR request above seems to be what has caused the issue.

### Reproduction Steps

1: Start Minecraft Paper 1.18.1 Server with LuckPerms Plugin Installed

2: Install Forge Mod Version 39.0.46 or later on client

3: Connect to Minecraft Paper Server with client running Forge

4: Use /luckperms or /lp commands to reproduce that command is not registered

### Expected Behaviour

When using a client running Forge 39.0.46 or later, LuckPerm v5.3.98 commands work as they do prior to 39.0.46.

### Server Details

git-Paper-177

### LuckPerms Version

v5.3.98

### Extra Details

This is able to be reproduced consistently.

**Comment by DarthUdp** [comment]
Yeah having the same issue downgrade of forge fixes it

**Comment by TheMethodicalJosh** [comment]
To anyone else having this issue:

https://github.com/MinecraftForge/MinecraftForge/issues/8438#issuecomment-1029526426

Since LuckPerms is using an older method of registering commands, an update in the Forge custom commands is causing a breakage. Unfortunately the only fix at the moment is to stay on or downgrade to 39.0.45 until LuckPerms updates to the newer way of registering commands that mark the commands as executable.

**Comment by lucko** [comment]
Fixed in https://github.com/lucko/commodore/commit/7bbcbe4f4722d5b670a074a0995bf24633d03885

**Comment by DarthUdp** [comment]
Thanks for the quick fix :)
