### ISSUE TITLE
OP can't command bukkit command.

### ISSUE THREAD

**Issue by NCSV** [LuckPerms/LuckPerms#3301]
### Description

bukkit permission was denied despite player is op,
i also applied bukkit.command.*, *

### Reproduction Steps

just put luckperms in server. give op to player, execute bukkit command.

### Expected Behaviour

i think is problems in config, but i can't figure it.

### Server Details

purpur-1.18.1

### LuckPerms Version

LuckPerms-Bukkit-5.3.98

### Logs and Configs

https://gist.github.com/NCSV/6660fcd905a15b5d4ba72e6a07f0f7a2

**Comment by lucko** [comment]
Doesn't sound like a bug, the LP discord is a better place for you to get help with this :)
