### ISSUE TITLE
The translation will not work when switching servers using bungee.

### ISSUE THREAD

**Issue by XXY233** [LuckPerms/LuckPerms#3304]
### Description

Suppose I have one bungee and two spigot, when I enter server A via bungee, the translation works fine, but when I switch from server A to server B, the translation does not work anymore.
But if I go directly to server B through bungee, then the translation will work fine.

### Reproduction Steps

1. Access Server A through bungee
2. Access server B using /server b
3. Enter /lp and you will see that the translation no longer works and is no longer displayed in the client language, but in English

### Expected Behaviour

1. Access server A through bungee
2. Enter server B using /server b
3. type /lp, lukperms is displayed as client language.

### Server Details

git-Paper-186(MC:1.18.1)

### LuckPerms Version

v5.3.98

**Comment by lucko** [comment]
Sounds like BungeeCord isn't correctly forwarding the players locale when they switch servers.

Are you sure you're using a recent BungeeCord release?
