### ISSUE TITLE
LuckPermsReseting after restart

### ISSUE THREAD

**Issue by Zidian5467** [LuckPerms/LuckPerms#3305]
### Description

Hey,i love luckperms but i have found a bug,every time after i set-up my permissions it works perfectly fine,but when i try restarting the server it resets the permissions..i have tried to set it up from the in-game commands and the /lp editor it still resets
can someone help me pls?

### Reproduction Steps

I dont really know

### Expected Behaviour

I expect someone to help me !!

### Server Details

Paper-MC Version 1.18.1

### LuckPerms Version

v5.3.70

**Comment by lucko** [comment]
Does your server working directory reset on restart?

Any errors in console?

Perhaps your hosting provider could help?
