### ISSUE TITLE
SQL issues.

### ISSUE THREAD

**Issue by MithrandirCraft** [LuckPerms/LuckPerms#3306]
### Description

The following issues started occuring after replacing GriefPrevention with GriefDefender, which makes heavy use of LuckPerms.

LP seems to be running "fine", but I get an error when executing /lp editor:
https://gist.github.com/MithrandirCraft/0193773d50167a12cea89a3adb2beb53
(eventually the editor link opens, but I believe sometimes it doesn't apply when saving).

Additionally, PAPI errors mentioning LuckPerms for some reason, are quite frequent:
https://gist.github.com/MithrandirCraft/2d02694e8521747a43142919a67e0a9e

I followed instructions in: https://luckperms.net/wiki/Storage-system-errors
Still haven't been able to determine if max sql connections are surpassed when the second error spams. It certainly isn't being surpassed normally. (150~/400 connections)

### Reproduction Steps

This may be something specific to my server's setup, amount of plugins/connections to sql, and the addition of GriefDefender, which makes heavy use of LP.

### Expected Behaviour

I'm expecting no errors.

### Server Details

git-Paper-182 (MC: 1.18.1)

### LuckPerms Version

5.3.98

### Extra Details

We're using MariaDB.

**Comment by lucko** [comment]
Duiplicate of #3273

I'll hopefully get some time to look into this soon.
