### ISSUE TITLE
User list resets

### ISSUE THREAD

**Issue by Dracathio** [LuckPerms/LuckPerms#3307]
### Description

So I spent a good hour deleting users out of the editor, for it to then be reset by the time I started the editor up again a day later.
This time though instead of the names it was all their UUIDs.

### Reproduction Steps

I haven't a clue really, probably delete a large chunk of users on the browser editor, then apply the changes, then wait a while.

The UUIDs will come back after a while and they no longer have names.

### Expected Behaviour

I expect the users deleted in the editor to not come back after a while.

### Server Details

Paper-1.18.1-177

### LuckPerms Version

LuckPerms-Bukkit-5.3.108

### Extra Details

Thank you for this awesome update to the plugin, I do hope the bugs and such get ironed out!

**Comment by Laarryy** [comment]
If this is a bug with the new live editor, you may want to open this issue on the LuckPerms/LuckPermsWeb repository! Seems like so to me!

**Comment by lucko** [comment]
I don't think this is related to the new changes.

After you deleted the users, did you create a new session to confirm they were gone? (in other words, did the deleting bit work?)

If it did, and they just came back later, then sounds like another plugin (perhaps) is re-creating the entries for the user by requesting data from LP.

**Comment by Dracathio** [comment]
Yea I'd close the session and open a new one, then the list of users would be back as UUIDs.

I was thinking that it could be getting users from other Databases in other plugins.   Seems I may need to go and delete all forms of UUIDs or such from other plugins and hope that fixes it.

Anyways Thank you for this awesome update Luck!
