### ISSUE TITLE
Granting all permissions doesn't work (*)

### ISSUE THREAD

**Issue by sitapea1337** [LuckPerms/LuckPerms#3310]
### Description

After update, * doesn't grant all permissions.
For example, if administrator group has * permission to true, then administrator cannot use /minecraft:kill command.

This happened, changed after latest update.

### Reproduction Steps

After update, * doesn't grant all permissions.
For example, if administrator group has * permission to true, then administrator cannot use /minecraft:kill command.

This happened, changed after latest update.

### Expected Behaviour

After update, * doesn't grant all permissions.
For example, if administrator group has * permission to true, then administrator cannot use /minecraft:kill command.

This happened, changed after latest update.

### Server Details

paper 1.18

### LuckPerms Version

5.4.0

### Extra Details

After update, * doesn't grant all permissions.
For example, if administrator group has * permission to true, then administrator cannot use /minecraft:kill command.

This happened, changed after latest update.

**Comment by OmegaWeaponDev** [comment]
You should technically avoid using the `*` permission as it can give un-wanted effects which can mess with things. It really should only be a temporary solution while you're setting up your permissions. Then with a proper permissions setup you shouldn't need it. 

Some plugins are created in a way which results in odd behaviour when the root '*' wildcard is used. More information:
https://nucleuspowered.org/docs/nowildcard.html

**Comment by OmegaWeaponDev** [comment]
Also, apart from what I mentioned above, You have copied-pasted the same response for multiple questions and not followed the instructions properly. Please re-open or resubmit your issue once you have fixed it up.

**Comment by sitapea1337** [comment]
I am aware that I should avoid using * permission, still it is being used, because it's easiest method to give all command permissions, every plugin etc.
If it breaks something, then I can find exceptions and give those permissions with "deny" setting, for example some bypass set to false.

As for reporting bug correctly - it has been reported, you understood and acknowledged it therefore it's your decision anyway what to do with this information.
If you want to fix that bug, then you'd probably do that, if not, then not.
I'm not the one that follows idiotic bueracracy for the reason "just-because".

**Comment by underscore11code** [comment]
> As for reporting bug correctly - it has been reported, you understood and acknowledged it therefore it's your decision anyway what to do with this information.
If you want to fix that bug, then you'd probably do that, if not, then not.
I'm not the one that follows idiotic bueracracy for the reason "just-because".

The issue template asks things for a reason. We need info to debug, and you haven't given it to us. You've effectively gone to the doctor and said "it hurts".

**Comment by emilyy-dev** [comment]
It's not "idiotic bureaucracy", it's so we have the necessary information for us to help you, because "in my permissions setup `*` works fine" so there must be something different between yours and mine, the only way for us to find out what's different in your setup is to provide the useful information that was asked.

**Comment by sitapea1337** [comment]
Yet still downloaded older version of LuckPerms, added it to blank server, added * permission and every command work.
Downloaded newest version on LuckPerms, added * permission and for example /minecraft:kill command doesnt work.

This issue/bug is newest version problem.

**Comment by underscore11code** [comment]
I'm glad you've made progress debugging. If you can either edit the initial message to answer all the questions, or open a new issue and answer all the questions there, we can actually do something about it.
