### ISSUE TITLE
Unable to suppress DynMap permissions for Default group

### ISSUE THREAD

**Issue by DrekiLunin** [LuckPerms/LuckPerms#3311]
### Description

I have set `False` for the server for the following permissions in a specific group, but the group members still have access to those commands in-game. What am I doing wrong? 

- dmap
- dmarker
- dynmap

I want these suppressed from the default group, but they are still available. 

Thank you. 

![image](https://user-images.githubusercontent.com/99612709/153769429-97ccdfcc-e98c-4ed6-a592-3fb9cd3cca2a.png)

### Reproduction Steps

1. Create Default Group
2. Set the above permissions to `false`
3. Log in as Default group member
4. Attempt to sue commands

### Expected Behaviour

The commands are not available

### Server Details

git-Paper-187 (MC: 1.18.1)

### LuckPerms Version

v5.3.86

**Comment by OmegaWeaponDev** [comment]
You have applied a world context for the world `world`. So they will be able to use those permissions (if granted by default) if they are in other worlds. Also check the plugin documentation for those plugins and maybe check with [verbose](https://luckperms.net/wiki/Verbose) as well. So you can see what is going on permission wise.
