### ISSUE TITLE
Luckperms not work properly with the latest forge (36.2.28) + SpongeForge

### ISSUE THREAD

**Issue by Eric-liucn** [LuckPerms/LuckPerms#3312]
### Description
luckperms cannot work properly with the latest build of sponge forge
Here is the full log, I have removed all other plugins or mods, only forge, spongeforge and luckperms 
https://gist.github.com/Eric-liucn/2550f5fa24fde4ed1f32b8fe58cf88d1

the spongeforge version is the latest build `spongeforge-1.16.5-36.2.5-8.0.0-RC1073-universal`

### Reproduction Steps

just put luckperms 5.4.2 into the plugin folder then start the server

### Expected Behaviour

just compatible with the latest version of spongeforge

### Server Details

spongeforge-1.16.5-36.2.5-8.0.0-RC1073-universal

### LuckPerms Version

LuckPerms-Sponge-5.4.2

### Logs and Configs

full log:
https://gist.github.com/Eric-liucn/2550f5fa24fde4ed1f32b8fe58cf88d1 

config(did't change anything):
https://gist.github.com/Eric-liucn/774edfe1cffb53ab613e60d539844d25

**Comment by lucko** [comment]
Hm, that class definitely exists: https://github.com/SpongePowered/SpongeAPI/blob/api-8/src/main/java/org/spongepowered/api/util/Tristate.java

Seems like some sort of classloading issue with either Sponge or Forge. Make sure you're using the latest versions of both, and if it still errors then might be worth raising with the Sponge devs :)

**Comment by lucko** [comment]
Actually I think this may be related to #3308, so I've raised an issue with Sponge myself :)

**Comment by lucko** [comment]
Should be resolved in LuckPerms-Sponge-5.4.4, SpongeVanilla 1.16.5-8.0.0-RC1074 and SpongeForge 1.16.5-36.2.5-8.0.0-RC1074
