### ISSUE TITLE
Function to delete all users

### ISSUE THREAD

**Issue by SnonSS** [LuckPerms/LuckPerms#3313]
### Description

Add a function on the LuckPerms editor site that should delete all users, otherwise it’s inconvenient to delete one user at a time if there are 500 or more of them, it would certainly not be bad if such a function was on the site, I hope you add it. 

### Proposed Behaviour

This useful feature will remove all users

**Comment by SnonSS** [comment]
> ### Description
> Add a function on the LuckPerms editor site that should delete all users, otherwise it’s inconvenient to delete one user at a time if there are 500 or more of them, it would certainly not be bad if such a function was on the site, I hope you add it.
> 
> ### Proposed Behaviour
> This useful feature will remove all users
> 
> ### Extra Details
> _No response_

**Comment by Turbotailz** [comment]
I said to open this on the LuckPerms/LuckPermsWeb repo (this is not the place for web requests).

Although come to think of it, I don't think this feature belongs there. Since the editor caps the user count this would be better suited as a plugin command.

**Comment by SnonSS** [comment]
Excuse me, yes, you can add this function to the plugin

**Comment by OmegaWeaponDev** [comment]
@Turbotailz 
Wouldn't this kind of already be a thing - To delete all users - Just using Bulkupdate to delete them all.

**Comment by Turbotailz** [comment]
I suppose there is `/lp bulkupdate users delete` but my understanding was `bulkupdate` only deleted the permissions, not the permission holders (i.e. groups, users). I could be wrong, though.

**Comment by SnonSS** [comment]
Well, yes, you just need to delete all users
