### ISSUE TITLE
Command execution [editor] has not completed. Trace:

### ISSUE THREAD

**Issue by Chypik** [LuckPerms/LuckPerms#3314]
### Description

Command execution [editor] has not completed. Trace:

### Reproduction Steps

through the console using the /lp editor command

### Expected Behaviour

+

### Server Details

 git-Paper-188 (MC: 1.18.1)

### LuckPerms Version

LuckPerms v5.4.2

### Logs and Configs

https://gist.github.com/Chypik/ae597a11ff86cd73a0347b47899511a8

**Comment by Chypik** [comment]
https://gist.github.com/ae597a11ff86cd73a0347b47899511a8.git

**Comment by lucko** [comment]
It's getting stuck doing a DNS lookup, check your servers internet connection + connection settings.
