### ISSUE TITLE
cmd /lp editor

### ISSUE THREAD

**Issue by mani1232** [LuckPerms/LuckPerms#3322]
### Description

If use cmd /lp editor
Nothing happens
Only errors in console
[message.txt](https://github.com/LuckPerms/LuckPerms/files/8102976/message.txt)

### Reproduction Steps

use /lp editor

### Expected Behaviour

Website 

### Server Details

Patina latest

### LuckPerms Version

v5.4.4

### Logs and Configs

[message.txt](https://github.com/LuckPerms/LuckPerms/files/8102982/message.txt)

**Comment by underscore11code** [comment]
The system failed to start one of the threads LP made. This is almost for sure an OS or hardware issue. If you're using a hosting company, talk to them.

**Comment by mani1232** [comment]
> The system failed to start one of the threads LP made. This is almost for sure an OS or hardware issue. If you're using a hosting company, talk to them.


it didn't happen before, I use my dedicated server with pterodactyl panel

**Comment by mani1232** [comment]
[message (2).txt](https://github.com/LuckPerms/LuckPerms/files/8103297/message.2.txt)
Upd errors

**Comment by underscore11code** [comment]
Please at least try to read errors before reporting them. That one clearly says "OutOfMemoryError". You've ran out of memory, which is most certainly not LP's end.

**Comment by underscore11code** [comment]
Please at least try to read errors before reporting them. That one clearly says "OutOfMemoryError". You've ran out of memory, which is most certainly not LP's end.
