### ISSUE TITLE
MongoDB not connecting

### ISSUE THREAD

**Issue by Rivangek** [LuckPerms/LuckPerms#3323]
### Description

Well, basically I'm trying to connect to my mongodb database and the console just throws an error.

![imagen](https://user-images.githubusercontent.com/97276103/154866376-b887fbd0-5ee7-4a3e-be97-626e37cab65d.png)

### Reproduction Steps

Just put your mongodb URI in the config.yml
![imagen](https://user-images.githubusercontent.com/97276103/154866327-92c8e47a-0cae-4673-b0d3-fcdd625cc4b7.png)

### Expected Behaviour

Connecting to database without errors?

### Server Details

Waterfall (Latest)

### LuckPerms Version

v5.4.4

**Comment by lucko** [comment]
4bdcca6566bf522a09e5d123e89ed745a518ebc9

**Comment by Rivangek** [comment]
Now I can't connect to the server. 😔
![imagen](https://user-images.githubusercontent.com/97276103/154869125-8bf6b67d-03ed-4ff2-9701-1c2c2d7bef19.png)
