### ISSUE TITLE
LuckPerms not working on BungeeCord(with MongoDB)

### ISSUE THREAD

**Issue by Rivangek** [LuckPerms/LuckPerms#3324]
### Description

Well, sorry for making another post but this I need to report this(and ensure that will not dissapear as result of a flood of messages), the LP-bungee not working.

Here's an screenshot of the error:
![imagen](https://user-images.githubusercontent.com/97276103/154871009-906adc6f-eb71-46ed-8f72-5b39fcd55f1b.png)

### Reproduction Steps

Using MongoDB and BungeeCord. The database works as expected on Spigot/Paper servers but not in Bungee ones.

### Expected Behaviour

Sync the permissions in every server even Proxy(bungee)

### Server Details

Waterfall Latest

### LuckPerms Version

v5.4.5

**Comment by Rivangek** [comment]
bump....

**Comment by rafaelsms** [comment]
Updated LuckPerms today and it broke for me too. Tested with default configuration, just changing to MongoDB and it happens too.

**Comment by lucko** [comment]
Please can you paste (use gist or https://pastes.dev) a full log file, in particular any errors when LP starts/enables or when players connect

**Comment by rafaelsms** [comment]
Here you go: https://pastes.dev/wBb8uTyxDg

**Comment by lucko** [comment]
Please can you try using v5.4.6 and let me know if that fixes it: https://luckperms.net/download :)

**Comment by rafaelsms** [comment]
It is fixed! Thank you, lucko, for your rapid response and awesome plugin! ❤️
