### ISSUE TITLE
why i dont can use prefix in bungee luckperms i need help for that  if you can give me bungee prefix plugin the

### ISSUE THREAD

**Issue by Sa7mB** [LuckPerms/LuckPerms#3328]
### Description

why i dont can use prefix in bungee luckperms i need help for that

if you can give me bungee prefix plugin the

### Reproduction Steps

why i dont can use prefix in bungee luckperms i need help for that

### Expected Behaviour

why i dont can use prefix in bungee luckperms i need help for that

if you can give me bungee prefix plugin the

### Server Details

Bungee Last Update sub servers paper 1.17.1 last update

### LuckPerms Version

v5.4.5

**Comment by ZeromaniacMc** [comment]
First of all, there is no reason to repeat yourself over and over. I suggest that you visit the discord of luckperms for support next time. To answer your question: The bungee version of luckperms `only handles bungee permissions`, but it does not actually act on anything on the backend servers. Also, the bungee version of luckperms `will not sync your network` if you thought so. 

I suggest you install luckperms bukkit on your backend server, make sure you have **a chat plugin** of your choice as well as **vault plugin** and é voila - prefixes you set in lp on your `backend server` will show up in chat. 
Keep in mind that luckperms will not by itself add prefixes to your chat or tablist or anywhere else. For chat you need a chat plugin, for tablist a tablist plugin and so on.
