### ISSUE TITLE
Smaller export file size

### ISSUE THREAD

**Issue by maxcom1** [LuckPerms/LuckPerms#3329]
### Description

Hi, I come with a suggestion to simply reduce the size of the export file (/lp export).
Luckperms currently saves these files in json format with lots of spaces - in my case, manual removal of spaces reduced the file by 42%, which is quite a difference.

![image](https://user-images.githubusercontent.com/46265094/155896564-c28daa74-5a5b-44b8-a846-1e634dffd22e.png)

### Proposed Behaviour

Making such a change/amendment is unlikely to require much work, rather it is a tiny little thing.
This should also not affect backward compatibility in any way, and may have a positive impact on file size/load speed, especially with large servers.

**Comment by lucko** [comment]
Thanks for the suggestion :)
