### ISSUE TITLE
Non Assignable Groups

### ISSUE THREAD

**Issue by Sxtanna** [LuckPerms/LuckPerms#3331]
### Description

Add a way to create/mark certain groups as non-assignable.

There are times where groups exist solely to provide a base inheritance for other groups. ex.

```
donor:
	vip
	vip+
	
staff:
  mod
  admin
```

It would be nice if you were able to mark these groups as non-assignable, so that the commands:
- user parent add
- user parent set
- etc..

fail when this group is passed in.

### Proposed Behaviour

Maybe have a special luckperms node (similar to the way group displaynames work):
`assignable.false` *(or maybe just `assignable` with the value `false`)*

And applicable commands would then check the value of this node when tab completing and when the group is passed as an argument.

**Comment by emilyy-dev** [comment]
This is already possible with [argument based command permissions](https://luckperms.net/wiki/Argument-based-command-permissions), by allowing to set/add all groups but setting to false the permissions to set or add the specific groups you don't want to be assignable.
These work on top of the [base command permissions](https://luckperms.net/wiki/Permissions) with all the mentioned extra checks.

**Comment by lucko** [comment]
^^ The specific part of that page you need is https://luckperms.net/wiki/Argument-based-command-permissions#checks-when-a-player-makes-changes-with-a-set-of-specific-arguments :)
