### ISSUE TITLE
make it possible that we can delete the default group

### ISSUE THREAD

**Issue by Strikerpro21** [LuckPerms/LuckPerms#3332]
### Description

make it possible that you can delete the default group just like in the groupmanger
and make it possible that you have a local storage function for velocity so you dont need to use mysql data base 

### Proposed Behaviour

make it easyer to work with without getting stuck on only default its sucks and essentailsx wil not work with this plugin for some reason because groupmanger works the best for my for now

**Comment by LoganDark** [comment]
Why do you need to delete the default group? You can just leave it empty and make new groups for whatever you need.

**Comment by powercasgamer** [comment]
You can use any of the flat file / text file storage types mentioned [here](https://luckperms.net/wiki/Storage-types), you however will not be able to sync your data to other servers, you can see the wiki for that [here](https://luckperms.net/wiki/Network-Installation#the-bungeecord-version-of-luckperms). There are multiple ways to "rename" the default group, see [here](https://luckperms.net/wiki/Default-Groups)

**Comment by Turbotailz** [comment]
Your problem is not with the default group, but a misconfiguration with Essentials or another plugin on your server, probably. There is no point in allowing the removal of the default group and you have options to rename it if necessary.

If you are having issues with Essentials I would recommend seeking support on their Discord.

**Comment by LoganDark** [comment]
Also remember to remove GroupManager before installing LuckPerms, or LuckPerms won't do anything. https://luckperms.net/wiki/FAQ#why-are-permissions-not-working
