### ISSUE TITLE
Option to disable MongoDB logger

### ISSUE THREAD

**Issue by maxcom1** [LuckPerms/LuckPerms#3334]
### Description

Hi, I come with a suggestion/request to add an option to disable mongodb logs - detailed database connectivity etc.
There are actually a lot of them and they make a nice spam in the console (only part of it is attached on the screen).

![image](https://user-images.githubusercontent.com/46265094/157931874-90c973ae-d77d-4e86-b5b2-8c934aab89cb.png)

### Proposed Behaviour

Possibility to disable these logs in config, or limit them to one line of basic information

**Comment by lucko** [comment]
Logging is configured by the server, not by plugins.

For most Minecraft server implementations (Spigot etc), this means overriding and then configuring the log4j config file.

https://www.spigotmc.org/threads/how-to-use-log4j-for-custom-logging.414564/
