### ISSUE TITLE
[Its possible to do this?

### ISSUE THREAD

**Issue by msmanui** [LuckPerms/LuckPerms#3336]
### Description

There is a bungee plugin (TAB by Neznamy) that checks for the primary groups in order to know which rank it has.
However if a player has VIP in context server=survival, but not context=bungee, it wont detect. 
Is there any way in order of TAB to know which specify context(server) is, in order to apply correctly?

So:
/lp user test parent add vip server=survival (Wont work)
/lp user test parent add vip server=bungee (Will work)

Is there any way with the API to work with server=survival somehow? 

### Proposed Behaviour

.

**Comment by powercasgamer** [comment]
You need to use `server=bungee` and `world=<server name configured in bungeecord>`. See #1668 for more details
