### ISSUE TITLE
not getting chatformatter plugin for nukkit server

### ISSUE THREAD

**Issue by Rubbi12** [LuckPerms/LuckPerms#3338]
### Description

please add chat formatting plugin for nukkit server, I have searched for plugins everywhere but nothing works. And this makes my setprefix not work properly

### Reproduction Steps

![Screenshot_20220316_004220](https://user-images.githubusercontent.com/101683138/158502232-e229270d-2e16-4f41-a9e0-bf39570928d6.jpg)
![Screenshot_20220316_004143](https://user-images.githubusercontent.com/101683138/158502236-0d7c1307-119e-4a69-97b0-8f20125ac23b.jpg)

### Expected Behaviour

can make chatformatter plugin work for nukkit server

### Server Details

git-Nukkit-8a276f8 (MC 1.18.10)

### LuckPerms Version

v5.4.9

### Extra Details

I hope this problem can be solved

**Comment by Rubbi12** [comment]
I hope this problem can be solved

**Comment by powercasgamer** [comment]
Have you looked [here](https://cloudburstmc.org/resources/categories/chat-related.4/?page=1)? This should have chat plugins that work with LuckPerms.
