### ISSUE TITLE
Setup server name through the API and/or environment variable

### ISSUE THREAD

**Issue by schneidermr** [LuckPerms/LuckPerms#3339]
### Description

That would be great if there will be an option to setup the server name using the Luckperms API and/or using an environment variable.

### Proposed Behaviour

Need to create a setServerName function to support dynamic server name changing.
Oh and it would be also very cool if you could implement the possibility to setup the server name via environment variable and not only using runtime variable (it is nearly a must have option if users running the plugin in a Docker container).

**Comment by lucko** [comment]
In your LuckPerms config, set:

```yml
server: load-from-system-property
```

then set the `luckperms.server` system property.

---

You can do this in Java code using: (must be called before LuckPerms loads)
```java
System.setProperty("luckperms.server", "specialserver");
```

or with a server startup argument:
```
java -Dluckperms.server=specialserver -jar server.jar
```

**Comment by SlimeDog** [comment]
Please add commentary to the configuration file, explaining how to configure this feature. Does it replace `server: global` (for example)?
