### ISSUE TITLE
an idea to block grievors

### ISSUE THREAD

**Issue by JeysonSK** [LuckPerms/LuckPerms#3342]
### Description

Good morning ! I just had an idea, here it is: why not add in the luckperms config (ONLY IN THE CONFIG) the fact of disabling all the luckperms commands executed by ingame players? just leave the commands active through the console! would this prevent the grievors from being able to act as they please?

### Proposed Behaviour

...

### Extra Details

...

**Comment by ZeromaniacMc** [comment]
Hi there,
sorry for being late to the party lol.
What you are aiming to do already exists in a different way. As you probably know, nobody will by default have permissions to mess with LuckPerms unless you either:

A: Give a player explicit permission
B: Give a player OP

LuckPerms has a config option to [deny LuckPerms interaction even with OP](https://luckperms.net/wiki/Configuration#commands-allow-op). Additionally, there is also [disabling the entire vanilla OP system](https://luckperms.net/wiki/Configuration#enable-ops).

Of course this is an option to further protect yourself but on the other hand, 'targeting OP's' is not the only way your server can be destroyed. Example: If someone gains access to your server console, this will not help. If someone manages to get your (mysql or other external database) credentials, they can just delete everything there unless you know how to restrict access to it by IP on top of logins. Also, if you use offline-mode without an authenticator, you risk someone logging in using your UUID, which you probably set heavy permissions on, making them have every permission on your user. 

So yes, the idea is good and yes, it already exists but it is not the solution to everything.
~Cheers
