### ISSUE TITLE
impossible to place command block

### ISSUE THREAD

**Issue by Cheesing-Jade** [LuckPerms/LuckPerms#3343]
### Description

When I try to place command blocks, it just doesn't place.
Command blocks are enabled and autoop is enabled

### Reproduction Steps

1. place command block
2. Cry because it's not working

### Expected Behaviour

1. place command block

### Server Details

spigot 1.18.2

### LuckPerms Version

latest

### Logs and Configs

https://pastebin.com/XQYDvj4F config.yml

**Comment by lucko** [comment]
Check with `/lp verbose`.
