### ISSUE TITLE
Support flat adding for bulk editing

### ISSUE THREAD

**Issue by NaspoDev** [LuckPerms/LuckPerms#3344]
### Description

Hello,

I really think you guys should support flat adding with bulkupdate. Not just update. It can be really limiting sometimes.

Thanks!
Naspo

### Proposed Behaviour

An example of adding the group "test" to everyone:

/lp bulkupdate users add permission group.test

**Comment by lucko** [comment]
The way to do this sort of thing is through the default group (it's personal preference, but I prefer that all users directly or indirectly inherit from the default group, no matter what their "rank" is)
