### ISSUE TITLE
User Authenticator - Crash

### ISSUE THREAD

**Issue by duarbala** [LuckPerms/LuckPerms#3346]
### Description

at some point when a player connects the server freezes and remains that way until restarted

### Reproduction Steps

at some point when a player connects to the server

### Expected Behaviour

that the server doesn't freeze when a random player connects

### Server Details

Purpur build #1597

### LuckPerms Version

5.4.13

### Logs and Configs

Log - Complete https://gist.github.com/duarbala/65af9ea7b9ec73f68842b09a91a29656

Other logs with crashs: 
- https://gist.github.com/duarbala/16555059363ab978ca382d151d9275d0
- https://gist.github.com/duarbala/86ac9ad97565649a070332c22c9fadac

### Extra Details

Server uses luckperms in bungee mode and the only one that freezes is the survival server, and from what has been verified the player does not even necessarily need to connect to survival

**Comment by lucko** [comment]
The issue here stems from the EssentialsX context calculator. I've fixed the issue and opened a pull request (see above), but to fix in the meantime, you can disable the calculator in the LP config

**Comment by duarbala** [comment]
I understand, thank you for the attention and for the PR with the correction, you said that provisionally I could disable this calculation in the config, how do I do that?

**Comment by lucko** [comment]
It's merged into EssX now, best to just update :)

But, for future ref:
https://github.com/LuckPerms/LuckPerms/blob/207e4aa9f8c640ad3b17f844d79512f7b8fb2044/bukkit/src/main/resources/config.yml#L555-L560
