### ISSUE TITLE
[Mysql] Luckperms closing messaging service prevent server restart

### ISSUE THREAD

**Issue by hkkongou** [LuckPerms/LuckPerms#3348]
### Description

you can see from this picture, my server cannot close and restart due to luckperms
this stuck have lasted for 5 hours without any updates

I have 6 servers, 3 of them cannot restart due to this luckperms problem yesterday, 5 hours stuck on that place, the luckperms messaging service.

![image](https://user-images.githubusercontent.com/61608872/159603181-7edd15d7-01e9-488d-86f2-2df2c29b4b80.png)

### Reproduction Steps

restart a server

### Expected Behaviour

server will close

### Server Details

paper-1.18.1-215

### LuckPerms Version

LuckPerms-Bukkit-5.4.1

### Logs and Configs

log:
https://mclo.gs/v7MdEsW

Lp config
https://gist.github.com/hkkongou/322bb642bfc7671f7957af120a1dd453

**Comment by lucko** [comment]
Please could you try updating to the latest version and let me know if the problem is fixed: https://luckperms.net/download :)

**Comment by hkkongou** [comment]
sure, i will try to monitor for a few days
