### ISSUE TITLE
 Command execution [editor] has not completed. 

### ISSUE THREAD

**Issue by hkkongou** [LuckPerms/LuckPerms#3349]
### Description

Every time when i use the command /lp editor 
The command takes very long time to response, is not tps problem, and the problem occurs the same when there are 1 player or 80 players in my server.

The console shows the following error 

![image](https://user-images.githubusercontent.com/61608872/159603998-bddc9a53-3106-44be-8b09-ce8f667448d9.png)

### Reproduction Steps

type command /lp editor

### Expected Behaviour

no error occur, and the command response in 1 second

### Server Details

paper-1.18.1-215

### LuckPerms Version

LuckPerms-Bukkit-5.4.13

### Logs and Configs

server log
https://mclo.gs/pm0efnG
Lp config
https://gist.github.com/hkkongou/322bb642bfc7671f7957af120a1dd453

### Extra Details

I am using mysql mode

**Comment by lucko** [comment]
It's probably a sign that your database is too slow.

**Comment by hkkongou** [comment]
> It's probably a sign that your database is too slow.

The database is hosted in my personal pc which only run minecraft server and mysql database.
The computer uses AMD 5950x and SN850 PCIE gen 4 SSD, the spec should be ok.

Is there anyway to check whether the database is too slow?

**Comment by lucko** [comment]
There are lots of different approaches, some quick googling should give you some ideas.

https://www.google.com/search?q=mysql+check+performance+stats

:)
