### ISSUE TITLE
Server contexts not working

### ISSUE THREAD

**Issue by JpegIsMe** [LuckPerms/LuckPerms#3350]
### Description

I am unable to get server contexts to work on our network. We have each server connected by sql and each server has a unique name set in its config however, when we set a context on a permission or a group it doesn't actually give the permissions to the player unless we set it to global.

Here are some screenshots of /lp info for our build and lobby server:

**LOBBY SERVER**
![javaw_hoHPT68zI8](https://user-images.githubusercontent.com/38381978/159817857-d13fe36b-fb63-4f46-ad2a-befa67e0c6b3.png)

**BUILD SERVER**
![javaw_CzTcbxcVsB](https://user-images.githubusercontent.com/38381978/159819137-f31032a0-9b59-4eec-8a17-71958583cd77.png)

And server context:
![image](https://user-images.githubusercontent.com/38381978/159816737-f1061563-f51a-4790-84c7-02bf49c86436.png)
![image](https://user-images.githubusercontent.com/38381978/159817242-8fd81f5f-2b4d-4b93-a247-669538985272.png)

### Reproduction Steps

Give a group/permission a **server=** context via either command or web editor.

### Expected Behaviour

Group/permission will respect the context per server. Switching servers will disallow/allow the context permissions set

### Server Details

git-Purpur-1598 (MC: 1.18.2)

### LuckPerms Version

v5.4.14

**Comment by lucko** [comment]
Looks ok to me.

If you're still having issues, please could you attach your LP config files.
