### ISSUE TITLE
Server shutdown hangs a few minutes and then throws exception

### ISSUE THREAD

**Issue by nhanledev** [LuckPerms/LuckPerms#3353]
### Description

Luckperms hangs when the server trying to shut down. It throws exceptions about its workers.
Looks like something is wrong with redis.

### Reproduction Steps

1. Install LP 5.4.13 - 5.4.14 and Paper 1.18.2 build 267
2. Use Redis as message queue. Look at my config for reproduce the redis config.
3. Doing a few stuff with LP like add and remove permission
4. Shut the server down

### Expected Behaviour

Luckperms close mysql fast and not hanging.

### Server Details

Paper 1.18.2 build 267

### LuckPerms Version

5.3.14

### Logs and Configs

Both log and config are inside this link
https://gist.github.com/nhanledev/ca26d7dc7c60463c0123ad75d3e8708f

### Extra Details

If server start and you do not touch any command to LP, the server shut down gracefully.

**Comment by lucko** [comment]
Can you let me know if that fixes it? :)

**Comment by nhanledev** [comment]
> Can you let me know if that fixes it? :)

Hello lucko this fixes my problem with Redis 👍
