### ISSUE TITLE
Could not load 'plugins/LuckPerms-Bukkit-5.3.47.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by Whynots1337** [LuckPerms/LuckPerms#3356]
### Description

Hello, can anyone help?

https://pastebin.com/6gpyGgus

### Proposed Behaviour

-

**Comment by ZeromaniacMc** [comment]
Hi,
there are a few things I would like to point out here:

1.) Please don't (half) ignore the issue template, the things asked to be filled out are there for a reason.
2.) Please label actual issues as 'issues' and not suggestions. Suggestions are not as important as providing fixes and therefore will most likely be looked at later.
3.) Please also update your LuckPerms, you are way behind by now.

Your error `Unable to create a temporary file` and `/tmp/luckperms-jarinjar6039974849523517053.jar.tmp: Read-only file system` indicate that the user running the server does not have 'write' perms in /tmp/ as far as I can see (read only). 
If you're running the server off a hosting provider, you need to contact their support.
If you're running the server on a VPS/dedi machine/selfhost, you should be able to fix this yourself.

I don't see how this is a suggestion nor anything LuckPerms could do about.
If I am wrong, someone else please correct me. 

~Cheers
