### ISSUE TITLE
I have an unsolvable error

### ISSUE THREAD

**Issue by DimaSergeew** [LuckPerms/LuckPerms#3357]
### Description

Hello, about 10 times a day this error is spammed: [me.lucko.luckperms.lib.hikari.pool.PoolBase] luckperms-hikari - Failed to validate connection me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl@268e52e7 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
I tried lowering maxLifetime, it didn't help, I signed up for the hosting, they said they have a default 8h timeout
What to do how to fix it she constantly kicks all my players!!!

### Reproduction Steps

She herself appears from time to time maybe 5 to 10 times a day

### Expected Behaviour

I expected that the plugin will work normally with the database, other plugins are also connected to the same database and take off everything is fine

### Server Details

Purpur 1.18.2 v1604

### LuckPerms Version

v5.4.15

### Logs and Configs

https://gist.github.com/DimaSergeew/7388717ef8be139e932b35e332021086

### Extra Details

help me

**Comment by lucko** [comment]
https://luckperms.net/wiki/Storage-system-errors is my exhaustive advice on external storage issues. sorry I can't offer any further suggestions.
