### ISSUE TITLE
Luckperms_actions not getting updated

### ISSUE THREAD

**Issue by Superalex0102** [LuckPerms/LuckPerms#3362]
### Description

Hey, I found a quite interesting issue, I have a bungee setup with mysql and somehow the luckperms_actions doesn't get updated for a while now (1 month to be exact), no new data has been inserted (currently I have 670K rows of data), but the other tables are getting updated, any ideas what could be the issue?

### Reproduction Steps

-

### Expected Behaviour

-

### Server Details

Bungee setup

### LuckPerms Version

5.3.57

**Comment by lucko** [comment]
Unsure - any errors in your logs?

Has the storage type changed? are you using split storage? disk space issues?

**Comment by Superalex0102** [comment]
> Unsure - any errors in your logs?
> 
> Has the storage type changed? are you using split storage? disk space issues?

No errors unfortunately.

The storage type is the same (mysql). No I'm not. Plenty of disk space, the other tables are getting updated only the action table is not.
