### ISSUE TITLE
LuckPerms forge mod

### ISSUE THREAD

**Issue by Razernok** [LuckPerms/LuckPerms#3366]
### Description

I would like to see a forge mod for LuckPerms.

### Proposed Behaviour

It should work the same way as the plugins do.

**Comment by LordSamosa** [comment]
Hi there
There's already a PR for this that you can keep an eye on.
[https://github.com/LuckPerms/LuckPerms/pull/3262](https://github.com/LuckPerms/LuckPerms/pull/3262)

**Comment by Turbotailz** [comment]
Closing this in favour of discussion in #3262
