### ISSUE TITLE
1.1.8.2 Update

### ISSUE THREAD

**Issue by HybridUla** [LuckPerms/LuckPerms#3369]
### Description

I updated Spigot to 1.18.2 after not playing Minecraft for a while, I updated to the newest LuckPerms and I am getting this error.

I tried Googling and it says something about bungeecord? The server is on bungeecord network but the server I'm trying to load it in is a regular spigot server. 

### Reproduction Steps

Just dragged and dropped and started the server. 

### Expected Behaviour

No errors. 

### Server Details

Spigot 1.18.2 with LuckPerms and My plugin.

### LuckPerms Version

newest version on the site.

### Logs and Configs

https://gist.github.com/HybridUla/b828c41bd153b14c721d9e4a0f5addbe

**Comment by HybridUla** [comment]
Forgot to mention i deleted the WHOLE LuckPerm folder to see if it would fix it.

**Comment by ZeromaniacMc** [comment]
Hi there,
the errors you are getting are indicating that LuckPerms can't download the dependency libraries it needs to operate. Perhaps you yeeted all data-inlines to your server? It could also be that your server doesn't have internet connection and therefore the download times out. 
[About dependencies](https://luckperms.net/wiki/External-connections#downloading-libraries)
[List of dependencies](https://luckperms.net/wiki/Credits#open-source)
You could either grab them from there or if you have another server that has these files, copy the `/libs/` folder from the working server to the other.
~Cheers
