### ISSUE TITLE
Server gracefully stopped (crash?) when opening lp editor

### ISSUE THREAD

**Issue by MithrandirCraft** [LuckPerms/LuckPerms#3370]
### Description

This happened to me twice today. I executed `lp editor`, it generated a session, and the server stopped, without a crash.

### Reproduction Steps

I would asume you could just execute `lp editor` but reproduction is very inconsistent.

It's certainly easyer for this to happen if you've been heavily editing and applying some permissions before you open the session.

I have a slight suspicion GriefDefender may be envolved in this, since it never happened before I installed the plugin, and I was configuring GD permissions. I completely fail to recognize how it could be involved, other than the fact that it uses LP's database capabilities.

### Expected Behaviour

The server shouldn't stop because you opened a luckperms editor session.

### Server Details

git-Paper-317 (MC: 1.18.2)

### LuckPerms Version

v5.4.21

### Logs and Configs

[2022-05-08-2.log](https://github.com/LuckPerms/LuckPerms/files/8647718/2022-05-08-2.log)

Let me know if you need lp's config.

**Comment by lucko** [comment]
Nothing in the logs to suggest it is being caused by LuckPerms
