### ISSUE TITLE
Add PlaceholderAPI support to meta (prefix/suffix)

### ISSUE THREAD

**Issue by InsideIntel** [LuckPerms/LuckPerms#3372]
### Description

I feel like there should be a way to add placeholders from PlaceholderAPI into the prefixes of the groups.
I just want to be able to do this so it's easy for me and I've seen some people ask for this before, hopefully this gains support and I hope you have a good day!

### Proposed Behaviour

Like if I were to do /lp group farmer meta setprefix 1 "%oraxen_farmer_tag%", it would use the placeholder and it would return something like this:
![image](https://user-images.githubusercontent.com/50695683/168014278-1a5cbb77-c0bb-45f6-afab-f890dc7284e4.png)

Note: This uses a texture pack that allows me to edit characters (Oraxen specifically).

Also, if I were to add something like %server_tps% that would return the 1, 5, and 15 tps times like it should if PlaceholderAPI was supported in prefix, anything really.

**Comment by emilyy-dev** [comment]
Placeholder support *inside* the prefix/suffix must be handled by the plugin fetching them (tab/chat/scoreboard etc plugins), LuckPerms performs no stylistic rendering on them, it will provide the prefix/suffix "as-is" exactly as stored, the same ideas outlined in [here for style format](https://luckperms.net/wiki/Prefixes,-Suffixes-&-Meta#displaying-prefixes-and-suffixes) also apply for placeholder resolution or any other kind of resolving.
