### ISSUE TITLE
Field `primarygroup` in `luckperms_players` table is always "default"

### ISSUE THREAD

**Issue by Sliman4** [LuckPerms/LuckPerms#3375]
### Description

It looks like `user.getPrimaryGroup().getStoredValue()` in https://github.com/LuckPerms/LuckPerms/blob/207e4aa9f8c640ad3b17f844d79512f7b8fb2044/common/src/main/java/me/lucko/luckperms/common/storage/implementation/sql/SqlStorage.java#L389 is not updated before saving, it's always "default".

### Reproduction Steps

1. Clean install LuckPerms with MySQL or MariaDB storage.
2. /lp creategroup testgroup
3. /lp user <username> parent add testgroup
4. /lp user <username> info: shows primary group "testgroup"
5. See the value in `luckperms_players` table is still default, even after rejoin, /lp sync, and even server restart.

### Expected Behaviour

Set primarygroup to "testgroup"

### Server Details

3096-Spigot-9fb885e--296df56 (MC: 1.16.5)

### LuckPerms Version

e6cc817, also tested v5.3.x

### Logs and Configs

Config is default, only changed storage-method to MariaDB and database credentials. No warnings in logs.

**Comment by underscore11code** [comment]
I believe this is intended behavior. With the default config, the primary group is calculated at runtime by weight, thus no point in saving it. You can change the primary group calculation [here](https://github.com/LuckPerms/LuckPerms/blob/e6cc817436e37d1128b6ba3c662048626cfb7627/bukkit/src/main/resources/config.yml#L302-L313) if you want. 

(While I'm here, be aware that modifying/reading the raw SQL data isn't really supported. While it will work, don't be surprised if there's unannounced breaking changes, and if you break something, you're pretty much on your own)

**Comment by Sliman4** [comment]
Thanks for the response, I was trying to read the primary group and display it on a website, but looks like I'll have to write a separate plugin for this.
