### ISSUE TITLE
Luckperms.* doesn't seem to work properly

### ISSUE THREAD

**Issue by Poldup** [LuckPerms/LuckPerms#3378]
### Description

I am setting up a paper server with luckperms and I'm having some difficulties.
I set up two tracks : users and staff, the first one containing default, players, builder and the second moderators and admins.
every group in each track inherits from the previous one, but not between the two tracks since the players in "staff" track still belong to a "user" track group.

I managed to set permissions up for other plugins without too much difficulties (multiverse, essentials...) but I struggle with LP's own conditionnal permissions. I wanted to have every group in user track all permisssions for the plugins set to false, moderator to be able to promote/demote players on the "users" track but not on the "staff" one and admins to have all permissions. 

My first idea was to set luckperms.* to false for my default group, to true for admins, and to follow the guide at https://luckperms.net/wiki/Argument-based-command-permissions#checks-when-a-player-makes-changes-in-a-specific-context for moderators.
But it didn't seems to work because whatever permission I gave to mods, they still ended up forbidden to use any command because of the luckperms.* = false in the default group.
I find a way around this by setting every luckperms permission to false in the default group, one by one, rather than using luckperms.*

It worked for moderator but now the luckperms.* doesn't work for granting full access to admins, and I don't feel like typing each and every one again.

I precise that i set up group weights, from light to heavy, default being the lighter and admin the heavyer.

### Reproduction Steps

![firefox_k4JEemUNLX](https://user-images.githubusercontent.com/75420849/169849047-dac5840a-fb92-4e12-8a33-a50186e94478.png)
![firefox_LsgFT2zYFQ](https://user-images.githubusercontent.com/75420849/169849055-16932285-d1c2-4d5b-afd7-e4896d9532ca.png)
![firefox_y3grCtsMbS](https://user-images.githubusercontent.com/75420849/169849067-3ef87f07-d8b3-4170-af42-c3f41aa1ad4e.png)

### Expected Behaviour

Admins should have all permissions, moderators be able to promote and demote on the "users" track, other groups should have no permission at all.

### Server Details

git-Paper-283 (MC: 1.18.2)

### LuckPerms Version

v5.4.9

**Comment by emilyy-dev** [comment]
Firstly, by default no player has access to LuckPerms entirely (unless they're opped on Bukkit/Spigot/Paper etc) so there is no need to set LP perms to false on default.

Secondly, specific permissions have priority over wildcard permissions (as mentioned [here](https://luckperms.net/wiki/Advanced-Setup#permission-calculation)), even if inherited, so your "base" group having all those permissions set to false, those will have priority over the `luckperms.*` in admin group, as they are specific permissions (though again, no-one has perms to use LP unless explicitly given).

And lastly just ensure you actually set the `argument-based-command-permissions` setting in the config file to true to make use of the extra permission checks (make sure to restart the server or run `/lp reloadconfig`)
