### ISSUE TITLE
[Fabric 0.14.6][MC 1.18.2] YAML Storage not working again 

### ISSUE THREAD

**Issue by Terminal-Access** [LuckPerms/LuckPerms#3381]
### Description

Looks like server is not using the downloaded snakeyaml library from the libs folder.

### Reproduction Steps

Install Fabric server
Install LuckPerms
Change storage-method config option to yaml or yaml-combined
Start server

### Expected Behaviour

LuckPerms starts without error and all command works

### Server Details

Minecraft 1.18.2
FabricLoader 0.14.6
fabric-api-0.53.4+1.18.2

### LuckPerms Version

v5.4.25

### Logs and Configs

Crash Report - https://pastebin.com/9D0VNLYw
Server Log - https://pastebin.com/F0EU1C03

### Extra Details

Technically this is a dupe of Issue 3325 - however the fix given there dosent work, new versions of the server mod and fabric hence a new issue report.

The following are both present inside the "/mods/luckperms/libs" folder
snakeyaml-1.28.jar
snakeyaml-1.28-remapped.jar

### Additional Note:
This is also affecting the Forge build - exactly the same error. (again both the jars listed above are present in the libs folder)
MinecraftForge v40.1.25

**Comment by ZeromaniacMc** [comment]
Interestingly, I can confirm this. Tested it for the living hell of it with:
- Minecraft 1.18.1
- Fabric Loader 0.13.3
- Fabric API 0-64.6+1.18
- LuckPerms Fabric Version 5.4.22
- Libs in question are also present here
Log: https://bytebin.lucko.me/1YzPai4nLp

**Comment by LeotomasMC** [comment]
why *not* switch? you can easily export, switch storage methods, and then import again, even if you have multiple servers

**Comment by purejosh** [comment]
I suppose I should.

**Comment by Terminal-Access** [comment]
> why _not_ switch? you can easily export, switch storage methods, and then import again, even if you have multiple servers

Playing devil's advocaate here, YAML is a feature of LP thus we should not HAVE to switch, we should be able to use YAML as it was origionaly intended, additionally, there are those of us, myself included, that just simply find it easyer working with YAML rather than having to load up a DB manipulation tool or the web-interface everytime we wish to make changes or slightly tweak our permission setups.

</devils advocate>

Additional thoughts: (not a rant but a polite observation)

This has been an issue for now for quite some time now spanning back a few versions of fabric and at least two versions of MC, and with fabric it'sd self now becomming more and more popular im very surprised at the lack of any form of responce from the team, now I know the main dev teams focus is not on fabric, but it would be nice to get even the slightest update on what's happening even if it's yes we are aware and it's being investigated but it will take some time. but soe the past 4 month's since i initially reported this back for MC 1.18 and the intial sub report confirming the issue there's been nothing said.

This all being said i do apreciate you guys are buisy with RL and the main spigot/forge e.t.c versions of the plugin/mod, andf i Do generally apreciate all the hard work that's gone in to the plugin/mod versions that you currently offer, Right now im happpily using the spigot plugin version and loving it, and jkust about to devl in to a rather complicated sub set of poermission stetups if i can pull iof what i have in mind. so for all of that work you guys are doing an amazing job and a huger thank you for your worek thus far!.

zero hate, love and apreciation as always <3

**Comment by purejosh** [comment]
Sincerely appreciate the fix. Thank you very much.

**Comment by Terminal-Access** [comment]
Awesome work guys, thank so much, lots of love and appreciatre, just tested and just wanted to add confirmation from my end that it's fully working on the very latest fabric server. <3
