### ISSUE TITLE
Permission assignments not working for my builder and moderator ranks

### ISSUE THREAD

**Issue by NRGKevo** [LuckPerms/LuckPerms#3382]
### Description

Whenever I set permissions to "true" using Luckperms, the rank ingame does still not have permission to do anything. Only when I give them /op it seems to work, and I ran out of ideas to try to be honest. So I really hope you can help me out!

### Reproduction Steps

Install Luckperms, install worldedit, assign perms to a certain rank, give yourself that rank ingame and /deop yourself ofc, and see that it doesn't work. If it does work, it has to have something to do with another plugin that's installed on my server, and I would like you guys to help me figure out what it is

### Expected Behaviour

Well I ofcourse expected to happen that it just worked whenever I assigned the right perms to the ranks... But even with worldedit.* nothing works :(

### Server Details

paper 1.18.2

### LuckPerms Version

LuckPerms-Bukkit-5.4.10.jar

**Comment by underscore11code** [comment]
This seems like you're running another permissions plugin if *no* permissions from LP are taking effect. Ensure you're not, or send the output of `/pl` if you're not sure.

*For faster responses, feel free to [join our Discord](https://discord.gg/luckperms).*

**Comment by kalleswe** [comment]
It seems like a certain permissions go thru all the perms from the default. But it more looks like that wildcard permissions doesn't work properly for some reason.
