### ISSUE TITLE
[LuckPerms] Command execution [editor] has not completed.

### ISSUE THREAD

**Issue by Koteika7777** [LuckPerms/LuckPerms#3383]
### Description

[00:18:18 INFO]: shxpe issued server command: /lp info
[00:18:20 INFO]: shxpe issued server command: /lp editor
[00:18:26 INFO]: shxpe issued server command: /lp
[00:18:30 WARN]: [LuckPerms] Command execution [editor] has not completed. Trace: 
  java.base@17.0.2/jdk.internal.misc.Unsafe.park(Native Method)
  java.base@17.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
  java.base@17.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
  java.base@17.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1027)
  java.base@17.0.2/java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:738)
  com.earth2me.essentials.storage.AsyncStorageObjectHolder.acquireReadLock(AsyncStorageObjectHolder.java:35)
  com.earth2me.essentials.Jails.getList(Jails.java:103)
  com.earth2me.essentials.perm.PermissionsHandler.lambda$initContexts$10(PermissionsHandler.java:202)
  com.earth2me.essentials.perm.PermissionsHandler$$Lambda$20936/0x0000000807e69800.get(Unknown Source)
  com.earth2me.essentials.perm.impl.LuckPermsHandler$1.estimatePotentialContexts(LuckPermsHandler.java:32)
  me.lucko.luckperms.common.context.manager.ContextManager.getPotentialContexts(ContextManager.java:182)
  me.lucko.luckperms.common.webeditor.WebEditorRequest.generate(WebEditorRequest.java:135)
  me.lucko.luckperms.common.webeditor.WebEditorSession.createAndOpen(WebEditorSession.java:60)
  me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:111)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:56)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:48)
  me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:265)
  me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:169)
  me.lucko.luckperms.common.command.CommandManager$$Lambda$21485/0x00000008080abcb8.run(Unknown Source)
  java.base@17.0.2/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
  java.base@17.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  java.base@17.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  java.base@17.0.2/java.lang.Thread.run(Thread.java:833)
[00:18:36 WARN]: [LuckPerms] Command execution [] has not completed - is another command execution blocking it?

### Reproduction Steps

/lp editor

### Expected Behaviour

editor

### Server Details

git-Spigot-79a30d7-f4830a1 (MC: 1.12.2)

### LuckPerms Version

v5.4.25

### Logs and Configs

https://gist.github.com/Koteika7777/a3a6a826938978cec79300b5f5bca023

**Comment by NullTxt** [comment]
Can you also please upload your config?

**Comment by Koteika7777** [comment]
> Can you also please upload your config?

https://gist.github.com/Koteika7777/1bd54acecb80ba69621bbacb35d1cc26

**Comment by NullTxt** [comment]
What java version are you using?

**Comment by underscore11code** [comment]
Looking at the stack trace, it appears EssentialsX was being slow to respond about the potential contexts. This actually is an issue with EssentialsX, not LuckPerms as far as I can tell.

**Comment by Koteika7777** [comment]
already fixed
