### ISSUE TITLE
I turned the server off and then on again and luckperms reset itself

### ISSUE THREAD

**Issue by mrpunky** [LuckPerms/LuckPerms#3384]
### Description

I turned the server off and then on again and luckperms reset itself

### Reproduction Steps

I shut down the server and restarted it luckperms reset all player permissions and information

### Expected Behaviour

I want it to be old

### Server Details

1.18.2

### LuckPerms Version

5.4.9

### Logs and Configs

config.yml https://paste.gg/p/anonymous/688c5b2ed27a444888081bbf074c090a

last running logs: https://paste.gg/p/anonymous/a444f3b5503344c7954b10a729b39cca

latest.yml https://paste.gg/p/anonymous/95bd53537e954219adbe466953312707

**Comment by NullTxt** [comment]
Your import failed which may have caused some problems
