### ISSUE TITLE
Adding player to group temporarily bug

### ISSUE THREAD

**Issue by Teraofficiql** [LuckPerms/LuckPerms#3385]
### Description

When I add a player to a group like this: /lp user <username> parent set blabla
it works fine both in chat and tab.

but when I add it temporarily, it does not show correctly in any chat plugin, it shows the prefix of the old group.  Command: 
/lp user <username> parent addtemp blabla <time>

### Reproduction Steps

The chat plugin I use: ChatManager

Plugins that I use and think may affect the chat: Essentials

I am using the latest version of both plugins. I faced the same issue with luckpermschat and essentials chat plugins

### Expected Behaviour

When I add the player to that group for a period of time, the prefix of the group I created in the chat should appear, but the old prefix continues to appear. 
 
<I'm sorry for my bad english>

### Server Details

git-Pufferfish-67 MC : 1.18.2

### LuckPerms Version

v5.4.21

**Comment by ZeromaniacMc** [comment]
Hi there,
as I see you mentioned that the same thing happens with other chat plugins, that speaks for incorrect prefix weights. Remember that it's not the group weights that decide which prefix the player gets from LuckPerms. 

Prefix weights can be viewed in the editor the easiest. If you open it and in the top right search bar put in 'prefix.' you will get a filtered page of all prefixes. The middle number part of 'prefix.**NUMBER**.ThePrefix' is what determines the weight. 
Having that said, the indefinite group of the user in question here most likely has a prefix of which the prefix weight is greater than the prefix weight of the group you added temporarily.
Prefix and suffix weights are explained [here](https://luckperms.net/wiki/Prefixes,-Suffixes-&-Meta#how-does-prefixsuffix-weight-work).

Furthermore, please do not trust what any chat or tablist plugin shows you. Other plugins can add their very own overrides. Please always only trust `/lp user <username> info` - this command will show you which prefix a user gets while staying unfazed by the funky stuff other plugins may or may not do.
If you need further assistance with this, consider visiting the [Discord](https://discord.gg/luckperms). Response times are usually better there than here. 
~Cheers
