### ISSUE TITLE
Bug with /lp log notify <on/off>

### ISSUE THREAD

**Issue by NoltoxGit** [LuckPerms/LuckPerms#3387]
### Description

Hello, 
I found a bug with the command /lp log notify.

- When I run the command, there is an error with the database.

### Reproduction Steps

1. Have the last version of Purpur 1.18.2,
2. Have the last version of LuckPerms,
3. Have the MariaDB database,
4. LuckPerms run to MariaDB,
5. Run `/lp log notify on` or `off`,
6. Check console for errors.

### Expected Behaviour

I was expecting to have the logs enabled or disabled when I make a change with lp.

### Server Details

git-Purpur-1631 (MC: 1.18.2)

### LuckPerms Version

v5.4.25

### Logs and Configs

https://gist.github.com/NoltoxGit/e1772cfbebe0a7b3281bc841519a6cd3

### Extra Details

My database is connected in lpb (bungeecord) database, and use MariaDB V10.6.5.

**Comment by Dovahkiin-Warrior** [comment]
Before someone says your server setup is incorrect, I must address your logs pointing out the issue:

` Caused by: java.sql.SQLException: Table 'XXXX.luckperms_actions' doesn't exist`

The SQL table for luckperms_actions is missing. This could either be because luckperms didn't create it, or you switched to mysql. You can manually create luckperms_actions. However, XXXX.luckpermas_actions suggests your database name is XXXX. So check that database with phpMyAdmin or Adminer to verify that table exists in that database.

**Comment by NoltoxGit** [comment]
> Before someone says your server setup is incorrect, I must address your logs pointing out the issue:
> 
> ` Caused by: java.sql.SQLException: Table 'XXXX.luckperms_actions' doesn't exist`
> 
> The SQL table for luckperms_actions is missing. This could either be because luckperms didn't create it, or you switched to mysql. You can manually create luckperms_actions. However, XXXX.luckperms_actions suggests your database name is XXXX. So check that database name is correct and if so, use phpMyAdmin or Adminer to verify that table exists in that database.
> 
> Edit: I don't use luckperms with mysql as I only have one server running it. I do know my mysql though. If you need further help feel free to mention me in a reply.

Hellow @Dovahkiin-Warrior!
Indeed this table doesn't exist, and yet I've been working on a database for LuckPerms for a few months now and I never noticed this before...

And I don't know how to create the table because I don't know the number of columns required for this table :/

![image](https://user-images.githubusercontent.com/75265787/173231055-229ba45b-5d8e-4d25-a161-16d18145a7a7.png)

**Comment by ZeromaniacMc** [comment]
Hey there. To answer your question I quickly dug up the code of LuckPerms (current master) and looked for mysql/mariadb (same settings) table creations. [Here](https://github.com/LuckPerms/LuckPerms/blob/master/common/src/main/resources/me/lucko/luckperms/schema/mysql.sql#L42-L50) you can see the VARCHAR and data type values it's being made with. So you can recreate it with this or you can try to pull a backup export of you LuckPerms Data, wipe the DB, let it recreate all the tables, and then dump your setup back onto it.

**Comment by NoltoxGit** [comment]
Thanks for the help @ZeromaniacMc!

Everything is working normally again!

Have a nice day 😉
~ Noltox ~
