### ISSUE TITLE
Luckperms not working with EconomyShopGui

### ISSUE THREAD

**Issue by Spiceinajar** [LuckPerms/LuckPerms#3389]
### Description

So I'm running an Aternos server with the EconomyShopGui plugin, and it doesn't work for non op players. I was told to install luckperms and add ESG permissions to the default group. I did this and applied the edits, restarted my server and nothing changed. Not sure if this is the issue of LP or ESG. Please help. Also, the server runs on 1.18.2

Edit: I noticed that none of the permission nodes including the permission nodes outside of ESG don't apply either. So clearly the issue is with LuckPerms and not ESG. Still not sure what to do here.

### Reproduction Steps

Install ESG
Install LP and add all basic ESG permissions to the default group
Reload luckperms and restart server

Nothing happens or changes and non-op players still cannot use the plugin.

### Expected Behaviour

Non-op players can use the plugin normally.

### Server Details

Paper/Bukkit

### LuckPerms Version

v5.4.25

**Comment by LeotomasMC** [comment]
you likely gave the wrong permission nodes. if the plugin looks for 'esg.something' and you put in 'economyshopgui.something' it wont work. if your not sure what the exact permissions you need to give are, its likely documented somewhere on the plugins wiki or download page or something, and if its not, you can try using the [verbose command](https://luckperms.net/wiki/Verbose)
also worth nothing that you do not need to restart the server to apply changes to permissions

**Comment by Spiceinajar** [comment]
@LeotomasMC Well I just used ESG as an abbreviation in the description. there are no permission nodes that start with 'esg'.

**Comment by LeotomasMC** [comment]
well that was just an example. it could even be a small difference like "EconomyShopGUI", "EconomyShopGui", and "economyshopgui" all being different

**Comment by Spiceinajar** [comment]
Yeah... I'll try that. Thanks!

**Comment by lucko** [comment]
Check with the verbose command if this is still an issue
