### ISSUE TITLE
Add the last version of luckperms for Forge to  CurseForge

### ISSUE THREAD

**Issue by YoYomec** [LuckPerms/LuckPerms#3391]
### Description

Hi, I would like to know if it is possible to make the latest version for forge 1.18.2 available on  CurseForge, because some online minecraft server hosters, like Aternos only accept mods from specific sites, like curseforge

### Proposed Behaviour

Just put the forge 1.18.2 version on CurseForge

**Comment by lucko** [comment]
Sure
