### ISSUE TITLE
Mysql timeout

### ISSUE THREAD

**Issue by artur9010** [LuckPerms/LuckPerms#3392]
### Description

Hey, i'm getting timeouts on luckperms mysql connections after update from 1.16 to 1.18. Latest lp, other plugins connects fine.
Server running on 1.16 with that same config and luckperms version connects fine.

Last packet sent to mysql from minecraft container:
![image](https://user-images.githubusercontent.com/4835677/172487088-33345a34-74b8-402a-9279-b72b6fd28db9.png)
![image](https://user-images.githubusercontent.com/4835677/172487101-3845375a-2ed6-4296-8252-fe6d3b929e87.png)

mysql 8.0.23 running inside k8s/docker
mysql client from minecraft container connects fine to mysql database in another container

All mysql settings, firewall, privileges, password etc are correct.

### Reproduction Steps

I do not know how to reproduce, it just happens :/

### Expected Behaviour

Do not timeout

### Server Details

git-Paper-357 (MC: 1.18.2)

### LuckPerms Version

LuckPerms v5.4.26

### Logs and Configs

https://gist.github.com/artur9010/7b3b2a9b852a815b2d986e647e862705

**Comment by artur9010** [comment]
Welp, looks like luckperms can't connect in 5s after update. Increased timeout from 5 to 10s and now works fine, weird.

**Comment by kamcio96** [comment]
same for me. Is it possible to fix? 
Tbh start time is important :/

**Comment by artur9010** [comment]
![image](https://user-images.githubusercontent.com/4835677/173203698-14655935-b981-495d-94fa-6323fc45637d.png)
 As you can see, there is a gap on network between last luckperms mysql query (response is instant), after it it doing something and trying to connect to redis after 4 seconds. It resolves redis dns instantly, connects and subscribes.
After that it still doing something for few more seconds and runs mysql queries like

```
SELECT name FROM `luckperms_groups`
```

also those requests are instant.

**Comment by lucko** [comment]
You can configure the connection timeout in the LP config.yml -- `data.pool-settings.connection-timeout`
