### ISSUE TITLE
no me deja poner prefix

### ISSUE THREAD

**Issue by ElPerritoXD** [LuckPerms/LuckPerms#3402]
### Description

hola, no me deja añadir prefix en los grupos pongo el comando /lp group Owner  meta setprefix 100 &4&lOwner&f o el /lp group Owner  meta setprefix &4&lOwner&f y no me deja

ayuda

### Reproduction Steps

s

### Expected Behaviour

s

### Server Details

s

### LuckPerms Version

s

### Logs and Configs

ss

### Extra Details

s

**Comment by romerdev** [comment]
LuckPerms only acts as the source for prefixes / suffixes, it doesn't actually apply them. You need an appropriately configured chat/tablist formatting plugin for them to be displayed. If the values appear correctly when you run `/lp user <user> info`, LuckPerms is doing its job!

**FAQ answer: Prefix isn't showing?**
https://luckperms.net/wiki/FAQ#why-are-prefixessuffixes-not-working

**List of chat/tablist formatting plugins that work with LuckPerms**
https://luckperms.net/wiki/Prefixes,-Suffixes-&-Meta#displaying-prefixes-and-suffixes
