### ISSUE TITLE
Allow Usage of XUID

### ISSUE THREAD

**Issue by Bedlesssgod** [LuckPerms/LuckPerms#3406]
### Description

So, recently im started a BungeeCord Server with geyser and Floodgate to allow Bedrock Edition Players onto my Network, but Luckperms, doesnt seem to be able to save XUIDs, So new players From Bedrock Edition cannot recieve ranks

### Proposed Behaviour

It Would Translate the XUID to UUID, to Allow Bedrock Players to Connect and recieve Ranks!

**Comment by LeotomasMC** [comment]
have you set "allow-invalid-usernames" to true in the LP config?

**Comment by Bedlesssgod** [comment]
Yes, But i get the error 
Client Side 'Kicked whilst connecting to Server X: '
Server Side 'Processing pre-login for xxxxx-xxxx-xxxxx - !GameStarTVyt
Disconnecting com.mojang.authlib.GameProfile@6cf923f5[id=xxxx-xxx-xxxx-xxx, name=!GameStarTVyt], porperties={}, legaxy false] (xx.xxx.xxx.xxx:xxxx):Failed to verify username!'

**Comment by LeotomasMC** [comment]
that has nothing to do with LuckPerms. thats from vanilla because bedrock players cannot authenticate with javas authentication servers. you likely have floodgate/geyser configured incorrectly
