### ISSUE TITLE
User permission data not loading

### ISSUE THREAD

**Issue by alfredcort** [LuckPerms/LuckPerms#3407]
### Description

I recently set up LuckPerms bungee, now when players log-in they receive this error message in chat. I haven't noticed anything breaking at all, it seems like everything is working 100% which is frustrating me as I can't locate the issue.

I've tried removing Geyser/Floodgate & my Bungeeguard/AntiBot on my proxy without any change, the issue still persists.

error message on login:
https://imgur.com/a/9P5saHu

Console error on the proxy:
https://www.toptal.com/developers/hastebin/zuzixacepo.sql

### Reproduction Steps

Setup LuckPerms on my Bungee network correctly, I have no issues anywhere apart from this annoying message. Everyone, including lp staff, in the Discord support chat are clueless.

### Expected Behaviour

I didn't expect to get this error message

### Server Details

Purpur 1.19 #1679

### LuckPerms Version

v.5.4.30

### Logs and Configs

https://www.toptal.com/developers/hastebin/zuzixacepo.sql

**Comment by FurryMileon** [comment]
have you installed a plugin on proxy or waterfall

**Comment by alfredcort** [comment]
> have you installed a plugin on proxy or waterfall

I've got The bungee LP on my proxy and the standalone LP on my seperate servers

**Comment by alfredcort** [comment]
> have you installed a plugin on proxy or waterfall

here are the plugins installed on my bungee server: https://imgur.com/a/YuZEINr
