### ISSUE TITLE
Errors with world context

### ISSUE THREAD

**Issue by tigra323** [LuckPerms/LuckPerms#3409]
### Description

if you die or teleport from the end (if the context is end), then the permission remains active even if you re-enter the dimension

### Reproduction Steps

1. Add a permission with context world=the_end(or if select another world, only death will "suspend" permission)
2. Go to selected world
3. Death or enter the portal if you in end
4. You still have this permission

### Expected Behaviour

i use styledplayerlist to display in tab which dimension you are in, after dying or teleporting from end through portal i still have the same color without any error in console. If you use execute to teleport from the end, then everything is fine. Then I tried to use the context with luckperms.* and after going from the end through the portal or dying in the end, I can use lp, even without opka or other permissions.

### Server Details

1.19 - fabric-api@0.4.9+e62f51a3a9

### LuckPerms Version

v5.4.30

### Extra Details

if poor literacy, then sorry, I use a translator

**Comment by lucko** [comment]
Sounds like styledplayerlist is not refreshing as opposed to an issue with permissions
