### ISSUE TITLE
Luckperms not working through RCON

### ISSUE THREAD

**Issue by Geoxor** [LuckPerms/LuckPerms#3411]
### Description

Luckperm commands don't work through RCON removing the ability of using scripts to automatically synchronize roles/permissions

![image](https://user-images.githubusercontent.com/34042825/176781206-cd87113a-3dca-4bb9-b7dc-0768e05d1a11.png)

I've seen that this problem apparently had been fixed before on this commit https://github.com/LuckPerms/LuckPerms/blob/04bb035a83af96d55e7dffea514c505c66ce0f54/bukkit/src/main/java/me/lucko/luckperms/bukkit/BukkitSenderFactory.java#L99 
so i'm unsure what causes the problem currently

### Reproduction Steps

Simply try to execute luckperm commands through RCON

### Expected Behaviour

For luckperms commands to execute through it

### Server Details

git-paper-1.19-33

### LuckPerms Version

v5.4.30

**Comment by lucko** [comment]
See https://github.com/LuckPerms/LuckPerms/issues/1365
