### ISSUE TITLE
Connection is not available, request timed out after 5002ms

### ISSUE THREAD

**Issue by iamlexivale** [LuckPerms/LuckPerms#3412]
### Description

Luckperms send a lot of error every 5 or 10 minutes, and sometimes all players get kicked.

### Reproduction Steps

Install Purpur Latest Build
Install Luckperms Latest Build
- Config LuckPerms to MariaDB

Has followed this step : [https://luckperms.net/wiki/Storage-system-errors](https://luckperms.net/wiki/Storage-system-errors) and still had same isseus

### Expected Behaviour

LuckPerms works great and seen like no error or mistake but in console send a lot of error and sometimes all players get kicked every 5 or 10 minutes

### Server Details

git-Purpur-1689 (MC: 1.19)

### LuckPerms Version

v5.4.30

### Logs and Configs

https://gist.github.com/iamlexivale/5b491cbc5e6927d80e2a3ce13e158ff4

**Comment by lucko** [comment]
https://luckperms.net/wiki/Storage-system-errors is the extent of the advice I can offer - sorry
