### ISSUE TITLE
Unable to stop server

### ISSUE THREAD

**Issue by sauramel** [LuckPerms/LuckPerms#3417]
### Description

LuckPerms works as expected however is causing a crash when stopping the server

### Reproduction Steps

Using Medieval Minecraft Fabric v1 1.19 modpack install luckperms, placeholderapi, luckperms hook for placeholderapi
configure some ranks and prefixes in game
stop server
server will crash instead

### Expected Behaviour

Server should stop normally instead of crashing

### Server Details

Fabric 0.14.8 Minecraft 1.19

### LuckPerms Version

Fabric 5.4.30

### Logs and Configs

https://gist.github.com/sauramel/7c4a886ca716662359ab55b5aa7577ad#file-latest-log

**Comment by lucko** [comment]
Safe to ignore the error
