### ISSUE TITLE
the perms wont take effect 

### ISSUE THREAD

**Issue by saudaalseri** [LuckPerms/LuckPerms#3420]
### Description

im playing 1.18.2 and  when i put perms and they wont work and i need help with that

### Reproduction Steps

so i did a group named op and added value false perms which is essentials.keep.inv essentials.keep.pxp and i added a value true perm which is * and still not working 

### Expected Behaviour

i wanted to remove is a op to not  keep.inv and keep.pxp  which the plugin is doing that is essentials and i  made a group op group and  added the value false essentials.keep.inv   essentials.keep.pxp perms  and added * value true and applyed and its still keeps the inv 

### Server Details

spigot 1.18.2

### LuckPerms Version

v5.4.30

### Logs and Configs

sadly i cannot get a log of it

**Comment by saudaalseri** [comment]
> Hi there. Please note that the permissions you gave are incorrect. Please refer to [this](https://essinfo.xeya.me/permissions.html) website for essentials permissions. ![qHykAFz](https://user-images.githubusercontent.com/94971971/178496838-4326ff17-94e6-46cb-bac0-3248f6b5d80c.png)

its the same

**Comment by LeotomasMC** [comment]
can you send a screenshot of `/pl` then?

**Comment by saudaalseri** [comment]
![image](https://user-images.githubusercontent.com/82798415/178587079-cd526d89-19b4-49df-90c5-758df7d6c60e.png)
sure

**Comment by ZeromaniacMc** [comment]
You have powerranks installed, which is a permission plugin just like luckperms. 2 permission managers can't work together. You need to remove one or the other.

**Comment by saudaalseri** [comment]
> You have powerranks installed, which is a permission plugin just like luckperms. 2 permission managers can't work together. You need to remove one or the other.

ok i will tray that

**Comment by saudaalseri** [comment]
it worked ! thanks

**Comment by saudaalseri** [comment]
i problem aswell the prefix not showing up  ?

**Comment by ZeromaniacMc** [comment]
LuckPerms does not perform any chat/tablist formatting of its own.
LuckPerms only acts as the source for prefixes / suffixes, it doesn't actually apply them. You need an appropriately configured chat/tablist formatting plugin for them to be displayed. If the values appear correctly when you run /lp user <user> info, LuckPerms is doing its job.
[Setting a prefix in luckperms](https://luckperms.net/wiki/Meta-Commands#lp-usergroup-usergroup-meta-setprefix-priority-prefix-context)
[Chat/Tablist plugin suggestions](https://luckperms.net/wiki/Prefixes,-Suffixes-&-Meta#displaying-prefixes-and-suffixes)

**Comment by saudaalseri** [comment]
ok thanks i will download that

**Comment by saudaalseri** [comment]
> LuckPerms does not perform any chat/tablist formatting of its own. LuckPerms only acts as the source for prefixes / suffixes, it doesn't actually apply them. You need an appropriately configured chat/tablist formatting plugin for them to be displayed. If the values appear correctly when you run `/lp user <user> info`, LuckPerms is doing its job. [Setting a prefix in luckperms](https://luckperms.net/wiki/Meta-Commands#lp-usergroup-usergroup-meta-setprefix-priority-prefix-context) [Chat/Tablist plugin suggestions](https://luckperms.net/wiki/Prefixes,-Suffixes-&-Meta#displaying-prefixes-and-suffixes)

which one is  the most recommended

**Comment by ZeromaniacMc** [comment]
Really depends on what you want. Essentials chat makes sense if you use essentials anyway. LPC makes sense if you want placeholder api support. Stylizer comes with a tablist also, which might appeal to you. Chat manager for instance is very advanced with chat filters, rules, auto capitalization and punctuation. It really is up to you to pick a plugin that suits your needs.
