### ISSUE TITLE
server startup sql error - failed to init storage implementation

### ISSUE THREAD

**Issue by Cruwzky** [LuckPerms/LuckPerms#3421]
### Description

I see the error in the pastebin at every startup.

But LuckyPerms works fine. Im just getting a mini heart attack each time  I see it.

I have been though the common issues with storage and everything seems to be fine.

### Reproduction Steps

I don't know. I just start the server.

### Expected Behaviour

I would except it to not show an error.

### Server Details

git-Purpur-1708 (MC: 1.19)

### LuckPerms Version

v5.4.30

### Logs and Configs

https://bin.bloom.host/ihusuzulil.sql

### Extra Details

If I do an export of the database and import into a H2 it does not show this error.

**Comment by Aberdeener** [comment]
I'd be surprised if LuckPerms actually works 100% fine after this error.

You should run over [this wiki article](https://luckperms.net/wiki/Storage-system-errors#luckperms-cannot-connect-to-my-mysql-server) to make sure your configuration is 👌🏼

**Comment by Cruwzky** [comment]
I have looked though everything and it should be good. We have now changed database server, so maybe this has helped.

But after that error Luckperms "seems" to work fine, if I query the database I can see that it updates so it has formed a connection. And we also have all the groups, permissions and so on. So I don't know the effect of the error.

It is not everytime we boot that we see it.

**Comment by lucko** [comment]
Either a networking issue or a problem with your database server.
