### ISSUE TITLE
Make it for 1.5.2 bukkit

### ISSUE THREAD

**Issue by CuriousCoder1232** [LuckPerms/LuckPerms#3425]
### Description

you should make it for 1.5.2or is it

### Proposed Behaviour

the same

### Extra Details

EEEEEEe

**Comment by emilyy-dev** [comment]
The minimum supported version is 1.7.10 with the Bukkit Legacy build (see https://luckperms.net/download). Anything lower than that would take more effort to implement that what it's worth for the amount of people running it.
