### ISSUE TITLE
luckperms.autoop does not work

### ISSUE THREAD

**Issue by DanHCraft** [LuckPerms/LuckPerms#3428]
### Description

After I updated my Paper server to 1.19, luckperms.autoop stopped working. All my admins can't use anything now. And I dont want to use `*` and `/op`

### Reproduction Steps

Update an existing and full configurated (Permissions included) 1.18.2 Paper server to 1.19 Paper.

Environment Details:
- OS: Debian 10 (Buster), Linux 5.4.34-2
- Java: OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)

Plugin List:
- BlueBridgeCore-v1.3.1-alpha
- BlueBridgeWG-v1.3.1-alpha
- BlueMap-1.7.3-spigot
- CoreProtect-21.2
- Creative(+NBT)Control-1.13
- FastAsyncWorldEdit-Bukkit-2.4.0
- LuckPerms-Bukkit-5.4.35
- LWCTrust-1.0.6
- LWCX-2.2.9-dev
- Multiverse-Core-4.3.1
- Multiverse-Inventories-4.2.2
- Multiverse-Portals-4.2.1
- mywarp-bukkit-3.1.1-all
- Vault-1.7.3
- VaultChatFormatter
- WGLecternFlags-0.1.3-SNAPSHOT
- worldguard-bukkit-7.0.7-dist

### Expected Behaviour

I expect that the autoop functionality is working as before I updated the server.

### Server Details

git-Paper-70 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: d0e7fa4)

### LuckPerms Version

v5.4.35

### Logs and Configs

[Latest Log, LuckPerms Config & Permissions](https://gist.github.com/DanHCraft/57938ae261a29af64fbdaf382c735830)

**Comment by lucko** [comment]
Can't reproduce
