### ISSUE TITLE
Modrinth releases are outdated compared to other sources

### ISSUE THREAD

**Issue by 3stantedja** [LuckPerms/LuckPerms#3429]
### Description

Currently, the Modrinth releases are several months behind CurseForge's release. This means that for people using tools like packwiz they would be puzzled that LuckPerms doesn't have releases for 1.19, whereas luckperms.net and CurseForge have releases that are at least compatible for 1.19. This made it seemed like the Modrinth page is abandoned, which is weird considering Spark is up to date on all official sources.

### Proposed Behaviour

It would be nice if it's possible to sync up releases at least between CurseForge or luckperms.net with Modrinth.

**Comment by lucko** [comment]
I've updated modrinth with releases for 1.19 - thanks for the nudge :)
