### ISSUE TITLE
ConnectionIsClosedException

### ISSUE THREAD

**Issue by kohlerpop1** [LuckPerms/LuckPerms#3433]
### Description

The connection seems to be closed and I am unsure if it is fetching a new connection or not but this is spamming in our Hubs console and I believe is something that can be fixed easily. I am unsure if this is an issue with the plugin or settings we have configured in our database.

### Reproduction Steps

Start server and connection will eventually send a request after it has expired.

### Expected Behaviour

Should initiate a new connection instead of trying to use the old one.

### Server Details

git-Paper-324 (MC: 1.18.2)

### LuckPerms Version

LuckPerms v5.3.47.

### Logs and Configs

https://paste.gg/p/anonymous/6205316109454b0a9a0d792f317a6164

### Extra Details

Unsure exactly what causes it but I presume it can be easily identified what is the issue!

**Comment by Laurenshup** [comment]
Had this problem as well on a Velocity server. Looks like it happened when there were around 60+ players online. It was really lagging the Velocity a lot.

**Comment by lucko** [comment]
https://luckperms.net/wiki/Storage-system-errors
