### ISSUE TITLE
Standalone app does not shutdown on a fatal exception

### ISSUE THREAD

**Issue by clrxbl** [LuckPerms/LuckPerms#3438]
### Description

An application should always terminate on a fatal exception where it cannot recover (e.g. database connection failures on startup).
The standalone LuckPerms application currently does not do this.

### Reproduction Steps

Start the standalone application with a bad configuration file.

### Expected Behaviour

Shutdown the application on a fatal exception.

### Server Details

N/A

### LuckPerms Version

v5.4.36

**Comment by lucko** [comment]
b1953632c58551ad1450c034ee4a14e7f5eb01f7

Still won't immediately shutdown if, for example, it cannot connect to the database - but if the database does become accessible, then LP will connect and the app should start functioning correctly.
