### ISSUE TITLE
Tab completion broken in new build

### ISSUE THREAD

**Issue by Chris6ix** [LuckPerms/LuckPerms#3449]
### Description

With the new `5.4.39` build, player names, groups and tracks and are no longer tab completed when trying to use a command such as `/lp user <PlayerName> parent set <GroupName>`.

### Reproduction Steps

Try to use a command like `lp user` ?

### Expected Behaviour

Tab completion working

### Server Details

git-Paper-105 (MC: 1.19.1)

### LuckPerms Version

5.4.39

### Logs and Configs

No Errors or warnings in logs.

I have not changed anything in my config, but if it helps you here:
https://gist.github.com/Chris6ix/09f89e4d34f3939c56ce6e2ef33ba8bf

**Comment by lucko** [comment]
Thanks

**Comment by Chris6ix** [comment]
Thank you for fixing this so quickly :)
