### ISSUE TITLE
LP or /luckperms commands only works from console, not from player

### ISSUE THREAD

**Issue by chiel1112** [LuckPerms/LuckPerms#3451]
### Description

When I tried setting up a new server I found out that the /lp editor command only works when used from the console. When using it as a player it is showing the error "An unexpected error occurred trying to execute that command".

### Reproduction Steps

I tried using /lp editor as a player on my spigot 1.19.1 server, but I got this error "An unexpected error occurred trying to execute that command". When using it in console it did work.

### Expected Behaviour

I would expect it to make me a link for the editor like happens in the console

### Server Details

3561-Spigot-2183145-8f36472 (MC: 1.19.1)

### LuckPerms Version

v5.4.36

**Comment by Aberdeener** [comment]
Hi there, this has been fixed in v5.4.37 - however you should get the most recent jar as other fixes have occurred since then as well.
