### ISSUE TITLE
Kicks players on give rank

### ISSUE THREAD

**Issue by StelarMC** [LuckPerms/LuckPerms#3453]
### Description

When I give a rank to anyone, the server kicks a lot of people with this error: Internal Exception: java.io.IOException: Error while read(...): Connection reset by peer (this doesn't always happen, it happens very rarely, but if it happens to me at an important moment it would be really annoying)

### Reproduction Steps

1 - Give a rank to anyone
2 - Console kicks to the server kicks people (almost everyone connected)

### Expected Behaviour

Don't kick anyone

### Server Details

spigot 1.8.8

### LuckPerms Version

v5.4.30

### Logs and Configs

Default

### Extra Details

Nothing

**Comment by YaUhYeah** [comment]
can confirm happening to me also. in 1.17 paper

**Comment by LeotomasMC** [comment]
Do you happen to have TAB installed?

**Comment by StelarMC** [comment]
Yes, I have

**Comment by LeotomasMC** [comment]
update TAB then, there was a bug that has been fixed that caused that

**Comment by StelarMC** [comment]
ohhh, okey. I will update
