### ISSUE TITLE
Can not give bedrock players a rank

### ISSUE THREAD

**Issue by AxoGamer** [LuckPerms/LuckPerms#3455]
### Description

The plugin does not recognise the ''.'' for the username from bedrock players

### Reproduction Steps

Try to give a bedrock player a rank (/lp user <username> parent set <rank name>) on a crossplay server

### Expected Behaviour

Try to give a bedrock player a rank (/lp user <username> parent set <rank name>) on a crossplay server

### Server Details

Paper 1.19

### LuckPerms Version

v5.4.41

**Comment by ZeromaniacMc** [comment]
In the config of LuckPerms there is a setting called `allow-invalid-usernames`. Set that to true. It'll work.
