### ISSUE TITLE
placeholder

### ISSUE THREAD

**Issue by Blskk** [LuckPerms/LuckPerms#3456]
### Description

%luckperms_group_expiry_time_<group name>% 
If it is 5 day, it displays 4d 23h, 59M, 59S  I don't want it!

### Proposed Behaviour

No format, no unit, it doesn't need
If the player has 5 days, please display it as an integer of 5 without any units

I'm sorry. I'm in English level 0
 ------------Google Translate

### Extra Details

false

**Comment by LeotomasMC** [comment]
well 4 days, 23 hours, 59 minutes, and 59 seconds is not 5 days. its 1 second less than 5 days. You personally might not care that its only 1 second less, but not everyone wants this number rounded. There are ways to do what you want without causing other people who rely on the current behavior to begin having issues, such as using another plugin that formats it however you want.

**Comment by Blskk** [comment]
In the most direct way, you can add other placeholders directly



excess

**Comment by LeotomasMC** [comment]
Adding an excess of placeholders for special formatting seems out of scope for LuckPerms. Not to mention solutions for this [already exist](https://github.com/ZeromaniacMc/LuckPerms-Time-Placeholder-Script).

**Comment by Blskk** [comment]
如果是这样的话，谢谢你的回复，不得不说这个插件非常强大。
感谢您免费的提供支持
