### ISSUE TITLE
Serious h2 database corrupt under unusual high load

### ISSUE THREAD

**Issue by skbeh** [LuckPerms/LuckPerms#3458]
### Description

Yesterday a hacker spammed my server by clicking a sign which executes commands for giving players items. During that, the h2 database engine of luckperms crashed. Then the server automaticly restarted but the database can not be opened anymore.
I also noticed that the version of h2 library is very outdated (1.4.199) which is not supported by their team and has known security vulnerabilities. They said in the changelog that 2.x version improved stability when an application crash. Although upgrading it will break a lot and not forward compatible, the security and stability benefits seem worthwhile.

### Reproduction Steps

The problem happends by chance so there may be not a way to  stably reproduce it. Even though, I am trying my best to make it.

### Expected Behaviour

Luckperms plugin can handle whatever high load without database corruption.

### Server Details

https://github.com/Wind-Development/WindSpigot

### LuckPerms Version

v5.4.36

### Logs and Configs

https://gist.github.com/skbeh/38e3235a26f6abc1d508e844b3ff40d8
https://gist.github.com/skbeh/69cc1e30f9ed4843753bb3dc98b24bbf

**Comment by LeotomasMC** [comment]
It looks like your server is in offline mode. Please know that being in offline mode inherently makes your server less secure. I don't see why LuckPerms should be responsible for someone causing your database to break because you run you server in offline mode. I haven't experience a corrupt H2 file before, but it appears your H2 file **might** just be locked because it wasn't unlocked properly from the server crashing, so there is a chance the data is still intact, but I could be wrong about that.

**Comment by skbeh** [comment]
> Please know that being in offline mode inherently makes your server less secure.

Online mode not solves **any** bugs in existing code (There have been reports that this h2 version is easy to be corrupted like https://github.com/h2database/h2database/issues/2730).

> it appears your H2 file might just be locked

There is not any lock files around the he db file. Even the official database recover tool `java -cp h2*.jar org.h2.tools.Recover` which reports `java.nio.BufferUnderflowException` not works.

**Comment by lucko** [comment]
LP v5.4.50 upgrades h2 from `1.4.199` to `2.1.214`.

The migration is automatic on startup:

<img width="1296" alt="Screenshot 2022-10-16 at 14 21 42" src="https://user-images.githubusercontent.com/8352868/196038159-ad4dc40b-6d72-4a8f-ac08-faf9219c4885.png">

And a backup of the old format is retained in the LuckPerms folder:

<img width="734" alt="Screenshot 2022-10-16 at 14 23 29" src="https://user-images.githubusercontent.com/8352868/196038179-601d2884-a140-484f-ab77-c064010092ef.png">

Hopefully this will help with the corruption issues some people are seeing. Unfortunately, not sure what to suggest to fix any existing broken db files. If the recovery tool doesn't work, then you might be s' out of luck :(
