### ISSUE TITLE
Parameter hints when defocusing the tab suggestion box no longer appear without typing a character

### ISSUE THREAD

**Issue by WiIIiam278** [LuckPerms/LuckPerms#3460]
### Description

The "hints" that appear indicating expected command arguments when you press escape to exit the box with tab suggestions no longer appear following the upgrade made to allow Commodore to support 1.19+.

Caused by https://github.com/lucko/commodore/issues/29 - I'm reporting this here in addition to on the commodore tracker for posterity (although LuckPerms itself isn't the source of the issue, I figured it's good to have this here so it can be better tracked with LuckPerms)

### Reproduction Steps

1. Fire up a server with the latest Luckperms running Paper (supporting commodore 2.1+)
2. Type /luckperms user player permission set
3. You will be presented with a list of tab suggestions. Press ESC to exit the window
4. You should see the remaining parameters to enter on the command. Instead, you see an (incorrect) syntax error.

### Expected Behaviour

Expected result, with LuckPerms:
![image](https://user-images.githubusercontent.com/31187453/183450999-e87442fd-3fc0-4c91-bb3e-174e748da18f.png)

Actual result (Commodore 2.2 / Paper 69950d5 / Minecraft 1.19.1):
![image](https://user-images.githubusercontent.com/31187453/183451032-5ab6a107-0f01-4559-be2c-15c735884429.png)

However, parameter hints will appear if you type a character into the field work.
![image](https://user-images.githubusercontent.com/31187453/183451059-b83b3bca-ad61-4eb2-b8aa-d25709cb3eac.png)

This does not mirror Vanilla behavior, where hints are able to display even before typing a character.
![image](https://user-images.githubusercontent.com/31187453/183451107-619046af-1c80-46f3-b211-70e4d0947991.png)

### Server Details

1.19.2

### LuckPerms Version

v5.4.41

### Extra Details

Caused by https://github.com/lucko/commodore/issues/29

**Comment by lucko** [comment]
We can track the issue in the commodore repo, thanks :)
