### ISSUE TITLE
Console Errors

### ISSUE THREAD

**Issue by Insidi0usAngel** [LuckPerms/LuckPerms#3461]
### Description

Downloaded latest version of LP - 5.4.41 and got console errors on server startup
Deleted the new jar and rolled back to v5.4.3 and no errors are now present in console

### Reproduction Steps

As above

### Expected Behaviour

no console errors

### Server Details

This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba) You are running the latest version Previous version: git-Paper-77 (MC: 1.19)

### LuckPerms Version

v5.4.41

### Logs and Configs

https://pastebin.com/sMVG0RAr

### Extra Details

.

**Comment by Insidi0usAngel** [comment]
Edit, on next server reload the error came back, so I think this was a data sync error and not a version issue. On loading a new /lp editor and saving session with applying no changes this error then went away.

**Comment by underscore11code** [comment]
This error is a result of reloading the server. Never `/reload`, plugman reload, etc. See [here](https://madelinemiller.dev/blog/problem-with-reload/) for more info.
