### ISSUE TITLE
Exception in server tick loop - Forge 41.1.0 LuckPerms 5.4.41

### ISSUE THREAD

**Issue by Codename-11** [LuckPerms/LuckPerms#3463]
### Description

I'm attempting to use LuckPerms latest 1.19 Forge build on my server which is running Forge 41.1.0. I tested with LuckPerms 5.4.41 being the only mod installed with a clean server, and upon player login after the server starts, the server crashes. See attached crash report.

### Reproduction Steps

Install Forge Server 41.1.0.
Add LuckPerms 5.4.41 to mods folder.
Start server.
Login to server after server is ready.
See server crash.

### Expected Behaviour

Player able to join server without server crashing.

### Server Details

Forge 41.1.0 MC 1.19

### LuckPerms Version

5.4.41

### Logs and Configs

Crash-Report: [https://pastes.dev/5hVGQjxMkV](https://pastes.dev/5hVGQjxMkV)

### Extra Details

Edit: Tested both LuckPerms 5.4.36 & 5.4.41 with the same result. Updated issue to reflect latest version.

**Comment by zPanic** [comment]
Having this exact issue on Forge 1.19.2 (43.0.8).

**Comment by lucko** [comment]
Fixed by https://github.com/LuckPerms/LuckPerms/pull/3477
