### ISSUE TITLE
Wildcards not working after migrating from YAML to MySQL

### ISSUE THREAD

**Issue by PovilasLT** [LuckPerms/LuckPerms#3465]
### Description

After migrating from YAML to MySQL, several wildcards stopped to work. I'm OP with `*` permission, but Luckperms commands wont work with `*` wildcard, but works with `luckperms.*`. Bukkit commands also won't work with `*` or `*.*` permissions. Cmi /gamemode command won't work even with `cmi.*` permission, it requires every single permission for gamemode command.. Plugman commands only works when applied `plugman.*`

`[19:49:41 INFO]: [LP] povilasc's Permissions:  (page 1 of 1 - 7 entries)`
`[19:49:41 INFO]: > *.*`
`[19:49:41 INFO]: > cmi.*`
`[19:49:41 INFO]: > luckperms.*`
`[19:49:41 INFO]: > plugman.*`
`[19:49:41 INFO]: > *`
`[19:49:41 INFO]: > cmi.command.gm`
`[19:49:41 INFO]: > cmi.command.gm.creative`

### Reproduction Steps

Migrate from YAML to MySQL storage with /lp export/import.

### Expected Behaviour

Commands should work with wildcards.

### Server Details

git-Paper-130 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 4ba43fe)

### LuckPerms Version

v5.4.41

**Comment by lucko** [comment]
Check with verbose. https://luckperms.net/wiki/Verbose

Choice of storage method is not a factor in permission resolution behaviour.
