### ISSUE TITLE
X butten hitbox is way too small in webeditor

### ISSUE THREAD

**Issue by leonpano2006** [LuckPerms/LuckPerms#3466]
### Description

X butten in screenshot is way too small and easy to press wrong things and made mistake
![image](https://user-images.githubusercontent.com/58368166/185386665-7f491053-e4a3-4c12-ba55-d24fc59d6d27.png)
i alradey made a mistake to give everyone to use op command due to this

### Proposed Behaviour

it suppose to be bigger hitbox at side and easier to press to remove insisted to go to default

**Comment by leonpano2006** [comment]
![Screenshot_20220818_135802](https://user-images.githubusercontent.com/58368166/185389403-711a64b3-61b3-4037-8193-8887007ff8e0.png)
l
can tell

**Comment by Turbotailz** [comment]
This belongs in LuckPerms/LuckPermsWeb
