### ISSUE TITLE
Replace button isn't working

### ISSUE THREAD

**Issue by Deimosssss** [LuckPerms/LuckPerms#3467]
### Description

After check anything permission and adding more context through panel below via ,,+" button, the button ,,Replace" has no role if I need add more contexts to existing or only replace.

### Reproduction Steps

Select and check anything permission that has any contect
Click on button ,,+" for adding contexts in panel below
Select anything context
Click on button ,,Replace"
Lastly, click on button ,,Update"

### Expected Behaviour

The context would be add to existing conctexts after check the button or should replace existing context and add new set.

### Server Details

git-Purpur-1609 (MC: 1.18.2)

### LuckPerms Version

v5.4.18

**Comment by Turbotailz** [comment]
I'm assuming this is for the web editor? In which case this issue belongs here: [LuckPerms/LuckPermsWeb](https://github.com/LuckPerms/LuckPermsWeb/issues)
