### ISSUE TITLE
[Forge] Use luckperms when player logout from death cause exception

### ISSUE THREAD

**Issue by Yann151924** [LuckPerms/LuckPerms#3471]
### Description

I make a quick [repo ](https://github.com/Mineaurion/testlp) to have a better explanation of the problem. But the issue come when a player is killed and go to the title screen an exception is raised saying the capability is missing on him. It will trigger the PlayerLoggedOutEvent on forge but on a classic disconnect it work like normal like ESC -> disconnect or ALT+F4

### Reproduction Steps

Kill yourself or `/kill YourPseudo` and then press title screen and title screen again and the exception appear
Kill yourself or `/kill YourPseudo` and then press respawn and no exception only the log i put

### Expected Behaviour

No exception need to be made when i kill myself and disconnect from the server

### Server Details

forge 1.18.2-40.1.60

### LuckPerms Version

v5.4.30

### Logs and Configs

Latest.log : https://pastebin.com/VMqYy7JD
Debug.log : https://pastebin.com/mX6hF4nx

Luckperms is the default one

### Extra Details

The repositories for the mod to test : https://github.com/Mineaurion/testlp

I made this for better understanding but this is part of 2 pr i made for FTB Mods to add lp support : https://github.com/FTBTeam/FTB-Mods-Issues/issues/285

**Comment by Yann151924** [comment]
I did another test round for debugging and the problem doesn't appear after the server is restarted

**Comment by lucko** [comment]
Will accept a PR to fix :)

**Comment by lucko** [comment]
https://github.com/LuckPerms/LuckPerms/commit/ce6031ad52def38e52428d0eb58e2f5b8474408c

Please re-test using LP v5.4.61 -- https://luckperms.net/download

**Comment by bloodmc** [comment]
Does this issue still occur on latest? If so, provide new logs.

**Comment by Yann151924** [comment]
With the last version, the issue is not here anymore.
For detail in case i test with the v5.4.67 version
