### ISSUE TITLE
Luckperms Sponge-Forge API8 with SQL cannot unset permissions

### ISSUE THREAD

**Issue by FerrisComplex** [LuckPerms/LuckPerms#3476]
### Description

When using SQL unsetting permissions from both groups and players seems to give feedback but not remove from the database or sync 

### Reproduction Steps

Setup Luckperms with SQL on spongeforge 1.16
Set a group or player permission
Try to unset said permission

### Expected Behaviour

Permission is removed from player/group

### Server Details

SpongeAPI 8.0.0 - SpongeForge 1.16.5-36.2.5-8.0.0-CustomBuild

### LuckPerms Version

v5.3.103

### Logs and Configs

Permission being set removed from group (With editor)
https://gyazo.com/01112dbce634141c03e824b51717e090

Permissions still existing in the group after removal
https://gyazo.com/b38354e437c0bdf05e1218de5018e301
```
[Server thread/INFO] [/]: [08-28 16:58:43] [Server thread] [INFO] CommandLoggerModule » Jirachi tried to run "lp group default permission unset test.perm"
[Server thread/INFO] [/]: [08-28 16:58:43] [Server thread] [INFO] CommandLoggerModule » Jirachi ran "lp group default permission unset test.perm" 
[28Aug2022 16:58:43.072] [luckperms-command-executor/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: [LP] LOG > (Jirachi@violet) [G] (default)
[28Aug2022 16:58:43.072] [Sponge-AsyncScheduler-1700/INFO] [luckperms/]: [Messaging] Sending log with id: 54732b99-f799-4d23-a0cd-2d70c4871d6a
[28Aug2022 16:58:43.072] [luckperms-command-executor/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: [LP] LOG > permission unset test.perm

```

**Comment by LeotomasMC** [comment]
try updating luckperms and see if the issue still persists

**Comment by FerrisComplex** [comment]
Same issue on latest

**Comment by FerrisComplex** [comment]
Slight update seems like the database has thousands of null id entries from the old remove might be related

**Comment by FerrisComplex** [comment]
https://gyazo.com/8849f98b49857fcd56ec0ac5c0fa8cdf
Very much still an issue

**Comment by FerrisComplex** [comment]
Edit solution found turns out our schema (used sql on mariadb) did not create primarykeys or autoincrement on any of the permission tables

https://gyazo.com/88d8e9b6961687ee70c8488873b7492d
added PK and AI to expected spots and everything functions unsure if this is an issue with table creation using SQL on MARIA but seems like a pretty glaring issue for that that will not autocorrect itself currently

Would be nice to have an automatic check that updates tables to have PK/AI on startup before load to ensure that issue does not happen but all seems good now!
