### ISSUE TITLE
Meta ordering not working

### ISSUE THREAD

**Issue by LuluxClient** [LuckPerms/LuckPerms#3479]
### Description

I currently want to show a "tag" when a player is in a rank. The player already has a prefix suffix and I'm using the meta method and the placeholder to show it within a menu. The issue is it will always take the lowest meta based on weight from the permissions. For example my default rank weight is 5 and my highest is 200 but it will always show the lowest one

### Reproduction Steps

- Create 2 groups
- 1 with one with a weight value of 5 and the other one 100 
- give this perm to the lowest one: meta.profilerang.&fTEST1
- give this perm to the highest one: meta.profilerang.&fTEST2
- Do /papi parse me %luckperms_meta_profilerang%

and it will always show TEST1

### Expected Behaviour

I should see the highest one.

### Server Details

1.18.2

### LuckPerms Version

5.4.41

### Logs and Configs

0 errors

**Comment by NullTxt** [comment]
Your version for luckperms is out of date
