### ISSUE TITLE
java.lang.NoSuchMethodError: 'java.util.List me.lucko.luckperms.common.config.generic.adapter.ConfigurationAdapter.getKeys(java.lang.String, java.util.List)'

### ISSUE THREAD

**Issue by WhiTe-Yak** [LuckPerms/LuckPerms#3480]
### Description

Plugin not worked.

### Reproduction Steps

Start server.

### Expected Behaviour

Normal work plugin.

### Server Details

Purpur version git-Purpur-1774 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT)

### LuckPerms Version

v5.4.40 and v5.4.41

### Logs and Configs

https://gist.github.com/WhiTe-Yak/3a1e7bae4c941f632202287e857ec608

**Comment by LeotomasMC** [comment]
delete the `/plugins/luckperms/libs/` directory and try starting the server again

**Comment by WhiTe-Yak** [comment]
> delete the `/plugins/luckperms/libs/` directory and try starting the server again

It didn't help, the error remained.

**Comment by mly2839** [comment]
Try using version 5.4.46 from [their website](https://luckperms.net), mine didn't work with the previous ones, but when I deleted the plugins/luckperms and updated to that version, it worked for me
