### ISSUE TITLE
Exception caught during firing event

### ISSUE THREAD

**Issue by Sblash** [LuckPerms/LuckPerms#3481]
### Description

I'm attempting to use LuckPerms latest 1.19.2 Forge build on my server which is running Forge 43.1.16. I tested with LuckPerms 5.4.36 being the only mod installed with a clean server, and upon player login after the server starts, the server crashes.

### Reproduction Steps

Install Forge Server 43.1.16.
Add LuckPerms 5.4.36 to mods folder.
Start server.
Login to server after server is ready.
See server crash.

### Expected Behaviour

No crash

### Server Details

1.19.2 forge 43.1.16

### LuckPerms Version

5.4.36

### Logs and Configs

https://gist.github.com/Sblash/cefe5576caddcd40da3a257407c67e60

**Comment by LeotomasMC** [comment]
the "latest" luckperms forge build is actually 5.4.41, not 5.4.36 (as of writing this). try updating luckperms because .39 included a fix related to forge.

**Comment by Sblash** [comment]
Thank you, that works.
But please update the version on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/luckperms/files) because i downloaded from there and it wasn't the last version.
