### ISSUE TITLE
Declare a stable module name

### ISSUE THREAD

**Issue by A248** [LuckPerms/LuckPerms#3482]
### Description

The LuckPerms API jar is published without a stable module name. The filename-derived module name is `api`, which is clearly ambiguous.

While no platform supported by LuckPerms currently uses the module system, defining a stable module name has no cost. Some dependents may benefit at compilation time from a stable module name, even if the module system is inoperative at runtime. Compiling with module-info clarifies dependency usage.

<sub>Also, it is theoretically possible for a server fork to implement the module system, but this is of relatively small importance</sub>

### Proposed Behaviour

I propose defining the `net.luckperms.api` or `net.luckperms` module name using the `Automatic-Module-Name` jar manifest attribute.

**Comment by lucko** [comment]
Thanks
