### ISSUE TITLE
silently add user permissions

### ISSUE THREAD

**Issue by aparry91** [LuckPerms/LuckPerms#3484]
### Description

Add the ability to flag -s on other commands such as user permissions rather than outputting - running LP Perms

### Proposed Behaviour

Aid with keeping players immersed and not identifying that a LP command is being run to a general player

**Comment by LeotomasMC** [comment]
normal players should not be running luckperms commands to get an output beyond just the version number

**Comment by davidgb8246** [comment]
I think it's a good idea to add this feature. Could be used to prevent administrators from receiving certains log messages from luckperms on a big server

**Comment by LeotomasMC** [comment]
there is already a command that players with permission to see the log can use to stop seeing log messages in game.

**Comment by aparry91** [comment]
> normal players should not be running luckperms commands to get an output beyond just the version number

In my instance I am adding a click event that runs a luckperms command, normal player 'accepts' the dialogue, and shortly after is greeted with a beautifully big bright LP message to indicate it is running - I feel it is unecessary for normal players to have this info and removes from the immersive experience.  If the normal player is not running a version check, I feel they shouldn't be informed about the background process of a click event.

command attached to the click event is 
`/lp user @p permission set quest_accepted.heimerdinger.a true`
![Untitled](https://user-images.githubusercontent.com/30159032/190882327-37bb16a5-1861-4ccf-8b4a-b7fb40a08fd5.png)

Command is correctly run, and permission is correctly added as expected, its the message that is irrelevant for the normal user

**Comment by Turbotailz** [comment]
This sounds more like an issue with your setup. Are you making the event run the command as the player? You shouldn't be doing this, make the command run from console instead if possible.

**Comment by aparry91** [comment]
> This sounds more like an issue with your setup. Are you making the event run the command as the player? You shouldn't be doing this, make the command run from console instead if possible.

Hmm well, the player right clicks the Confirm, with all luck perm permissions set to false, and then it initiates the command through Mythic Mobs, populates the trigger.name as the player who triggered the events name, Trigger being a right click on a mob and seems to get the info message

`/lp user <trigger.name> permission set quest_accepted.heimerdinger.a true`

I'm not very java savvy or anything like that but:

This seems to be where the [Running version message](https://github.com/LuckPerms/LuckPerms/blob/master/common/src/main/java/me/lucko/luckperms/common/locale/Message.java#L1550-L1559) is generated, sitting under: `Args2<LuckPermsPlugin, Map<Component, Component>> INFO = (plugin, storageMeta) -> join(newline()`

And the user promote/demote has examples of a flag to silence the message like so:
[silence example in user demote](https://github.com/LuckPerms/LuckPerms/blob/master/common/src/main/java/me/lucko/luckperms/common/commands/user/UserDemote.java#L97)
[conditional for silence message](https://github.com/LuckPerms/LuckPerms/blob/master/common/src/main/java/me/lucko/luckperms/common/commands/user/UserDemote.java#L145-L147)

was thinking I could add something similar in [here](https://github.com/LuckPerms/LuckPerms/blob/master/common/src/main/java/me/lucko/luckperms/common/commands/misc/InfoCommand.java#L49)

just not really sure if this is where the message is being generated or if that is being consumed by [PermissionSet.java](https://github.com/LuckPerms/LuckPerms/blob/master/common/src/main/java/me/lucko/luckperms/common/commands/generic/permission/PermissionSet.java)

**Comment by lucko** [comment]
> This sounds more like an issue with your setup. Are you making the event run the command as the player? You shouldn't be doing this, make the command run from console instead if possible.

Exactly this - the command triggers should be executed as the console, not as the player.

Seems like mythicmobs supports this: https://git.mythiccraft.io/mythiccraft/MythicMobs/-/wikis/skills/mechanics/command

if you configure this correctly, the player shouldn't get the "running luckperms version aaa" feedback in their chat.

**Comment by aparry91** [comment]
> > This sounds more like an issue with your setup. Are you making the event run the command as the player? You shouldn't be doing this, make the command run from console instead if possible.
> 
> Exactly this - the command triggers should be executed as the console, not as the player.
> 
> Seems like mythicmobs supports this: https://git.mythiccraft.io/mythiccraft/MythicMobs/-/wikis/skills/mechanics/command
> 
> if you configure this correctly, the player shouldn't get the "running luckperms version aaa" feedback in their chat.

actually already tried setting up the command mechanic to work with the tellraw command, running with the asOp functionality:
it works in the exact same way as the jsonmessage, I feel the only difference is that jsonmessage allows you to nicely view your message.  I have infact even tried using the asCaster. please see below.

According to MythicMob docs if setup with asOp The player that Triggers the command with right click actually executes the command with all permissions

I've tried running the command in several ways now, all with the same result:
```
  Skills:
  - command{c="tellraw <trigger.name> [<&dq><&dq>,<&dq>\n<&dq>,<&dq>\n<&dq>,<&lc><&dq>text<&dq>:<&dq>Would you like to start Heimerdinger's quest? <&dq>,<&dq>color<&dq>:<&dq>dark_aqua<&dq><&rc>,<&lc><&dq>text<&dq>:<&dq>[Confirm]<&dq>,<&dq>color<&dq>:<&dq>dark_green<&dq>,<&dq>clickEvent<&dq>:<&lc><&dq>action<&dq>:<&dq>run_command<&dq>,<&dq>value<&dq>:<&dq>/lp user <trigger.name> permission set quest_accepted.heimerdinger.a true<&dq><&rc>,<&dq>hoverEvent<&dq>:<&lc><&dq>action<&dq>:<&dq>show_text<&dq>,<&dq>contents<&dq>:[<&lc><&dq>text<&dq>:<&dq>Click to Confirm<&dq>,<&dq>color<&dq>:<&dq>dark_green<&dq><&rc>]<&rc><&rc>,<&dq>\n<&dq>,<&dq>\n<&dq>]";} @trigger ~onInteract
```

```
  Skills:
  - command{c="tellraw <trigger.name> [<&dq><&dq>,<&dq>\n<&dq>,<&dq>\n<&dq>,<&lc><&dq>text<&dq>:<&dq>Would you like to start Heimerdinger's quest? <&dq>,<&dq>color<&dq>:<&dq>dark_aqua<&dq><&rc>,<&lc><&dq>text<&dq>:<&dq>[Confirm]<&dq>,<&dq>color<&dq>:<&dq>dark_green<&dq>,<&dq>clickEvent<&dq>:<&lc><&dq>action<&dq>:<&dq>run_command<&dq>,<&dq>value<&dq>:<&dq>/lp user <trigger.name> permission set quest_accepted.heimerdinger.a true<&dq><&rc>,<&dq>hoverEvent<&dq>:<&lc><&dq>action<&dq>:<&dq>show_text<&dq>,<&dq>contents<&dq>:[<&lc><&dq>text<&dq>:<&dq>Click to Confirm<&dq>,<&dq>color<&dq>:<&dq>dark_green<&dq><&rc>]<&rc><&rc>,<&dq>\n<&dq>,<&dq>\n<&dq>]";asOp=true} @trigger ~onInteract
```

```
  Skills:
  - command{c="tellraw @p [<&dq><&dq>,<&dq>\n<&dq>,<&dq>\n<&dq>,<&lc><&dq>text<&dq>:<&dq>Would you like to start Heimerdinger's quest? <&dq>,<&dq>color<&dq>:<&dq>dark_aqua<&dq><&rc>,<&lc><&dq>text<&dq>:<&dq>[Confirm]<&dq>,<&dq>color<&dq>:<&dq>dark_green<&dq>,<&dq>clickEvent<&dq>:<&lc><&dq>action<&dq>:<&dq>run_command<&dq>,<&dq>value<&dq>:<&dq>/lp user @p permission set quest_accepted.heimerdinger.a true<&dq><&rc>,<&dq>hoverEvent<&dq>:<&lc><&dq>action<&dq>:<&dq>show_text<&dq>,<&dq>contents<&dq>:[<&lc><&dq>text<&dq>:<&dq>Click to Confirm<&dq>,<&dq>color<&dq>:<&dq>dark_green<&dq><&rc>]<&rc><&rc>,<&dq>\n<&dq>,<&dq>\n<&dq>]";asOp=true} @None ~onInteract
```

```
  Skills:
  - jsonmessage{m="['','\n','\n',{'text':'Would you like to start Heimerdinger\'s quest? ','color':'dark_aqua'},{'text':'[Confirm]','color':'dark_green','clickEvent':{'action':'run_command','value':'/lp user <trigger.name> permission set quest_accepted.heimerdinger.a true -s'},'hoverEvent':{'action':'show_text','contents':[{'text':'Click to start Heimerdinger\'s quest.','color':'dark_aqua'}]}},'\n','\n']"} @trigger ~onInteract
```

All results gave the same:
![Untitled](https://user-images.githubusercontent.com/30159032/190898026-70e234ad-4f3c-4558-84e1-121cf49d052a.png)
