### ISSUE TITLE
Cannot import to mysql database

### ISSUE THREAD

**Issue by My1Legocraft** [LuckPerms/LuckPerms#3485]
### Description

Hi,

I am trying to import my export to a mysql database (with multiple servers) every time I do I get this "error"

[LP] (Import) -> Starting import process.
[LP] (Import) -> Reading data....
[LP] (Import) -> Waiting for initial update task to complete....

It stays like this for days and won't ever complete I have tried putting the export on a local server doing /luckperms import --upload and doing the 10 digit code on my actual server but the same thing happens I don't know what's wrong if someone could help me out and point me in the right direction that would be great, and if you need me to send another let me know, thank you

### Reproduction Steps

export your groups + users
switch storage type to mysql
attempt to import and its stays stuck on this message:

[LP] (Import) -> Starting import process.
[LP] (Import) -> Reading data....
[LP] (Import) -> Waiting for initial update task to complete....

### Expected Behaviour

It's supposed to import.

### Server Details

git-Paper-160 (MC 1.19.2) - 1.19.2-R0.1-SNAPSHOT

### LuckPerms Version

v5.4.4.6

### Logs and Configs

https://pastes.dev/oDt9XNi7gD

**Comment by NullTxt** [comment]
From just looking at it it seems it could be caused by like half of your skript plugins failing to load

**Comment by My1Legocraft** [comment]
> From just looking at it it seems it could be caused by like half of your skript plugins failing to load

Why would skript be the issue?

**Comment by lucko** [comment]
Please generate a stack dump when the process gets stuck.
https://gist.github.com/lucko/81033b72927eee0246dc8e8c284664c4
