### ISSUE TITLE
1.17.10 legacy bootstrap crash

### ISSUE THREAD

**Issue by freedom1b2830** [LuckPerms/LuckPerms#3487]
### Description

class not found

### Reproduction Steps

download legacy 1.7.10 from https://luckperms.net/download
start server
(plugin not started)

### Expected Behaviour

working plugin

### Server Details

1.7.10-1614.58 (MC: 1.7.10)

### LuckPerms Version

Legacy-5.4.46

### Logs and Configs

https://gist.github.com/freedom1b2830/6e4f143422d09d7c01dbad8480b9fa57

**Comment by underscore11code** [comment]
This feels like a possibly corrupted jar. Try deleting your jar, redownloading, and reinstalling.

If that doesn't work, please attach the full logs, not just the LP error.

**Comment by freedom1b2830** [comment]
the old version of the kernel library was used
