### ISSUE TITLE
Error on world change

### ISSUE THREAD

**Issue by LuluxClient** [LuckPerms/LuckPerms#3494]
### Description

No idea by what it's caused but luckperms is spamming my console of errors: https://pastebin.com/BUnpbuFw

### Reproduction Steps

no idea

### Expected Behaviour

shouldn't spam errors

### Server Details

1.16.5

### LuckPerms Version

v5.4.46

**Comment by ZeromaniacMc** [comment]
Please post a picture of `/plugins` or (better) include a full log as asked in the template.

**Comment by lucko** [comment]
Try deleting the libs directory in the LuckPerms folder and restarting your server.
