### ISSUE TITLE
Something Is Stopping LP From Seeing Me Online

### ISSUE THREAD

**Issue by Masterisop** [LuckPerms/LuckPerms#3497]
### Description

It been a while since i am getting a issue
The Issue is
Lp Dont Register me as online
So Its Difficult To Config It
I Hope You Understand And Oblidged

### Reproduction Steps

I Want You To Do Something To Let Me Show Online
And Also Don't The Plugin Take My OP Back

### Expected Behaviour

I Expected to see me Online But It Does'nt , Still I Am Using Premium Account

### Server Details

git-Paper-411 (MC: 1.17.1)

### LuckPerms Version

v5.4.40

### Logs and Configs

Config - https://gist.github.com/Masterisop/271a8e0983486a3208916f12348d6940
Logs - https://gist.github.com/Masterisop/fd1bd1ec54a1f1e01c762ef55535ba77

**Comment by lucko** [comment]
Not a LuckPerms issue - please use Discord for support
