### ISSUE TITLE
if there isn't already, perhaps add a way to set spawns for certain ranks

### ISSUE THREAD

**Issue by GuyInTheAlley** [LuckPerms/LuckPerms#3502]
### Description

i think that making spawns for certain ranks would be a cool feature. if there isn't already, perhaps add it?

### Proposed Behaviour

if a player has a rank with a special spawnpoint, they would spawn at provided coordinates

**Comment by TheIntolerant** [comment]
This isn't something LuckPerms handles. That being said, the ability to create a spawn for a specific rank already exists in plugins such as, EssentialsX and CMI

**Comment by OmegaWeaponDev** [comment]
As already mentioned above, 
This is not something that Luckperms handles. You will need to find a third party plugin that deals with setting spawns and get that plugin to handle the per-group spawn locations.
