### ISSUE TITLE
LP Editor Command Erroring

### ISSUE THREAD

**Issue by Optio1** [LuckPerms/LuckPerms#3506]
### Description

The LP Editor command is erroring with the error specified below in logs area.

The command worked once, and then errors afterwards.

### Reproduction Steps

Install Luck Perms,
Use the LP Editor command,
close out of browser tab after making any change
try to use the lp editor command again

### Expected Behaviour

The command succeeds and yields a new editor link

### Server Details

CraftBukkit version 3597-Spigot-4aa5ead-aaf484f (MC: 1.19.2)

### LuckPerms Version

v1.4.49

### Logs and Configs

https://gist.github.com/Optio1/2bd39e0a1135c67c8cecaacf89626868

**Comment by lucko** [comment]
Looks like networking issues - might be at my end, or yours! (although things are usually pretty stable)

If it's still happening, it is most likely your servers internet connection.
