### ISSUE TITLE
ranks reset

### ISSUE THREAD

**Issue by Vxrtebs** [LuckPerms/LuckPerms#3507]
### Description

all my ranks and users have been reset after a server restart, also I dont have any backup...

### Reproduction Steps

.

### Expected Behaviour

.

### Server Details

Purpur 1.17.1

### LuckPerms Version

v5.4.49

**Comment by Aberdeener** [comment]
Solved in Discord.
They restored an editor link and things are better now. A good reminder to always have backups!
