### ISSUE TITLE
 Something went wrong whilst upgrading the LuckPerms database. Please report this on GitHub. java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by gordonchew** [LuckPerms/LuckPerms#3508]
### Description

Something corrupted in LP database I believe, need help to know how to solve it
Logs : https://pastebin.com/jFHrDxFF

Happened after server restarted.

### Reproduction Steps

Something corrupted in LP database I believe, need help to know how to solve it

### Expected Behaviour

Wish to get solution to know how to recover the database.

### Server Details

git-Purpur-1799 (MC: 1.19.2)

### LuckPerms Version

v5.4.50

### Logs and Configs

https://pastebin.com/jFHrDxFF

**Comment by martijnpu** [comment]
Thank you for reporting.
This H2 database transfer is added in the latest version of LuckPerms, released about an hour back, as fix for Hs-database corruption. #3458 
Pinging @lucko to investigate this issue where it looks like there is an error while migrating from H2-v1 to H2-v2.

**Comment by lucko** [comment]
@gordonchew was everything ok before you updated LuckPerms?

**Comment by gordonchew** [comment]
> @gordonchew was everything ok before you updated LuckPerms?

Everything is not okay before, so that i wanted to upgrade it to fix it. and its been like this.

**Comment by Togglerine** [comment]
Is any chance to fix this? I don't know whether i should create new groups and permission because of these don't work or not

**Comment by lucko** [comment]
Your best bet is the H2 recovery tool - but if it's corrupted then there's not a whole lot I can do to help, sorry
