### ISSUE TITLE
Table 'minecraft.luckperms_groups' doesn't exist

### ISSUE THREAD

**Issue by Fairweather-Furry** [LuckPerms/LuckPerms#3509]
### Description

After setting up a MySQL server on the same machine as my Minecraft proxy, I tried to set up shared storage. Unfortunately, I keep receiving errors about tables not existing in the database. Is that something that has to be set up manually? I have the MySQL login setup to have the right privileges to create it by itself.
My server is running on Ubuntu Server 22.04 if that at all is relevant.

### Reproduction Steps

1. Create a Database in MySQL named minecraft
2. Setup a user and password in MySQL
3. Grant all privileges to user for database
4. Start MySQL service
5. Add MySQL details to LuckPerms' config
6. Start Velocity
7. Receive error and suffer

### Expected Behaviour

LuckPerms should create the necessary tables in the database it needs on its own if tables are missing.

### Server Details

Velocity 3.1.2 Snapshot 184

### LuckPerms Version

5.4.50

### Logs and Configs

https://gist.github.com/Fairweather-Furry/7bdab0b2643ccb54aa693e60bbeb619b

### Extra Details

If any more info is needed, I can provide if asked.

**Comment by lucko** [comment]
Seems like the 1st time setup didn't work correctly the first time.

Your best bet is to manually delete all of the existing luckperms tables, then start the plugin again and it should recreate them.
