### ISSUE TITLE
Server crashes when a player tries to join

### ISSUE THREAD

**Issue by CrazyDev05** [LuckPerms/LuckPerms#3510]
### Description

I wanted to use LuckPerms on my "Encrypted_" server, but when i tried to join the server, the server crashed

### Reproduction Steps

1. install a encrypted_ server (https://www.curseforge.com/minecraft/modpacks/encrypted_/files/3957277) 
2. install LuckPerms Forge 5.4.50 on the server
3. start the server
4. join the server
5. server crashes

### Expected Behaviour

Nothing, just a player joining the server

### Server Details

net.minecraftforge:40.1.73

### LuckPerms Version

v5.4.50

### Logs and Configs

https://gist.github.com/CrazyDev05/858d042e6bcb49df4e683e68af375059

**Comment by LeotomasMC** [comment]
The latest version of LuckPerms is for Forge 1.19.2. Try downloading the latest 1.18.2 build from CurseForge.

**Comment by CrazyDev05** [comment]
i'll try

**Comment by CrazyDev05** [comment]
works now, thank you
