### ISSUE TITLE
when promoting a user, the username must be in all lowercase?

### ISSUE THREAD

**Issue by user4302** [LuckPerms/LuckPerms#3512]
### Description

so theres a user like this
AnAmazingUser

when i use
lp user AnAmazingUser promote
i get the error : AnAmazingUser is not a valid username/uuid.

but if i use 
lp user anamazinguser promote
it works.

is this the expected behaviour?

### Reproduction Steps

when i use
lp user AnAmazingUser promote
i get the error : AnAmazingUser is not a valid username/uuid.

but if i use 
lp user anamazinguser promote
it works.

### Expected Behaviour

when i use
lp user AnAmazingUser promote
it should promote the user

### Server Details

git-paper-219 (MC: 1.19.2)

### LuckPerms Version

v5.4.50

**Comment by lucko** [comment]
Cannot reproduce
