### ISSUE TITLE
Please add support for command block operator @p

### ISSUE THREAD

**Issue by sketrick** [LuckPerms/LuckPerms#3514]
### Description

Currently there's no way to add roles via command blocks due to LuckPerms not having "Player Name" operator.

### Proposed Behaviour

Using </lp user @p group add GroupName> in command block shoud give the Player "GroupName" group.

But as it is, it just returns @p is not recognized as a player.

### Extra Details

If you can please add this to 1.18.2 Fabric plugin.

**Comment by LeotomasMC** [comment]
Have you looked in the config file? There is [an option](https://github.com/LuckPerms/LuckPerms/blob/5ff9a12a727432f32efb3978782ea3d48449687d/fabric/src/main/resources/luckperms.conf#L640) for this.

**Comment by sketrick** [comment]
I literally spend all day looking for work arounds online using FTBRanks and Player Ranks and this was an option in the config all along x_x
I'm deceased. 
Thank you for saving my sanity :D
