### ISSUE TITLE
Error with RedisBungee Faker

### ISSUE THREAD

**Issue by Lefraudeur** [LuckPerms/LuckPerms#3516]
### Description

When I install both luckperms and RedisBungee faker, luckperms thinks it's a real redisBungee, so it sends redisBungee api request.
This requests aren't supported by RedisBungee Faker so it leads to errors in the console.
I know, It's not really a bug in luckperms but more an incompability.

### Reproduction Steps

Install both luckperms and RedisBungee faker on bungeecord

### Expected Behaviour

Luckperms should detect redisbungee faker. So that it stops making false api requests. Or maybe add an option in the configuration to force disable redis bungee.

### Server Details

waterfall-1.19-506 [c64ebfc]

### LuckPerms Version

v5.4.50

### Logs and Configs

https://gist.github.com/Lefraudeur/0c374c21284ba617db44328eda9f45a0

**Comment by LeotomasMC** [comment]
that name impies it is pretending to be the real thing, does it not?

**Comment by Lefraudeur** [comment]
> 

Yes it pretends RedisBungee is installed but it's not, I use this for party and friends extended

**Comment by Lefraudeur** [comment]
> that name impies it is pretending to be the real thing, does it not?

Yes it pretends RedisBungee is installed but it's not, I use this for party and friends extended

**Comment by LeotomasMC** [comment]
so you want luckperms to detect that a plugin is pretending to be another plugin, and not do something...?

**Comment by Lefraudeur** [comment]
> so you want luckperms to detect that a plugin is pretending to be another plugin, and not do something...?

Exactly

**Comment by Evidentsinger14** [comment]
🤨

**Comment by underscore11code** [comment]
This is out of scope for LP. If another plugin is mocking a plugin we depend on, but doesn't actually provide everything that the mocked plugin contains, that's not our problem. 

As far as I can tell, the only RedisBungee methods we rely on with default config are `RedisBunge.getApi`, `RedisBungeApi#getServerId`, and `RedisBungeApi#getAllServers`, those all seem like very reasonable and simple things for a mock to implement.
