### ISSUE TITLE
LP dont recognize UUID/Username

### ISSUE THREAD

**Issue by Gamer014277** [LuckPerms/LuckPerms#3517]
### Description

Hi!,
When i try Run the LP give command it says "[username] is not a valid UUID/Username"

### Reproduction Steps

lp user {username} parent set {group}

### Expected Behaviour

N/A

### Server Details

Paper_1.19.2

### LuckPerms Version

v5.3.70

### Logs and Configs

N/A

### Extra Details

N/A

**Comment by Turbotailz** [comment]
what exactly is the command that you are running?

**Comment by Turbotailz** [comment]
keep in mind that if you are using something like Geyser for Bedrock players you will need to set to `allow-invalid-usernames` false
https://luckperms.net/wiki/Configuration#allow-invalid-usernames

**Comment by Gamer014277** [comment]
Thank you for the resolution!

**Comment by edge73999-crypto** [comment]
this problem only accurse when a bedrock play is in the server with the prefix . you can either change the prefix from something other than a . or * or you can go to luckperms config.yml and change allow-invalid-usernames from false to true

**Comment by BNTFryingPan** [comment]
yes, this was already posted in the issue. please dont answer already answered issues with the already provided answer

**Comment by edge73999-crypto** [comment]
> yes, this was already posted in the issue. please dont answer already answered issues with the already provided answer

I saw i provided an alternative in case if his didn't work some times things dont work the same for everyone
