### ISSUE TITLE
Error logs in console for no reason, luckperms command doesn't work

### ISSUE THREAD

**Issue by darthpeti** [LuckPerms/LuckPerms#3518]
### Description

For some reason when I started my server, luckperms refused to operate and started throwing errors in console.

### Reproduction Steps

- load the server
- wait a bit (for me the errors started throwing after I unloaded a non-lp related plugin with plugman, not sure if it has anything to do with this tho)
- console now gets spammed with errors, LP doesn't work

### Expected Behaviour

 - "/lp" should work
 - errors shouldn't be thrown in the chat.

### Server Details

git-Paper-81 (MC 1.19)

### LuckPerms Version

v5.4.52

### Logs and Configs

https://gist.github.com/darthpeti/c044c607eabb26f9625ff58ad9ba6927 - LP RELATED LOGS

**Comment by underscore11code** [comment]
This error is almost always a symptom of a reload. Have you used `/reload`, plugman load/enable/disable/reload, or similar?

**Comment by darthpeti** [comment]
yeah, plugman load and unload. but i used it on another plugin, not luckperms

**Comment by darthpeti** [comment]
sorry, i meant enable/disable
should it be an issue that luckperms is throwing errors when i'm enabling a plugin that is not related to it?
