### ISSUE TITLE
Lost all ranks after updating

### ISSUE THREAD

**Issue by GamingVexed** [LuckPerms/LuckPerms#3520]
### Description

I updated the plugin after that all ranks went missing, so did i lose all the data now?

### Reproduction Steps

How can i fix this?

### Expected Behaviour

All ranks would be there after updating

### Server Details

paper 1.19.2

### LuckPerms Version

v5.4.52

**Comment by underscore11code** [comment]
Could you please send your full startup logs? LP isn't in the habit of randomly deleting your data so I suspect there was an error loading it.
