### ISSUE TITLE
Set the gamemode for players based on their user group

### ISSUE THREAD

**Issue by RMSCA** [LuckPerms/LuckPerms#3526]
### Description

Automatically set the gamemode of a player based on his user group

### Proposed Behaviour

For example, I have two groups called visitor and player. Whenever a player joins the server, the plugin will check the user group of that player, if the player belongs to the visitor group, the plugin will automatically set the gamemode of that player to adventure (If it's not adventure already). If the player belongs to player group, the plugin will set the gamemode of that player to survival.

### Extra Details

I'm not sure if this should be posted here, if this is not the type of feature that luckperms will implement, please correct me and I will look for other plugins, thank you

**Comment by ZeromaniacMc** [comment]
This is something I personally find to not fit into a "permission manager". The plugin called "Conditional Events" can do this.

**Comment by LeotomasMC** [comment]
This is likely out of scope for LuckPerms. If you want players to be unable to build, you should use a plugin that does that, such as WorldGuard.

**Comment by RMSCA** [comment]
Like i said, I'm not sure if this is the type of feature that will be implemented in luckperms. I will take a look at the conditional events plugin, thanks for replying me!
