### ISSUE TITLE
typo in czech language translation

### ISSUE THREAD

**Issue by hairpinNAT** [LuckPerms/LuckPerms#3527]
### Description

Typo in file cs_CZ.properties on line 253:
wrong:
luckperms.command.user.demote.success=Degraduji uživatele {0} na trase {1} z {2} ns {3} v kontextu {4}
correct:
luckperms.command.user.demote.success=Degraduji uživatele {0} na trase {1} z {2} na {3} v kontextu {4}

### Reproduction Steps

look at line 253 in cs_CZ.properties

### Expected Behaviour

replace typo with coorect word

### Server Details

paper 1.19.2

### LuckPerms Version

LuckPerms v5.4.52

**Comment by LeotomasMC** [comment]
you can contribute to the [crowdin](https://crowdin.com/project/luckperms) to fix errors like this yourself
