### ISSUE TITLE
Could not pass event AsyncTabCompleteEvent to LuckPerms

### ISSUE THREAD

**Issue by SnonSS** [LuckPerms/LuckPerms#3528]
### Description

Here is such an error

Could not pass event AsyncTabCompleteEvent to LuckPerms

### Reproduction Steps

Here is such an error

Could not pass event AsyncTabCompleteEvent to LuckPerms

### Expected Behaviour

Here is such an error

Could not pass event AsyncTabCompleteEvent to LuckPerms

### Server Details

Purpur 1.18.2-R0.1-SNAPSHOT

### LuckPerms Version

v5.4.52

**Comment by ZeromaniacMc** [comment]
I sincerely hope you did not use /reload or plugman to reload LuckPerms. 
If you didn't, please upload your entire latest.log in a pastebin. We can't help you unless we can investigate the cause. The title of the error could have multiple reasons.
If you did, a restart will fix it. LuckPerms cannot be reloaded that way.

**Comment by SnonSS** [comment]
> Я искренне надеюсь, что вы не использовали /reload или plugman для перезагрузки LuckPerms. Если вы этого не сделали, пожалуйста, загрузите всю свою последнюю версию.log в pastebin. Мы не можем помочь вам, если мы не сможем расследовать причину. Название ошибки может иметь несколько причин. Если вы это сделали, перезагрузка исправит это. LuckPerms не может быть перезагружен таким образом.

Through / reload did not reboot only through restart

**Comment by ZeromaniacMc** [comment]
Sorry, what?

**Comment by SnonSS** [comment]
> Извините, что?

I just use a translator, I'm Ukrainian and I don't know English almost

**Comment by SnonSS** [comment]
[latest.log](https://github.com/LuckPerms/LuckPerms/files/10085621/latest.log)

**Comment by underscore11code** [comment]
Plugman, `/reload`, and similar functions cause issues with most plugins, Luckperms included. Restart the server and the issues should resolve themselves. For more information, see [this](https://s.u11.io/norl) wonderful blog post explaining the problems with reloading.

*Notable exception, if a plugin provides it's own internal command i.e. `/lp reloadconfig`, those are fine to use.*
