### ISSUE TITLE
New placeholder request

### ISSUE THREAD

**Issue by NEZNAMY** [LuckPerms/LuckPerms#3531]
### Description

A placeholder that returns weight of the group with highest weight assigned to a player. Currently, the closest placeholder to this is `%luckperms_highest_group_by_weight%`, which returns name of the group. Instead of name of the group, the new placeholder should return its weight.

### Proposed Behaviour

Placeholder would take all groups of a player, get their weights and return the highest one.
Example: Player is a member of following groups:
owner - 100
admin - 50
default - 1

The placeholder would return `100`.

### Extra Details

Adding this placeholder will allow users to achieve the legendary sorting by luckperms weights.

**Comment by lucko** [comment]
Thanks @Aberdeener!
