### ISSUE TITLE
luckperm prefix issue

### ISSUE THREAD

**Issue by ShadiestCaed** [LuckPerms/LuckPerms#3535]
### Description

can someone help me with this one? everytime i try yo use this "/lp group default meta addprefix &7(&eMember "
nothing changes it worked the first time i used it but whenn i tried to change the prefix now it's just saying "Command Usage - addprefix"  or in other /lp commands
![2022-12-14_23 07 29](https://user-images.githubusercontent.com/120581343/207633448-30a61a9e-7876-4264-8044-7d43c756057a.png)

### Reproduction Steps

help with the commands

### Expected Behaviour

i need help to fix this issue or if im doing something wrong.

### Server Details

Spigot 1.19.2 

### LuckPerms Version

v5.4.40.

**Comment by LeotomasMC** [comment]
its telling how to use the command because you didnt use it correctly. carefully read what each argument is supposed to be.
