### ISSUE TITLE
Error appearing on its own

### ISSUE THREAD

**Issue by ccyounga** [LuckPerms/LuckPerms#3543]
### Description

Hello. Recently there was an error, the solution of which I did not find and I do not quite understand what it refers to. It in every possible way interferes with the normal operation of rights, complaints come that something does not work for someone due to a lack of rights.

### Reproduction Steps

I do not know how and in what cases it occurs, even restarted the server several times, it appears by itself.

### Expected Behaviour

I'm just waiting for the plugin to work properly.

### Server Details

paper-1.18.2-386

### LuckPerms Version

LuckPerms-Bukkit-5.4.40

### Logs and Configs

https://gist.github.com/ccyounga/0a4ccc9d3732456c625d752027ce72a4

**Comment by underscore11code** [comment]
Delete the `plugins/Luckperms/libs` folder and restart.

**Comment by ccyounga** [comment]
The method helped only once, the plugin began to swear at another class again, deleting the libs folder does not help.
https://hastebin.com/negokuxida.properties
