### ISSUE TITLE
Bug with offline lookup (user is online)

### ISSUE THREAD

**Issue by kalleswe** [LuckPerms/LuckPerms#3544]
### Description

There is a bug in version 5.4.55.

The player is ONLINE not offline as the message suggests. Also the vault-unsafe-lookups does not work even if set to true the following shit is spammed in the log.

LuckPerms cannot respond to the request because to do so:
- it needs to lookup user data for '<redacted>' (an offline player) from the database

Performing this lookup on the main server thread would cause your server to lag.
There are two solutions to this problem:
  a) Ask the author of the plugin making the request to perform Vault calls for
     offline players "asynchronously" (using the scheduler). Additionally, prefer
     using the methods that accept 'Player' or 'OfflinePlayer' instead of usernames.
     You should be able to identify the plugin making the request in the trace below.
  b) As a server admin, you can disable this exception by setting 'vault-unsafe-lookups'
     to true in the LuckPerms configuration file. However, please use this only as
     a last resort.

### Reproduction Steps

see above

### Expected Behaviour

Expected lookup of data as the player is ONLINE, not offline as  the message says.

Also the "vault-unsafe-lookups: true" does nothing. It still spits out the message above.

### Server Details

paper-1.19.3-362

### LuckPerms Version

5.4.55

### Logs and Configs

redacted for privacy

**Comment by emilyy-dev** [comment]
It is impossible to diagnose any issue without logs. If you wish to hide player IP addresses, you can use Paper's own `log-player-ip-addresses` setting in the Paper global configuration, or use something like [mclo.gs](https://mclo.gs/) for an existing log file. Otherwise the issue will be deemed invalid and have to be closed.
