### ISSUE TITLE
Release LuckPerms for additional platforms on Modrinth

### ISSUE THREAD

**Issue by Astralchroma** [LuckPerms/LuckPerms#3545]
### Description

LuckPerms for platforms other than Forge and Fabric are not available on Modrinth.

### Proposed Behaviour

As Modrinth now supports platforms such as Bukkit, LuckPerms should provide those releases there as well.

**Comment by Evidentsinger14** [comment]
LuckPerms is on Modrinth with all platforms https://modrinth.com/plugin/luckperms
Thank you @Zoriot for letting us know this could be closed!
