### ISSUE TITLE
Error Appeared

### ISSUE THREAD

**Issue by ZXeon21627** [LuckPerms/LuckPerms#3547]
### Description

Hello.Recently,l met a problem that I even can't start my server!

### Reproduction Steps

I do not know how and in what cases it occurs, even restarted the server several times, it appears by itself.

### Expected Behaviour

I want to get the method that can sove my problem.

### Server Details

Sponge1.19.2

### LuckPerms Version

v5.4.56

### Logs and Configs

https://pastes.dev/fLs2m5MS3p

**Comment by LeotomasMC** [comment]
spongevanilla over paper?

something is preventing luckperms from downloading its required libraries. from just that log its impossible to say exactly what that is, but its likely outside the scope of what LP can control

**Comment by emilyy-dev** [comment]
By "restarted the server", do you mean the computer/physical machine the server runs on?
