### ISSUE TITLE
bedrock players not having a valid uuid 

### ISSUE THREAD

**Issue by NBS-Paste** [LuckPerms/LuckPerms#3548]
### Description

i use geyser and floodgate and it has a . in front of their name so when i tried to add them to a group they dont have a valid uuid so i cant add them to a group.

### Reproduction Steps

do /lp user .Rock_Duck_84 group add all
then it says not a valid uuid

### Expected Behaviour

add player to group

### Server Details

Previous version: git-Paper-349 (MC: 1.19.3)

### LuckPerms Version

not sure

**Comment by Turbotailz** [comment]
Set `allow-invalid-usernames: true` in config.yml
