### ISSUE TITLE
LuckPerms blows up if the MySQL server is unreachable

### ISSUE THREAD

**Issue by Kale-Ko** [LuckPerms/LuckPerms#3551]
### Description

While the Spigot/Paper server is running if the MySQL server is stopped or is otherwise unreachable LuckPerms will blow up and eventually cause the server to crash.

### Reproduction Steps

- Install LuckPerms configured with a MySQL or MariaDB server for data storage on a Spigot/Paper server (I believe this also works on Bungee)
- Start the MySQL/MariaDB server
- Start the Spigot/Paper server and wait for it to boot
- Stop the MySQL/MariaDB server
- Wait

### Expected Behaviour

LuckPerms will wait longer between reconnect attempts every time it fails (0 seconds then 2 then 4 then 8 etc.)

Possibly also display a more user-friendly message when LuckPerms can't connect to the MySQL/MariaDB server

### Server Details

git-Purpur-1882 (MC: 1.19.3)

### LuckPerms Version

v5.4.56

### Logs and Configs

https://gist.github.com/Kale-Ko/71d7e186529268e34c58e09f0c1e2d8b

**Comment by lucko** [comment]
This is expected behaviour, LuckPerms needs a reliable connection to a database to function normally.
