### ISSUE TITLE
"this.database" is null

### ISSUE THREAD

**Issue by Minion9113** [LuckPerms/LuckPerms#3552]
### Description

 [Server] [ERROR] [LuckPerms] Exception occurred whilst loading data for edbdb57a-35bd-4ef1-86ce-833ee6ce576c - Minionbob0808
02.01 01:06:25 [Server] [INFO] java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "me.lucko.luckperms.lib.mongodb.client.MongoDatabase.getCollection(String)" because "this.database" is null
02.01 01:06:25 [Server] [INFO] at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
02.01 01:06:25 [Server] [INFO] at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
02.01 01:06:25 [Server] [INFO] at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
02.01 01:06:25 [Server] [INFO] at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
02.01 01:06:25 [Server] [INFO] at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
02.01 01:06:25 [Server] [INFO] at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1176) ~[?:?]
02.01 01:06:25 [Server] [INFO] at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1647) ~[?:?]
02.01 01:06:25 [Server] [INFO] at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1614) ~[?:?]
02.01 01:06:25 [Server] [INFO] at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
02.01 01:06:25 [Server] [INFO] Caused by: java.lang.NullPointerException: Cannot invoke "me.lucko.luckperms.lib.mongodb.client.MongoDatabase.getCollection(String)" because "this.database" is null
02.01 01:06:25 [Server] [INFO] at me.lucko.luckperms.common.storage.implementation.mongodb.MongoStorage.savePlayerData(MongoStorage.java:548) ~[?:?]
02.01 01:06:25 [Server] [INFO] at me.lucko.luckperms.common.storage.Storage.lambda$savePlayerData$21(Storage.java:269) ~[?:?]
02.01 01:06:25 [Server] [INFO] at me.lucko.luckperms.common.storage.Storage.lambda$future$0(Storage.java:88) ~[?:?]
02.01 01:06:25 [Server] [INFO] at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
02.01 01:06:25 [Server] [INFO] ... 6 more

### Reproduction Steps

i added all things for mongodb and then it said this error

![image](https://user-images.githubusercontent.com/91319585/210189415-e8915709-1533-448f-9328-2a64de8b2570.png)

### Expected Behaviour

that it works?

### Server Details

paper 1.19.3

### LuckPerms Version

5.4.57

**Comment by LeotomasMC** [comment]
you should upload a full log to a paste service such as github gist or pastes.dev

**Comment by Minion9113** [comment]
okay wait one second

**Comment by Minion9113** [comment]
is mcpaste ok? because i can just click a button for it on my host

**Comment by Minion9113** [comment]
@LeotomasMC https://mcpaste.io/0cf28ad76720243a

**Comment by LeotomasMC** [comment]
that is not a *full* log. copy the contents of the latest.log file onto the a paste service

**Comment by Minion9113** [comment]
ah ok

**Comment by Minion9113** [comment]
https://mcpaste.io/55797499032457a0

**Comment by LeotomasMC** [comment]
`java.lang.NumberFormatException: For input string: "//DragonFruitSMP"`
wherever this is in your config, is preventing luckperms from reading the connection string

**Comment by Minion9113** [comment]
i think its the Dragonfruitsmp from the Uri for mongodb

**Comment by Minion9113** [comment]
I got it

**Comment by Minion9113** [comment]
Please write that you need to put the Uri way down and not to Adress
