### ISSUE TITLE
Prematurely reached end of stream

### ISSUE THREAD

**Issue by Minion9113** [LuckPerms/LuckPerms#3554]
### Description

https://mcpaste.io/2e12d731b5b894d3

### Reproduction Steps

1. add mongodb details
2. start server
3. get the error

### Expected Behaviour

that the database works on allservers and not on only 2/3. also all servers habe the same config, but the one is not working...

### Server Details

paper 1.19.3

### LuckPerms Version

5.4.57

**Comment by lucko** [comment]
You have configured mongodb incorrectly.
