### ISSUE TITLE
TimoCloud  is not a depend, softdepend or loadbefore of TimoCloud.

### ISSUE THREAD

**Issue by Nandinius** [LuckPerms/LuckPerms#3556]
### Description

The following warning appears in console:
`[LuckPerms] Loaded class com.sun.jna.Platform from TimoCloud v6.4.3 which is not a depend, softdepend or loadbefore of this plugin.`

### Reproduction Steps

1. Setup TimoCloud
2. Startup server with LuckPerms
3. Observe warning in console

### Expected Behaviour

No warning to appear in console

### Server Details

git-Paper-794 (MC: 1.16.5)

### LuckPerms Version

v5.4.57

**Comment by lucko** [comment]
Please report to TimoCloud, they are incorrectly shading the following class `com.sun.jna.Platform`
