### ISSUE TITLE
[Forge] Player unable to do anything after joining. Also when switching from end to overworld. IllegalStateException Capability missing

### ISSUE THREAD

**Issue by Ve6om** [LuckPerms/LuckPerms#3557]
### Description

[Stacktrace](https://paste.gg/p/anonymous/9eb7a420250f41278e49303a3ad074a5)

Bloodshot @ GriefDefender reports this as a LuckPerms issue.

### Reproduction Steps

Player joins server and stacktrace is printed. Player is then bugged and unable to do things.

### Expected Behaviour

Player should join server and a stacktrace shouldn't be printed.

### Server Details

forge-1.19.2-43.1.57

### LuckPerms Version

LuckPerms-Forge-5.4.58

### Extra Details

Wiping playerdata in world folder along with luckperms data in database fixes issue.

**Comment by Sam-Chai** [comment]
I also have this issue, but not on player's join server, it is the player when come back overworld from end.

**Comment by AnterCreeper** [comment]
I have this issue too, when player come back overworld from end.

**Comment by Ve6om** [comment]
#3584

**Comment by lucko** [comment]
https://github.com/LuckPerms/LuckPerms/commit/ce6031ad52def38e52428d0eb58e2f5b8474408c

Please re-test using LP v5.4.61 -- https://luckperms.net/download

**Comment by Ve6om** [comment]
> [ce6031a](https://github.com/LuckPerms/LuckPerms/commit/ce6031ad52def38e52428d0eb58e2f5b8474408c)
> 
> Please re-test using LP v5.4.61 -- https://luckperms.net/download

Can confirm it fixes the error printed on server. However player is still bugged. Unable to break blocks and chat.

**Comment by AnterCreeper** [comment]
will this patch will be backport to 1.18.2?

**Comment by Ve6om** [comment]
Stacktrace is fixed. However items are now super bugged. Including furnaces, chest, etc. Items will appear in chest, then back to inventory. Items will also straight up not work, axes for example. I also noticed the stacktrace gets printed when using the API to do a permission check. This is all after respawn.
