### ISSUE TITLE
Issues with h2/sqlite databases on 1.19.2 Fabric Server

### ISSUE THREAD

**Issue by TH3N3WN00B** [LuckPerms/LuckPerms#3558]
### Description

I did a server with some friends, so we can play with mods, at the bigining with the server in online mode everything was fine, but when a new offline guy wanted to join and I switched the server from online to offline we couldnt join anymore, tried deleting all luckperms data/folders and still nothing happened, we still couldnt join.

### Reproduction Steps

Install Fabric 1.19.2 with Fabric Loader 0.14.12 and FAPI 0.72.0, Install LP 5.4.58, join server

### Expected Behaviour

Being able to Join the server as usual

### Server Details

Fabric 1.19.2

### LuckPerms Version

v5.4.58

### Logs and Configs

https://gist.github.com/TH3N3WN00B/992a633ed25c40a061f10e907e00c1d5

**Comment by underscore11code** [comment]
The LP error is a symptom of a larger problem, not the actual issue. Somehow players are connecting with no UUIDs, which is completely unsupported and will break literally everything. LP just happened to be the first thing to notice.
