### ISSUE TITLE
Luck Perms & Mekanism Security configuration crash

### ISSUE THREAD

**Issue by JustAnotherGhostName** [LuckPerms/LuckPerms#3563]
### Description

When luckperms is installed, and Mekanism is configured under general.toml in general.security to have allowProtection = true and the opsBypassRestriction = true, the server will crash upon startup. This is currently tested on a ATM8 version 1.0.7 server.

There appears to also be some link to Industrial Forgoing, as the block entity being ticked is a block placer as part of a standard fluid extraction setup, however, nothing about this setup seems abnormal (IE, its not trying to place any mekanism blocks, and the only mekanism thing attached to the block placer is an advanced universal cable.)

### Reproduction Steps

Note that this is only tested on my server, not in single player yet as this is a lower priority issue for me.

1. Startup a new ATM8 1.0.7 server
2. Shutdown to do config changes
3. Add LuckPerms-Forge-5.4.57.jar to the mods folder
4. Configure ./serverFiles/config/Mekanism/general.toml to have allowProtection = true and the opsBypassRestriction = true.
5. Start server back up
6. Crash?

### Expected Behaviour

The server doesn't crash and works just fine.

### Server Details

Forge 32.1.55 on ATM8 1.0.7

### LuckPerms Version

v5.4.57

### Logs and Configs

https://gist.github.com/JustAnotherGhostName/66e2209d8c3fe93288a7f1d4af1e02d8

### Extra Details

Mekanism 10.3.5 (Latest).

Reported to the Mekanism devs, they reported that it is likely a Luckperms issue, not Mekanism issue. 
https://github.com/mekanism/Mekanism/issues/7703

**Comment by LeotomasMC** [comment]
try downgrading to the previous version of LP. the latest version is for 1.19.3 on forge and fabric, but you are running 1.19.2

**Comment by JustAnotherGhostName** [comment]
> try downgrading to the previous version of LP. the latest version is for 1.19.3 on forge and fabric, but you are running 1.19.2

I will try to test that this week on a dev server and let you know the results.
