### ISSUE TITLE
Conflict with Carpet /player command.

### ISSUE THREAD

**Issue by Loyal-Wind** [LuckPerms/LuckPerms#3566]
### Description

When I enter the /player command, server responds:
> {uuid}` - Alex doesn't currently have data pre-loaded - denying login
Chat box prompt:
> An unexpected error occurred trying to execute that command

### Reproduction Steps

I tried to remove LP mod and move back to LP mod.

### Expected Behaviour

After I remove LP mod, carpet mod was able to summon the fake player normally, as expected.
But when move LP mod back to /mods, the message above re-showed in CMD

### Server Details

Fabric 1.16.5

### LuckPerms Version

Fabric-5.3.9

### Extra Details

Carpet mod: 1.4.44+v210714

**Comment by lucko** [comment]
Most likely reason for this is that Carpet isn't firing the correct login/pre-login events for the fake player - not something LuckPerms can fix
