### ISSUE TITLE
Group set permission command node not accessible on Fabric 1.19.3

### ISSUE THREAD

**Issue by ThomasBerne** [LuckPerms/LuckPerms#3569]
### Description

I don't have access to any of the command node implementations and setting unimplemented command doesn't work:

![image](https://user-images.githubusercontent.com/23033483/213859316-c9ea4dca-fcc1-4125-970f-8997df5bee6f.png)

For example:
/lp group default permission set command.ban true

Also the commands doesn't work when set. For example, after the previous command. non-op players couldn't use the ban command.

### Reproduction Steps

I use Fabric 1.19.3 0.14.13
with those mods : 
![image](https://user-images.githubusercontent.com/23033483/213859393-cecbe397-d679-485b-8ec0-6175c73c44c8.png)

You can download the mods here : https://drive.google.com/drive/folders/13gGfyS0gsW3uAc0bId6u8vyqSz-e2aoc?usp=sharing

### Expected Behaviour

I expect like in the Forge server I created earlier to see the commands and set them to different groups

### Server Details

Fabric 1.19.3 0.14.13

### LuckPerms Version

V5.4.57 or v5.4.46 or v5.4.58

### Logs and Configs

Default config and nothing in the logs.

### Extra Details

Only bug on Fabric. It works on Forge.

**Comment by underscore11code** [comment]
Unlike on Forge, Fabric doesn't provide permissions for the vanilla commands by default. Install [this](https://github.com/lucko/minecraft-command-permissions-fabric/releases) to add permissions for vanilla commands. For any other mods, it's up to them to support permissions.

**Comment by ThomasBerne** [comment]
Thanks a lot. Is there something else to add for mods?

**Comment by lucko** [comment]
Nope, you have to ask mod authors to add support
