### ISSUE TITLE
An error occurred when entering the server after loading mod

### ISSUE THREAD

**Issue by yefeng113** [LuckPerms/LuckPerms#3573]
### Description

When I enable this mod, I will display an error when entering the server

### Reproduction Steps

Enable mod
Open Server
Enter the server from the client
error occurred

### Expected Behaviour

Being able to Join the server as usual

### Server Details

fabric0.14.12(MC:1.19.3)

### LuckPerms Version

LuckPerms-Fabric-5.4.57

### Logs and Configs

[17:30:16] [luckperms-worker-5/ERROR]:Exception occurred whilst loading data for null - Maplee_leaf
(提示)java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "<parameter1" is null
(提示)at java.util.concurrent.ConcurrentHashMap.get(Unknown Source) ~[?:?]
(提示)at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.getIfPresent
(提示)(BoundedLocalCache.java:1904) ~[caffeine-2.9.0-remapped.jar:?]
(提示)at me.lucko.luckperms.lib.caffeine.cache.LocalManualCache.getIfPresent
(LocalManualCache.java:57) ~[caffeine-2.9.0-remapped.jar:?]
(提示)at me.lucko.luckperms.common.util.ExpiringSet.contains(ExpiringSet.java:53) ~[%5B权
(提示)限%5DLuckPerms-Fabric-5.4.57.jar:?]
(提示)at me.lucko.luckperms.common.util.ExpiringSet.add(ExpiringSet.java:47) ~[%5B权
(提示)限%5DLuckPerms-Fabric-5.4.57.jar:?]

at me.lucko.luckperms.common.model.manager.user.UserHousekeeper.registerUsage
(提示)(UserHousekeeper.java:58) ~[%5B权限%5DLuckPerms-Fabric-5.4.57.jar:?]
(提示)at me.lucko.luckperms.common.plugin.util.AbstractConnectionListener.loadUser
(提示)(AbstractConnectionListener.java:67) ~[%5B权限%5DLuckPerms-Fabric-5.4.57.jar:?]
(提示)at me.lucko.luckperms.fabric.listeners.FabricConnectionListener.onPreLoginAsync

(FabricConnectionListener.java:98) ~[%5B权限%5DLuckPerms-Fabric-5.4.57.jar:?]
(提示)at me.lucko.luckperms.fabric.listeners.FabricConnectionListener.lambda$onPreLogin$0
(提示)(FabricConnectionListener.java:80) ~[%5B权限%5DLuckPerms-Fabric-5.4.57.jar:?]
(提示)at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
(提示)at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?]
(提示)at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]

at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
(提示)at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]

at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
(提示)at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
(提示)[17:30:16] [luckperms-worker-5/信息]:Disconnecting com.mojang.authlib.GameProfile@37709733
(提示)[id=<null,name=Maplee_leaf,配置={},legacy=false] (/218.89.90.148:3308): [LP] 在加载权限数
(提示)据时发生了一个数据库错误. 请稍后再试. 如果你是服务器管理员, 请检查控制台是否有错误.

[17:30:16] [Server thread/信息]:com.mojang.authlib.GameProfile@37709733
(提示)[id=<null,name=Maplee_leaf,配置={},legacy=false] (/218.89.90.148:3308) lost connection: 
(提示)[LP] 在加载权限数据时发生了一个数据库错误. 请稍后再试. 如果你是服务器管理员, 请检查控制台是否有错
(提示)误.

**Comment by LeotomasMC** [comment]
if you are trying to use a proxy: you have not set it up correctly.
otherwise its most likely because your server is in offline mode, which LP fabric currently does not work with

**Comment by yefeng113** [comment]
> 如果您尝试使用代理：您没有正确设置它。 否则很可能是因为您的服务器处于离线模式，LP 结构目前无法使用

Can I replace the file on the server with the server file that can be used on my computer so that I can use this mod normally

**Comment by LeotomasMC** [comment]
what...?
