### ISSUE TITLE
LuckPerms ignores permissions

### ISSUE THREAD

**Issue by Sitmobedaf** [LuckPerms/LuckPerms#3575]
### Description

- WorldEdit.selection.expand
- WorldEdit.selection.hpos
- WorldEdit.selection.pos
- WorldEdit.wand
- WorldEdit.*:
    value: false
    context:
      world: spawn
While migrating from PEX, I ran into a significant disadvantage of LuckPerms, which ignores more generic permissions. This behavior can be a security risk and the use of seemingly forbidden privileges in certain places.
It looks like I have to set each permission for a separate world?

### Reproduction Steps

/lp user user permission set worldedit.selection.pos
/lp user user permission set worldedit.selection.hpos
/lp user user permission set worldedit.wand
/lp user user permission set worldedit.selection.expand
/lp user user permission set worldedit.* false world=spawn

### Expected Behaviour

The player with these permissions must not have WorldEdit related permissions in the specified world.

### Server Details

Purpur-1.19.3

### LuckPerms Version

v5.4.58

**Comment by lucko** [comment]
This is the intended behaviour, more specific permission (like worldedit.selection.hpos) will take priority over wildcards (like worldedit.*)
