### ISSUE TITLE
"connection marked as broken (...)"

### ISSUE THREAD

**Issue by jonesdevelopment** [LuckPerms/LuckPerms#3578]
### Description

So I went offline and when I came back I had this error message spammed in my console:
https://paste.gg/p/anonymous/41d37819c53b45aa9c2e87d1aefa6d8f

I have no idea why this could happen.
Everything should be set up correctly and I never had any issues before.
I don't know if the error/stacktrace can interfere with the production server but I don't want to risk my player permission data not being saved.

### Reproduction Steps

Leave the server online for a long time?
I don't exactly know what happened since I was offline.
I think the stacktrace is self-explanatory.

No one was online on the server while this happened (it happened at 6:00 AM)

### Expected Behaviour

Do not spam the console with error messages.
I still don't know what this error causes → I hope it does not break permission saving

### Server Details

Current: git-Purpur-1906 (MC: 1.19.3)*

### LuckPerms Version

[LP] Running LuckPerms v5.4.56

### Logs and Configs

https://paste.gg/p/anonymous/41d37819c53b45aa9c2e87d1aefa6d8f

### Extra Details

Does this break something or should I just ignore it?
I already checked the firewall.
The MySQL port is opened and - as I said earlier - it should work totally fine (it worked before).

**Comment by supercoolspy** [comment]
It seems that the database went offline for some amount of time in which luckperms tried checking and failed and therefore shutdown

**Comment by jonesdevelopment** [comment]
Yeah, I know. But why would that randomly happen? I am not saying this has to do with LuckPerms directly but I want to make sure the permission saving is not affected.

**Comment by lucko** [comment]
If LP can't communicate with the database, then it won't be able to save data. There's nothing to fix here, just make sure your database connection is reliable.
