### ISSUE TITLE
Bug with jpremium

### ISSUE THREAD

**Issue by diocan** [LuckPerms/LuckPerms#3579]
### Description

when a new user try to join on the server give an error

14:12:59 [WARNING] [JPremium] Could not verify a player! Error details: Index 1 out of bounds for length 1
14:12:59 [INFO] [LuckPerms] Processing pre-login for 7b8fbeed-8e9d-38e0-bf97-f6e0712e8804 - Giovanni
14:12:59 [INFO] [LuckPerms] Another plugin has cancelled the connection for 7b8fbeed-8e9d-38e0-bf97-f6e0712e8804 - Giovanni. No permissions data will be loaded.
14:12:59 [SEVERE] Exception in thread "pool-4-thread-8" 
14:12:59 [SEVERE]     at com.jakub.premium.d.h.b(Unknown Source)

14:12:59 [SEVERE]     at com.jakub.premium.d.h.a(Unknown Source)

14:12:59 [SEVERE]     at com.jakub.premium.c.a.a.d(Unknown Source)

14:12:59 [SEVERE]     at com.jakub.premium.c.a.a.run(Unknown Source)

14:12:59 [SEVERE]     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)

14:12:59 [SEVERE]     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)

14:12:59 [SEVERE]     at java.base/java.lang.Thread.run(Thread.java:833)

### Reproduction Steps

join with new user and give the error

### Expected Behaviour

14:12:59 [WARNING] [JPremium] Could not verify a player! Error details: Index 1 out of bounds for length 1
14:12:59 [INFO] [LuckPerms] Processing pre-login for 7b8fbeed-8e9d-38e0-bf97-f6e0712e8804 - Giovanni
14:12:59 [INFO] [LuckPerms] Another plugin has cancelled the connection for 7b8fbeed-8e9d-38e0-bf97-f6e0712e8804 - Giovanni. No permissions data will be loaded.
14:12:59 [SEVERE] Exception in thread "pool-4-thread-8" 
14:12:59 [SEVERE]     at com.jakub.premium.d.h.b(Unknown Source)

14:12:59 [SEVERE]     at com.jakub.premium.d.h.a(Unknown Source)

14:12:59 [SEVERE]     at com.jakub.premium.c.a.a.d(Unknown Source)

14:12:59 [SEVERE]     at com.jakub.premium.c.a.a.run(Unknown Source)

14:12:59 [SEVERE]     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)

14:12:59 [SEVERE]     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)

14:12:59 [SEVERE]     at java.base/java.lang.Thread.run(Thread.java:833)

### Server Details

bungeecoord latest

### LuckPerms Version

latest form the site luckyperms.net

**Comment by diocan** [comment]
the problem is not lp or lpb but i have really need help with this bug please help me :crying

**Comment by LeotomasMC** [comment]
if "the problem is not lp" then why did you open an issue in the luckperms github...?

**Comment by diocan** [comment]
i know... but i dont found the jpremium insues page...
anyone can help me  ?
