### ISSUE TITLE
Error migrating db from h2 v1 to h2 v2

### ISSUE THREAD

**Issue by supercoolspy** [LuckPerms/LuckPerms#3581]
### Description

Whenever loading in with 1.19.3 with luckperms I get an error about creating an sql thing in the h2 db however it already seems to exist according to the error so it sends an error

### Reproduction Steps

1. Get an old h2 v1 db with data
2. Try and update it with newest luckperms
3. Start Server

### Expected Behaviour

Either database is migrated or it does not throw an error if the migrating attempt fails

### Server Details

git-Paper-386 (MC: 1.19.3)

### LuckPerms Version

v5.4.60

### Logs and Configs

https://gist.github.com/supercoolspy/dc8a27cf1dda06cf5dc30a494e0d65dd Config
https://gist.github.com/supercoolspy/2196468c79a5313619fab24cc83036dc Error

**Comment by lucko** [comment]
Seems like your old database has corrupted in some way.

Could you try rolling back to the previous LP version, then run `/lp export`, then upgrade again and `/lp import` into a fresh database.
