### ISSUE TITLE
[Forge] Player unable to do anything after dying

### ISSUE THREAD

**Issue by Bennyboy1695** [LuckPerms/LuckPerms#3584]
### Description

When a player dies or runs /kill on themselves they get a missing capability error when respawning which then bugs them out until the server restarts or the players data is deleted.

### Reproduction Steps

Simply die and then see the error

### Expected Behaviour

The capability is able to do stuff when respawning

### Server Details

Forge 1.19.2 43.2.3

### LuckPerms Version

v5.4.46

### Logs and Configs

https://gist.github.com/Bennyboy1695/c84d4df54e69070f8a15b1841b12147a

### Extra Details

This also happens on the latest version made for 1.19.3 but that one also has a missing class error because .2 and.3 have a few class differences

**Comment by Ve6om** [comment]
#3557

**Comment by lucko** [comment]
https://github.com/LuckPerms/LuckPerms/commit/ce6031ad52def38e52428d0eb58e2f5b8474408c

Please re-test using LP v5.4.61

**Comment by Bennyboy1695** [comment]
Still getting the issue with the newest version - https://gist.github.com/Bennyboy1695/f486bfff0b6097e61e8306d08a7b4269

**Comment by powercasgamer** [comment]
> Still getting the issue with the newest version - [gist.github.com/Bennyboy1695/f486bfff0b6097e61e8306d08a7b4269](https://gist.github.com/Bennyboy1695/f486bfff0b6097e61e8306d08a7b4269)

Can you send your **full** log file and send a list of the mods you're using?

**Comment by Bennyboy1695** [comment]
Log: https://mclo.gs/D1vShGV
Modpack: https://www.feed-the-beast.com/modpacks/101-ftb-presents-direwolf20-119 version: 1.3.2
Extra mods are custom mods ShadowCore, ShadowPatcher & ShadowEssentials. Theres also the latest version of the forge griefdefender for patreons
ShadowCore doesnt touch anything to do with lp. 
Shadowessentials gets custom stuff stored in the meta about the player but thats about all and is sopied from the example on the site
ShadowPatcher is a private custom patcher to fix bugs in mods etc with mixins. But none of the current patches touch anything that lp should be touching

**Comment by Ve6om** [comment]
> Log: https://mclo.gs/D1vShGV
> 
> Modpack: https://www.feed-the-beast.com/modpacks/101-ftb-presents-direwolf20-119 version: 1.3.2
> 
> Extra mods are custom mods ShadowCore, ShadowPatcher & ShadowEssentials. Theres also the latest version of the forge griefdefender for patreons
> 
> ShadowCore doesnt touch anything to do with lp. 
> 
> Shadowessentials gets custom stuff stored in the meta about the player but thats about all and is sopied from the example on the site
> 
> ShadowPatcher is a private custom patcher to fix bugs in mods etc with mixins. But none of the current patches touch anything that lp should be touching

Currently experiencing this on Better Minecraft. I don't think it's a mod causing this, as I can't see anything touching player capabilities.

**Comment by AnterCreeper** [comment]
will this patch will be backport to 1.18.2?

**Comment by JustinSchweiger** [comment]
Any news on this? I also have this error and it's quite unfortunate cause it basically makes LP for forge useless
