### ISSUE TITLE
[Essentials] Permissions lag notice with (LuckPermsHandler).

### ISSUE THREAD

**Issue by Nicalion** [LuckPerms/LuckPerms#3586]
### Description

this error comes every time in the console

### Reproduction Steps

the error was on the beginning 
https://i.imgur.com/f4IZMo3.png

### Expected Behaviour

is it because my charakter Owner from server has /op

### Server Details

Paper 1.19.2 B307

### LuckPerms Version

5.4.60

**Comment by lucko** [comment]
Safe to ignore

**Comment by Mastacate** [comment]
> Safe to ignore

Thiss is by far a good answer. There is something causing underlying issues and This OP is not the only person looking for a solve. I as well and so so many other people are searching for the Problem and a Fix. I see many people Using Gm seing it but I also see people getting the same problem on Luckperms b ut the issue we are all having is the Devs are NOT paying attention and trying to solve this issue WITH us and FOR US. WE DONT WANT A ( IGNORE IT ) This is NOT fixing the issue. Some people actually experiance server crashes from this. So i will also ask. What can all of us do to fix this problem we are seeing more and more of?

**Comment by underscore11code** [comment]
This error (almost) always means EssentialsX encountered a tiny bit of lag when trying to fetch data on player login - which is to be expected since LP is still loading that user's data, hence Luck's response that it's safe to ignore.

If you are actually experiencing server crashes that you have logs indicating LP is at fault for, please open a new issue, instead of commenting on a one year old closed issue with no supporting information.

**Comment by Mastacate** [comment]
Okey then please fix the error on your end. This is an error from
luckperms. Not us.

**Comment by emilyy-dev** [comment]
> If you are actually experiencing server crashes that you have logs indicating LP is at fault for, please open a new issue, instead of commenting on a one year old closed issue with no supporting information.

**Comment by Mastacate** [comment]
You dont like me commenting on this? Are you a control freak. You all need to get over yourself and stop being ignorant.

**Comment by Nicalion** [comment]
I am here and will be wait for a good solution
