### ISSUE TITLE
Prefix/Suffix doesn't work

### ISSUE THREAD

**Issue by crifurch** [LuckPerms/LuckPerms#3593]
### Description

In code i didn't found any listeners and methods to add prefix/suffix to player, and as result this feature doesn't work in general.

### Reproduction Steps

- add prefix for default group
- send any message or open tab list(maybe you need any mods to update tab list) 

### Expected Behaviour

I use own mode for chat and tab list, and when i use ServerPlayer.getPrefixes(), i want get non-empty list

### Server Details

Forge 1.18.2(i think for all)

### LuckPerms Version

5.4.26

**Comment by underscore11code** [comment]
Luckperms isn't a chat/tab formatter, it never will modify either of those locations to display meta, nor anywhere else for that matter.

**Comment by crifurch** [comment]
i found answer about that, sorry about that
