### ISSUE TITLE
[Bug] Invalid player data, players cant join

### ISSUE THREAD

**Issue by JustAnotherGhostName** [LuckPerms/LuckPerms#3596]
### Description

Player(s) are unable to join due to "invalid playerdata". At first I could just delete the .pdat file to mitigate it, however, that does not work consistently anymore. Did not originally notice luck perms mentioned in the error, so it took a moment for me to isolate. 

Server is running ATM 8 on 1.0.10, although other versions still had the issue when luckperms is added. 

Issue does not instantly occur, rather, it seems more random and unpredictable. In the sample logs provided, multiple people had it at once, although sometimes its just one player. 

Running on the latest luckperms forge 1.19 build, v5.4.62.

Note:
In the provided logs, there is a different luckperms build. I tried this with a few different versions, and the same error occurs. The current version I am running is the version mentioned above, and the same output occurs, it was just easier to grab this log data instead. 

### Reproduction Steps

Assume data is "bad":
1) Start server
2) Attempt to join server
3) Unable to join, "invalid player data" message is responded back to the client.

### Expected Behaviour

Players could join as normal. 

### Server Details

Forge 43.2.3 (MC: 1.19.2) on ATM8 1.0.10

### LuckPerms Version

v5.4.62

### Logs and Configs

https://gist.github.com/JustAnotherGhostName/fc91185b2084cc268bbb234f366cecbb (latest log)
https://gist.github.com/JustAnotherGhostName/ecd3919bf4602df111bd7b24bd061d00 (debug log)

**Comment by JustAnotherGhostName** [comment]
Issue is not fixed completely, tried most recent update and have been observing it for awhile. No longer thing its random, as it keeps occurring to a specific player currently (has happened to others, but just longer term observation). Found that doing `lp user (player with good data) clone (player with bad data)` resolves the issue temporarily.

**Comment by lucko** [comment]
If it's still a problem with the latest version, please open a new issue with the new errors/logs :)
