### ISSUE TITLE
EssentialsX and Luck Perms permissions not working?

### ISSUE THREAD

**Issue by KyameronKing** [LuckPerms/LuckPerms#3599]
### Description

I am trying to give my members access to /home, /sethome, /delhome, and /hat but after many tutorials, reading, and attempts I cannot get them to work. I had my friend who isn't oped try one of the commands, but no permission. I have gave the default group the permissions and applied changes in-game.. but nothing.

I think I must be doing something wrong! I appreciate the help in advance. 

![image](https://user-images.githubusercontent.com/126936552/222875728-821f8ffd-a7e2-4e2c-9ef9-ba20f9bd6212.png)

### Reproduction Steps

I stopped my server, added the luck perms plugin though FTP on my Apex server, started the server, ran command "lp editor" in my server console and went to the web editor link that was generated, ran trusted editor command I was given from the site in-game, added essentialsx permissions I wanted my default players to have under "default" group, saved and then ran the apply edits command given from the site in-game, asked my friend to test it (didnt work), then i deoped myself and tried it (didn't work). I deleted the plug in all together, and repeated this one more time and even redownloaded LuckPerms before my 2nd attempt.

### Expected Behaviour

My players to have the commands I mentioned.

### Server Details

Apex paper 1.19.3

### LuckPerms Version

Luckperms v5.4.62

### Logs and Configs

n/a

### Extra Details

n/a

**Comment by Aberdeener** [comment]
Hi there,
Can you attach an image of the output of `/plugins` command?

**Comment by KyameronKing** [comment]
> 

Yeah! I am new to github, sorry.

![image](https://user-images.githubusercontent.com/126936552/222876175-c9bbe4a1-f2d3-4eb9-a143-3dc653ff31fc.png)

**Comment by LeotomasMC** [comment]
remove powerranks

**Comment by KyameronKing** [comment]
> remove powerranks

Does power ranks effect it? I figured it was something like that.

**Comment by KyameronKing** [comment]
> remove powerranks also fyi essentials includes a `/invsee` command so you probably dont need 2 additional plugins to open player inventories
I planned on deleting it but ive been side tracked with luckperms haha

**Comment by LeotomasMC** [comment]
powerranks is a permission plugin. you cannot have 2 permission plugins at the same time and expect things to work

**Comment by KyameronKing** [comment]
> powerranks is a permission plugin. you cannot have 2 permission plugins at the same time and expect things to work

Right, I am new to plug ins so of course I didn't know that.. I'll remove it and test it out :)

**Comment by KyameronKing** [comment]
> powerranks is a permission plugin. you cannot have 2 permission plugins at the same time and expect things to work

Thank you for helping, I didnt know Power Ranks were a permission plugin, my members are very picky and throw all types of things at me to install.. but all is fine now! Thank you again :)
