### ISSUE TITLE
group default permission issue

### ISSUE THREAD

**Issue by siulung201314** [LuckPerms/LuckPerms#3600]
### Description

I have removed group.default permission from some players and provide them a new group permission such as group.vip.
After I restart the server, a few of the players still have group.default permission.
Those players have both permissions - group.default and group.vip.
This issue happens randomly on some players.

### Reproduction Steps

1. remove group.default permission from some players
2. add a new group permission for them
3. restart the server
4. use /lp editor to check if any players have both group permission

### Expected Behaviour

The players which have group.vip permission should not have the group.default permission.

### Server Details

git-Purpur-1858 (MC: 1.19.2)

### LuckPerms Version

v5.4.52

**Comment by lucko** [comment]
How are you adding/removing the permissions in your reproduction steps? I can't reproduce using LP commands
