### ISSUE TITLE
Very strange things, the plugin does not give permission.

### ISSUE THREAD

**Issue by Regomy** [LuckPerms/LuckPerms#3602]
### Description

I have no idea how or why, but it didn't happen, and it's not happening now. It happened yesterday, and only once, but it was enough to make a man a fortune.

What's the problem? I have a reward system in DeluxeMenu, when a player has played for 5 minutes they can take that reward, after that they are granted rewarded.1, and they can't take it anymore. But when giving permission, the plugin wrote that it already existed, but in fact it was not. Also, the player bought essentials.msg, which was "issued", but in the morning, comparing the log and the player's rights in /lp user permission info, I realized that the right to the command, which he bought, he did not have. From this I concluded that the problem is in luckperms. Here is my DeluxeMenu file https://paste.md-5.net/velavamuto.bash

### Server Details

This server is running FlamePaper (1.0.2) for 1.8.8 by LinsaFTW

### LuckPerms Version

Running LuckPerms v5.4.64

### Logs and Configs

https://gist.github.com/Regomy/83a1c4bf1689822c0faf21706940cedc

**Comment by F3F5** [comment]
up

**Comment by Regomy** [comment]
@lucko please help me

**Comment by underscore11code** [comment]
These symptoms sound like improper data saving, most likely due to improper shutdown of the server. Can you check shutdown and startup logs for any errors pertaining to LP?

**Comment by Regomy** [comment]
> These symptoms sound like improper data saving, most likely due to improper shutdown of the server. Can you check shutdown and startup logs for any errors pertaining to LP?

Perhaps I would have answered you, but why were others doing well? For example, this player tried from other accounts, but there was no such bug.

**Comment by Regomy** [comment]
Found this in the logs: https://paste.md-5.net/emusarofom.cs
But I don't use bungeecord or velocity. @lucko please helpp

**Comment by Regomy** [comment]
Found this fragment AuthMe kicked out the player, because of the wrong nickname, but luckperms still changed his uuid. https://paste.md-5.net/nulihusicu.cs

**Comment by Regomy** [comment]
In general, the problem is that AuthMe does not let the player with the nickname CAT, if he was registered cat. But luckperms still changes his uuid, and it turns out that if you log in with cat again, the rights will not be given.

**Comment by Regomy** [comment]
> Пожалуйста, прекратите упоминать удачу, это не повлияет на время отклика.
> 
> Автономный режим вызывает массу проблем, особенно с UUID. LP не изменяет UUID (при нормальных обстоятельствах, которые **никогда не** должны быть сделаны каким-либо плагином). В какой-то момент пользователь с заданным именем вошел в систему с помощью UUID онлайн-режима, но теперь подключается к UUID автономного режима. LP теперь запутался и не знает, какого «игрока» модифицировать, так как LP, как и большинство вменяемых плагинов, хранит данные под UUID, а не именами.
> 
> Как и большинство проблем автономного режима, это может быть решено путем переключения обратно в онлайн-режим и отсутствия поддержки пиратства.

Unfortunately, this will not solve the problem, and I will leave 99% of the players, because all play with pirate. Another 1 argument would be the fact that many use luckperms on the pirate, and maybe even with authme, so I hope you will come to your senses, and be able to fix it.

**Comment by Regomy** [comment]
> Please stop mentioning Luck, it won't affect response time.
> 
> Offline mode causes a ton of issues, especially with UUIDs. LP is not changing the UUID (under normal circumstances that should **never** be done by any plugin). At one point a user with a given name logged in with an online mode UUID, but are now connecting with an offline mode UUID. LP's now confused and doesn't know which "player" to modify, since LP, like most sane plugins, stores data under UUIDs, not names.
> 
> Like most offline mode problems, this can be solved by switching back to online mode and not supporting piracy.

Unfortunately, this will not solve the problem, and I will leave 99% of the players, because all play with pirate. Another 1 argument would be the fact that many use luckperms on the pirate, and maybe even with authme, so I hope you will come to your senses, and be able to fix it.

**Comment by emilyy-dev** [comment]
This is not an issue a) from LuckPerms b) LuckPerms can resolve.
LuckPerms is not changing the player UUID, so there is nothing LP can change about that behaviour.

> many use luckperms on the pirate, and maybe even with authme

Yes, that is true, and for many of those, it works fine.

LuckPerms works by identifying players with their UUID, and in offline mode those two usernames correspond to two different IDs, so they are effectively two different players. It does not change a player's username or ID, nor should it have to guess.

**Comment by Regomy** [comment]
> This is not an issue a) from LuckPerms b) LuckPerms can resolve. LuckPerms is not changing the player UUID, so there is nothing LP can change about that behaviour.
> 
> > many use luckperms on the pirate, and maybe even with authme
> 
> Yes, that is true, and for many of those, it works fine.
> 
> LuckPerms works by identifying players with their UUID, and in offline mode those two usernames correspond to two different IDs, so they are effectively two different players. It does not change a player's username or ID, nor should it have to guess.

The problem is in your plugin! In the logs you can see that it RECORDED the uuid of the player, because of the nickname, when authme did not let the player with the "wrong nickname" to the server. 
These are errors, and let's at least look at the logs, as the player nayupala more than 10 yolam, ok, yes! What kind of support that sends on all 4 sides, just wrote that luckperms does not work with uuid. And in the logs what? Magic luckperms from another world?
