### ISSUE TITLE
Unban me in discord

### ISSUE THREAD

**Issue by DaddyRobLIVE** [LuckPerms/LuckPerms#3607]
### Description

Hi, I can't join your discord. I'm sure it was because my account was compromised which made it spam discord invite links to all my private messages and discord servers. My account has been restored for a very long time now so I hope you will allow me to join your discord again for support. Thank you very much.

### Reproduction Steps

Hi, I can't join your discord. I'm sure it was because my account was compromised which made it spam discord invite links to all my private messages and discord servers. My account has been restored for a very long time now so I hope you will allow me to join your discord again for support. Thank you very much.

### Expected Behaviour

Hi, I can't join your discord. I'm sure it was because my account was compromised which made it spam discord invite links to all my private messages and discord servers. My account has been restored for a very long time now so I hope you will allow me to join your discord again for support. Thank you very much.

### Server Details

Latest Paper

### LuckPerms Version

Latest Version

### Extra Details

Please excuse if I'm in the wrong platform, I just don't know how to contact you guys.

**Comment by Turbotailz** [comment]
Please send your discord ID

**Comment by DaddyRobLIVE** [comment]
Daddy Rob #9033
Thank you in advance

**Comment by emilyy-dev** [comment]
Done
