### ISSUE TITLE
Server Level Group and Global Level Group (Group Contexts)

### ISSUE THREAD

**Issue by Manfry0** [LuckPerms/LuckPerms#3609]
### Description

Hello, I have a suggestion for  Luck Perms in a network environment. The idea is to create a system that divides groups into server-level and global-level categories. 

### Proposed Behaviour

To implement this system, you would create specific groups for each server (i.e., prison, bedwars), as well as global groups for staff members, VIPs, and other categories that apply to all servers. These groups would be displayed in the editor, which would allow for easy management and organization based on the server name (such as global, prison, bedwars).

With this approach, the groups will only work on their assigned servers, ensuring that players are given the appropriate permissions and privileges based on their designated server. This would greatly streamline the management of permissions within a network, making it more efficient and less prone to errors.

Overall, this would greatly enhance the functionality of Luck Perms in a network setting, and I believe it would be a valuable addition for any Minecraft server administrator.

**Comment by lucko** [comment]
You can do this already, a short example:

```bash
/lp creategroup moderator

/lp creategroup vip
/lp creategroup vip_prison
/lp creategroup vip_bedwards

# make vip inherit from vip_prison and vip_bedwards on those servers
/lp group vip parent add vip_prison server=prison
/lp group vip parent add vip_bedwards server=bedwars

# add some server specific vip permissions
/lp group vip_prison permission add example.prison.permission
/lp group vip_bedwars permission add example.bedwars.permission

# will have access to all permissions in moderator
/lp user Luck parent add moderator

# will have access to all permissions in vip_prison on the prison server, and all permissions in vip_bedwars on the bedwars server
/lp user Manfry0 parent add vip
```
