### ISSUE TITLE
[LuckPerms] Command execution [editor] has not completed

### ISSUE THREAD

**Issue by SoraGD** [LuckPerms/LuckPerms#3610]
### Description

LuckPerms is not opening the editor with Vault installed

It stopped working randomly, both plugins are up to date

### Reproduction Steps

Install Vault and LuckPerms
Execute the command /lp editor

### Expected Behaviour

The online editor should open

### Server Details

Spigot 1.12.2

### LuckPerms Version

5.4.67

### Logs and Configs

https://gist.github.com/SoraGD/87f8fc8382499b608ffba43eb56e6760

**Comment by emilyy-dev** [comment]
This does not seem to be an issue with LuckPerms, but with EssentialsX trying to retrieve the jail list.
Out of curiosity, do you use the jails feature in Essentials?

**Comment by SoraGD** [comment]
> This does not seem to be an issue with LuckPerms, but with EssentialsX trying to retrieve the jail list. Out of curiosity, do you use the jails feature in Essentials?

I do not use the jails feature, and never used it, but I tried running the command and it apparently stopped working, not issuing any more commands after that one

**Comment by mdcfe** [comment]
Hey, you're running a very *very* old version of EssentialsX (around 2-3 years old). Could you try updating EssentialsX?

**Comment by SoraGD** [comment]
> Hey, you're running a very _very_ old version of EssentialsX (around 2-3 years old). Could you try updating EssentialsX?

Updating fixed it, thanks!
