### ISSUE TITLE
Permissions are not gives

### ISSUE THREAD

**Issue by Lemar98** [LuckPerms/LuckPerms#3611]
### Description

First, I issue a list of permissions to the player using the api, then I take it with /lp user <nick> permission unset <permission>, and then again I try to issue the permissions using the api, but they are issued randomly: some permissions are issued, and some then no.

### Reproduction Steps

1. Give permissions using my code (https://pastebin.com/4s99j54H)
2. Take them with the LuckPerms team
3. Try to give permissions again using my code.
4. When doing "/lp user <your_nickname> permission info" you will not see all the permissions that should have been issued

### Expected Behaviour

Permissions should be given normally

### Server Details

git-Purpur-1171 (MC: 1.16.5)

### LuckPerms Version

v5.4.62

### Logs and Configs

lp config: https://pastebin.com/cSYj5zvJ

### Extra Details

Please note that my code may work fine, but sometimes it breaks. For example if you give yourself permissions ("/tst give <nick>"), try to take some of them with "/lp user <nick> permission unset <given perm>", then take the rest with "/tst take <nick>" and try to give yourself permissions again "/tst give <nick>", the plugin will not give you all rights or give them randomly

**Comment by underscore11code** [comment]
Could we get your code please.

**Comment by Lemar98** [comment]
https://pastebin.com/4s99j54H

**Comment by lucko** [comment]
Your code looks fine, might be worth adding some logging.
