### ISSUE TITLE
Adding permission-level as a context

### ISSUE THREAD

**Issue by CJDennisT** [LuckPerms/LuckPerms#3612]
### Description

Hello! 
It would be awesome if we could use permission levels or operator status as a context for permissions. 

### Proposed Behaviour

The plugin could grab the current permission level or operator status of a player, or listen for a permission level change on the server, and can be used for context.

**Comment by LeotomasMC** [comment]
while luckperms *setting* op level may be useful for environments that havent fully moved over to permissions, having op level be a luckperms context, which is what the OP appears to be requesting, doesnt really make sense to me.

**Comment by LeotomasMC** [comment]
i dont really see how op level has anything to do with this example you provided

**Comment by CJDennisT** [comment]
I was trying to use permission levels as the context for applying the bypass but instead I can change gamemodes and use that as the context. I didn't realise this until I read why operator shouldn't be used to begin with.
