### ISSUE TITLE
Latest direct link

### ISSUE THREAD

**Issue by capsload2** [LuckPerms/LuckPerms#3613]
### Description

Hey,

is there any way to have a direct DL link available without the version number?
That would be great for my latest update script.

https://download.luckperms.net/1478/bukkit/loader/LuckPerms-Bukkit-5.4.67.jar

should be

https://download.luckperms.net/1478/bukkit/loader/LuckPerms-Bukkit-latest.jar

Thanks :)

### Proposed Behaviour

Hey,

is there any way to have a direct DL link available without the version number?
That would be great for my latest update script.

https://download.luckperms.net/1478/bukkit/loader/LuckPerms-Bukkit-5.4.67.jar

should be

https://download.luckperms.net/1478/bukkit/loader/LuckPerms-Bukkit-latest.jar

Thanks :)

**Comment by powercasgamer** [comment]
No, use the [metadata api](https://github.com/LuckPerms/metadata-api#get-datadownloads)
