### ISSUE TITLE
Will LuckPerm work with Folia?

### ISSUE THREAD

**Issue by MineSunshineone** [LuckPerms/LuckPerms#3614]
### Description

Considering paper's new project Folia, and the popularity of the Luckperm project, I thought it would be great to make an adaptation for Folia!

### Proposed Behaviour

Add Folia-Supported

**Comment by powercasgamer** [comment]
There's already a branch for Folia support that is a work in progress. https://github.com/LuckPerms/LuckPerms/tree/feat/folia

**Comment by BleesTFE** [comment]
Hello, sorry for reopening. Has Folia support been cancelled? Currently, Folia has no command permissions management plugin available, making multiplayer servers very limited.

**Comment by BNTFryingPan** [comment]
see the linked pr and/or branch. folia is not "released" yet, so there isnt much point in making a real luckperms release for folia either

**Comment by MotyaDev** [comment]
https://ci.lucko.me/job/LuckPerms-Folia/

this is working artifacts
