### ISSUE TITLE
Strange elimination of ranks and permissions

### ISSUE THREAD

**Issue by iJosePlay** [LuckPerms/LuckPerms#3619]
### Description

Hi, so the server was having its daily restart cycle every 24 hours as it does every day and I don't know what went wrong today, but LuckPerms just didn't recognize the server database.

### Reproduction Steps

It seems that the database simply crashed after the daily server restart. Although it is strange because other times this did not happen.

### Expected Behaviour

-

### Server Details

ShieldSpigot (MC: 1.8.8)

### LuckPerms Version

v5.4.40

### Logs and Configs

luckperms-h2.trace.db: https://gist.github.com/iJosePlay/7f1e0daf92a5fc2d291980f7d01a8275

**Comment by underscore11code** [comment]
> File is locked

Looks like another process is currently using the file, usually meaning you've got multiple instances of the server running. This **will** cause problems, find the rogue process and kill it.
