### ISSUE TITLE
LuckPerms & Essentials error

### ISSUE THREAD

**Issue by DonKips** [LuckPerms/LuckPerms#3620]
### Description

I get an error from LuckPerms when the plugin tries to get the user state from Essentials

### Reproduction Steps

Have Essentials and LuckPerms on the server, log in with a new account and look at the console 

### Expected Behaviour

LuckPerms should handle the player after essentials

### Server Details

git-Purpur-1171 (MC: 1.16.5)

### LuckPerms Version

v5.4.71

### Logs and Configs

https://pastebin.com/pHjfcrEb

**Comment by LeotomasMC** [comment]
this looks like either an issue with eesx or supervanish.

fyi essx has a vanish feature so you shouldnt need a dedicated vanish plugin

**Comment by underscore11code** [comment]
Skimming the EssX code, it appears EssX is not ensuring a user is fully loaded before attempting to access it to determine applicable contexts. LP has no control over this. Please report to EssentialsX.
