### ISSUE TITLE
I instald it but i cant use it it say its instald but i cant se it whit /plugins minehut

### ISSUE THREAD

**Issue by lule25453** [LuckPerms/LuckPerms#3627]
### Description

Its buged

### Reproduction Steps

idk

### Expected Behaviour

Dat it show up not red and i can do /Lp

### Server Details

papper 1.19.4

### LuckPerms Version

v5.4.40

**Comment by LeotomasMC** [comment]
Please download the latest version and try again. If it still does not work, use a [pastebin](https://pastes.dev) to send a **full** log.
