### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by DiamondMan0007** [LuckPerms/LuckPerms#3628]
### Description

A notes section in the web editor for future usage.

### Proposed Behaviour

I often find myself having permission i forget what they do, or they look super similar to other permissions. For instance, I have a permission called 'spawn.bypass' for cooldown bypass, and I've looked it up multiple times mistaking it for something else. I think it would be cool to see a notes section in atleast the web editor (though if you figure out how to implement it into Minecraft thats even better), obviously though it would need to save to the Server Files to be accessed later by the web editor(though if im wrong please correct me). My idea was that it could fit in the giant empty space next to the basic group info at the top, or if you wanted to allow per permission notes it would look something like the Value column but would be a typing space for notes. I'm open to different implementation options and would be grateful for your thoughts on this. Thank you for considering my suggestion.

**Comment by DiamondMan0007** [comment]
I created 2 groups in which im currently organizing all the possible permissions into 2 catagories, User and Admin perms, and whether or not I'd even consider giving that perm to that respective group, this way i can refer to it later if i want to see all possible perms in a later configuration

**Comment by lucko** [comment]
Hi, nice idea, unfortunately it's quite a lot of work to add as it would need to be stored in the database (for all storage types). Realistically not something I have time to work on at the moment, other features are higher up the list!
