### ISSUE TITLE
Provide a permalink for every platform latest release

### ISSUE THREAD

**Issue by JAHMCR** [LuckPerms/LuckPerms#3630]
### Description

Hey!

It'd be really nice to have a permalink for every platform latest release.

I currently auto-update every plugin on my servers on every restart, so I wanted to do the same with LuckPerms.

### Proposed Behaviour

The permalinks could look like this:

https://download.luckperms.net/bukkit/LuckPerms.jar
https://download.luckperms.net/velocity/LuckPerms.jar

And so on

**Comment by emilyy-dev** [comment]
Use the [metadata API](https://github.com/LuckPerms/metadata-api#get-datadownloads) to get a link to the latest build.

**Comment by JAHMCR** [comment]
Thanks, didn't know about that API

**Comment by Turbotailz** [comment]
Auto updating plugins is not a very good idea. But I'm sure you are aware of the risks.
