### ISSUE TITLE
ClassNotFoundException, I can't use LuckpermsProvider.

### ISSUE THREAD

**Issue by Sandro642** [LuckPerms/LuckPerms#3632]
### Description

Good morning.

I can't use the Luckperms API. When I use the API and go to my server, I get an error in the console telling me that the LuckpermsProvider class was not found.

Sincerely Sandro

### Reproduction Steps

LuckPerms api = LuckPermsProvider.get();

### Expected Behaviour

Error ClassNotFoundException

### Server Details

Server :Spigot 1.12.2, Client : 1.12.2

### LuckPerms Version

v5.4

### Logs and Configs

https://gist.github.com/Sandro642/bb3b481bd59d98e1a9c3c962b9e19d5d

**Comment by underscore11code** [comment]
Please ensure that LP is installed, and you've declared in your plugin.yml that you depend on LP so it loads before you.
