### ISSUE TITLE
UUID error

### ISSUE THREAD

**Issue by NewPixelDev** [LuckPerms/LuckPerms#3633]
### Description

When running, it will often report UUID errors
But I have not modified the player's UUID
And Luckperms is a separate database and other plugins are not in the same database at all

### Reproduction Steps

I don't know how to reproduce
because the question is random

### Expected Behaviour

Luckperms will constantly report player UUID errors on the console
Causing the server to freeze and causing some of my players to collectively disconnect

### Server Details

waterfall-1.19-526

### LuckPerms Version

V5.4.71

### Logs and Configs

https://gist.github.com/NewPixelDev/2b88e5719665707c97f10febd5487126

### Extra Details

Luckperms often reports UUID errors
Luckperms is a separate database and not together with other plugin data
Once this error is reported, it will cause the server to freeze and cause some players to go offline
I have tried many different versions and have not been able to solve this problem

**Comment by LeotomasMC** [comment]
you have not shared enough information to determine what the problem is. is your server in offline mode? what plugins do you have?

**Comment by NewPixelDev** [comment]
> you have not shared enough information to determine what the problem is. is your server in offline mode? what plugins do you have?
Yes, my server is in offline mode
my plugin: 
![image](https://user-images.githubusercontent.com/129480648/234023627-ed413e73-d1d4-4977-b7b4-772a0acf075c.png)
I checked but there are no plugins that maliciously modify UUID

**Comment by NewPixelDev** [comment]
Can anyone solve this problem?

**Comment by lucko** [comment]
>  I checked but there are no plugins that maliciously modify UUID

I doubt it

**Comment by NewPixelDev** [comment]
> > I checked but there are no plugins that maliciously modify UUID
> 
> I doubt it, try again with the server running in online mode

Can only be solved through 'online mode'?

**Comment by NewPixelDev** [comment]
> > I checked but there are no plugins that maliciously modify UUID
> 
> I doubt it, try again with the server running in online mode

please reply me thank you
