### ISSUE TITLE
 Thread luckperms-worker-# threw an uncaught exception

### ISSUE THREAD

**Issue by Teddy20002** [LuckPerms/LuckPerms#3634]
### Description

leave the server running and you should get this error https://pastebin.com/tVDCyBTb

### Reproduction Steps

I have 130 plugins and left the server running and it shows up in console. So i don't know how to reproduce this.

### Expected Behaviour

https://pastebin.com/tVDCyBTb

### Server Details

Paper 307 1.19.2

### LuckPerms Version

5.4.71

**Comment by emilyy-dev** [comment]
This is usually a symptom of running `/reload` or hot-reloading the plugin with plugman or alike, have you done any of those things before getting this error? Please share the whole log file containing the error
