### ISSUE TITLE
Players getting the default group

### ISSUE THREAD

**Issue by sumsar1812** [LuckPerms/LuckPerms#3636]
### Description

I recently updated from v4 to v5 and afterwards i started seeing some players getting group.default. 
The players that are getting it is ones that already have `group.default` thru a parrent group.

The player has a group called `extra`, which has a parrent group called `a` and the `a` group has the group `group.default.`
It only happens to users that have `group.extra`.

I tried to add group.default to` group.extra ` but it didn't change anything.

When we manually remove the permission it seems to get added right away, not sure how long it takes but might first be after the server has rebootet(does so every night)

### Reproduction Steps

I think i described it above

### Expected Behaviour

The group is not added as a personal permission

### Server Details

paperspigot188, 3 servers syncing perms

### LuckPerms Version

5.4.40

**Comment by lucko** [comment]
Players need to have at least one group in the global context, if they don't LuckPerms will automatically add them to default.
