### ISSUE TITLE
Luckperms Fabric 1.19.3

### ISSUE THREAD

**Issue by AvatarMental** [LuckPerms/LuckPerms#3638]
### Description

Group getting permissions they should not have, even when specifically denying said permissions

### Reproduction Steps

Give player the following permissions:
`luckperms.user.promote`
`luckperms.user.promote.pvp`
`luckperms.user.promote.pvp.*`
And denying the following permissions:
`luckperms.user.promote.staff`
`luckperms.user.promote.staff.*`

### Expected Behaviour

According the wiki, this should allow the player to promote in the pvp track, but not in the staff track. However they can promote in any track as soon as `luckperms.user.promote` is given as a permissions.

### Server Details

Fabric 1.19.3

### LuckPerms Version

v5.4.60

**Comment by LeotomasMC** [comment]
did you enable argument based command permissions in the luckperms config?

**Comment by AvatarMental** [comment]
This was not enabled yesterday, but has been enabled today. Still same issue.

**Comment by lucko** [comment]
Check using the verbose command to debug.
