### ISSUE TITLE
Maybe too much database requests

### ISSUE THREAD

**Issue by WarnDa** [LuckPerms/LuckPerms#3639]
### Description

I'm running luckperms v5.4.71 with ~160 players on 1.19.3 with mysql
And I checked mysql requests, luckperms does a lot of requests to it, so I'm not sure it's normal
(I tried to reduce my iowait, as even with a 13900k and a samsung nvme 980 pro, I got up to 3% iowait, mainly from mysql)

Here are the requests : 
![image](https://user-images.githubusercontent.com/31826333/235300456-e07db718-5891-4894-8a07-a5dad757bf89.png)

Also "luckperms_messenger" is used for what is I got only a single server ?

### Reproduction Steps

- use luckperms at (high) player count

### Expected Behaviour

Maybe the number of requests should be lowered

### Details

LuckPerms version  : 5.4.71
Server version : Pufferfishplus-44 1.19.3
Only one server under mysql, on localhost
![image](https://user-images.githubusercontent.com/31826333/235300448-eece2965-168e-4e0c-8526-2290d38c7e8b.png)

### Extra Details
Someone told on discord : 
> luckperms shouldnt be making a request to the database every time a permission is checked
when a player joins, it loads their data from storage, and then permission checks are done against what it loaded

So that's why I open this issue

### Spark
Here is a spark with Luckperms (took 2 days ago until I update my luckperms version) that was taking a lot, I don't think it helps as it might plugins requesting too much permissions (I fixed antiAC that took 0.08%)
![image](https://user-images.githubusercontent.com/31826333/235300596-59a094af-e31d-4120-b9f5-e3aa94f7f624.png)

**Comment by lucko** [comment]
If you only have a single server connected to the database, you can set:

```yml
messaging-service: notsql
```

 in your config.yml to disable the messaging service.

Happy to look into the spark but you need to send the link, not screenshots :)

**Comment by WarnDa** [comment]
I had
> messaging-service: none

So it was "disabled" in the config
And here are the sparks : https://spark.lucko.me/m3EsB6pXbh
https://spark.lucko.me/B5Pjggc3Q4

**Comment by WarnDa** [comment]
![image](https://user-images.githubusercontent.com/31826333/235348795-e01c0650-402a-4320-ae0e-ae1d3665eb00.png)
Here is with messaging-service: notsql
I didn't restart server but used /lp reloadconfig

**Comment by lucko** [comment]
You'll need to restart the server to have the config change take effect (that property is not reloadable :P)
