### ISSUE TITLE
LuckPerms and Vault Hunters 3rd Edition - Missing Capability Exception

### ISSUE THREAD

**Issue by JustinSchweiger** [LuckPerms/LuckPerms#3640]
### Description

Hello there,

Vault Hunters 3rd Edition is a 1.18.2 Modpack but all of the Forge LP Versions throw a "Missing Capability" exception when you die and click the respawn button.

Using a Hybrid server would technically work. Practically hybrids arent feasible for VH since they break quite a few game mechanics since VH is so custom.

### Reproduction Steps

- Install VH on a server.
- Install LP and any mod that uses the LP API
- Die and press respawn

### Expected Behaviour

Player Caps not breaking after you die

### Server Details

Any Forge VH Server

### LuckPerms Version

v5.4.26

### Logs and Configs

https://mcpaste.io/dfb9b37eeaaf3c22

**Comment by JustinSchweiger** [comment]
I know there has been a Commit (62f2fc9714d4fe3227d1037f2ed951db914a5838) to address this issue but there isnt any new LP version with the fix on any of the available download platform so if anyone could publish a new one I would be happy to test it.

**Comment by martijnpu** [comment]
All external download platform receive an update once in a while.

The latest verion of LuckPerms can always be found on the site. [https://luckperms.net/download](https://luckperms.net/download). This version includes the commit you meantion that would fix your issue.

**Comment by JustinSchweiger** [comment]
Probably does yea ... the problem is that Forge doesnt really have Version Intercompatibility but the versions on the official luckperms page is always the most recent one being 1.19.4 right now which doesnt work for 1.18.2
