### ISSUE TITLE
API

### ISSUE THREAD

**Issue by fran201921** [LuckPerms/LuckPerms#3645]
### Description

I suggest being able to make an api that with "GET" methods can obtain the information of a person or player such as their group or permissions to be able to make discord bots ect for easier sync ect (Make it a configurable option and that you can put the port to choice). I think it's a good idea for developers

### Proposed Behaviour

I would do a "GET" method to a specific url and I would receive some information in json format for example
{"fran2019":{"group":"owner"}"}
or something similar
and the url is
http://ip:port/luckperms/api/users/(user)

### Extra Details

And I think that if the option of adding a token to the "API" could be added separately to make it more secure to consult

**Comment by emilyy-dev** [comment]
See [rest-api](https://github.com/LuckPerms/rest-api)

**Comment by fran201921** [comment]
how i can use it?

**Comment by emilyy-dev** [comment]
Check out the project readme as well as the [openapi spec](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/LuckPerms/rest-api/main/src/main/resources/luckperms-openapi.yml)

**Comment by fran201921** [comment]
ok ty
