### ISSUE TITLE
Luckperms is triggering permissions for plugins on join

### ISSUE THREAD

**Issue by Enderko** [LuckPerms/LuckPerms#3649]
### Description

On every join my server freezes for 2 seconds and my tps drops of course.
I have some type of Connection Handler lag shown on timings.
But on spark you can see that there's a permission check that triggers viaversion.
I think I have issue with luckperms, luckperms is triggering ViaVersion permission check on join.
Is anyone able to help me with this?
https://spark.lucko.me/R4mrSPNHUI

### Reproduction Steps

no particular step

### Expected Behaviour

no particular behavior

### Server Details

git-Pufferfish-57 (MC: 1.19.3)

### LuckPerms Version

v5.4.46

**Comment by emilyy-dev** [comment]
If you're still suffering from this issue please upload a new spark profile report! That one seems to have expired
