### ISSUE TITLE
Bedrock Player @player issue

### ISSUE THREAD

**Issue by jbreadtoasted** [LuckPerms/LuckPerms#3651]
### Description

I have a command when players go through a portal to each wordl they get something like lp user @player parent add membersv world=world
However it works for my java players but is not working for the bedrock players even though i have set the 

# If LuckPerms should allow usernames with non alphanumeric characters.
#
# - Note that due to the design of the storage implementation, usernames must still be 16 characters
#   or less.
allow-invalid-usernames: false

But it isnt giving my players from bedrock the permissions and group updates its giving it to them but not actually cause its not working even though it says on bedrock it gave the inheritants still not working.

### Reproduction Steps

using lp user @player add parent membersv world=world
not giving the inheritants to bedrock players i have to manually do it because of the .

### Expected Behaviour

Want it to give inheritance like it does with my java players

### Server Details

paper mc 1.19.4

### LuckPerms Version

5.4.40

**Comment by underscore11code** [comment]
Allow invalid usernames must be set to true to...allow invalid usernames.

**Comment by jbreadtoasted** [comment]
ok let me try that


> Allow invalid usernames must be set to true to...allow invalid usernames.

**Comment by jbreadtoasted** [comment]
So i just remembered it is actually already set to true that was just a copy paste from the internet my bad but yes i have it already set to true but its not working

**Comment by jbreadtoasted** [comment]
I explained it in a way that mentions when using the @player it isnt calling the .bedrockusername like its literally not giving the perms but when @player is used on a java player the command works just fine however when i manually do /lp user .playersname directly it works but the @player isnt using this function it seems like even with the setting to true and yes its been restarted many times cause im working on various plugins, It does in fact run the command but does not give them the inheritance like i explained
