### ISSUE TITLE
Waterfall crashes on start (attempt to cast an ArrayList to a Map in the config parser?)

### ISSUE THREAD

**Issue by TheManchineel** [LuckPerms/LuckPerms#3652]
### Description

Trying to set up LuckPerms (Bungee) as usual. I have no existing configuration on this proxy. Every time I get the following error:

```
Exception in thread "main" java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class java.util.Map (java.util.ArrayList and java.util.Map are in module java.base of loader 'bootstrap')
```

### Reproduction Steps

1. Download the latest version of Waterfall (1.19)
2. Download the latest version of LuckPerms Bungee
3. Install the plugin
4. Launch the server

### Expected Behaviour

The server works (?)

### Server Details

git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526

### LuckPerms Version

v5.4.79

### Logs and Configs

https://gist.github.com/TheManchineel/1a7dfb336763874548d46af95abfa165

### Extra Details

Java version 17 (also tested on Java 11, same error)

**Comment by powercasgamer** [comment]
Waterfall issue, not related to LuckPerms
