### ISSUE TITLE
LuckPerms adding users to groups on its own

### ISSUE THREAD

**Issue by destial** [LuckPerms/LuckPerms#3653]
### Description

Whenever I add a user to a group with context or temporary, after a while, when I check their parent group, they have the global group without the context or expiration.
This is the groups I had before.
![image](https://user-images.githubusercontent.com/67675805/236998376-0ddd4ead-02da-4710-8708-0f280c2378a1.png)

This is after when I wake up in the morning to check.
![image](https://user-images.githubusercontent.com/67675805/236998287-b98758b1-cbdf-4e57-b69f-da4a253d2616.png)

You can see I added a temporary Exarch group but by the time I wake up, I also have the full Exarch group without the expiration. This also happens for context groups.
![image](https://user-images.githubusercontent.com/67675805/237000508-c01b0b14-99b6-47dc-ad8b-75ca37cb7a96.png)
You can see he has the context builder group but I never added the full builder group.

### Reproduction Steps

1. All your servers to the same mariadb database and table.

2. Enable split-storage and set user to mariadb.

3. Add a temporary group / context group to yourself.

4. Wait a while and check your groups again and you will see that you have the context/temp group and the full group applied.

### Expected Behaviour

The expected behaviour is that LuckPerms would keep the same context group and not add the full group.

### Server Details

git-Pufferfish-68 (MC: 1.19.4)

### LuckPerms Version

v5.4.77

### Extra Details

I am using MariaDB for all of my servers, using the same database and table. I have split-storage enabled, with user being stored in mariadb and the rest in h2. I have tried using 2 separate MariaDB database on 2 separate machines, they both worked, gave no errors, but they both had the same issue.

**Comment by destial** [comment]
I forgot to clarify the images, I took the images when I woke up in the morning so I removed the group after I took the resulting screenshot, but it is essentially the same.

**Comment by destial** [comment]
![image](https://user-images.githubusercontent.com/67675805/237023128-902aaf04-4d55-4c10-982d-5ef1aafd0024.png)
I left and rejoin after 2 hours and I got the full group again

**Comment by ComicIvans** [comment]
I'm facing the same issue

**Comment by ComicIvans** [comment]
I did create a dummy group and assign that to the user, but if the user enters and leaves the server wile having the temporary group, when it should expire, it becomes permanent:
![image](https://github.com/LuckPerms/LuckPerms/assets/83135925/a8a27dee-a412-49a3-931b-acd3f9ea4457)

**Comment by BNTFryingPan** [comment]
![image](https://github.com/LuckPerms/LuckPerms/assets/7706960/beb86882-5761-4cd3-bba0-c1748dcfee8a)
your temporary node is expiring just fine. you just also have a permanent group node as well that wont expire

**Comment by ComicIvans** [comment]
> ![image](https://private-user-images.githubusercontent.com/7706960/293292007-beb86882-5761-4cd3-bba0-c1748dcfee8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM4MTIxOTIsIm5iZiI6MTcwMzgxMTg5MiwicGF0aCI6Ii83NzA2OTYwLzI5MzI5MjAwNy1iZWI4Njg4Mi01NzYxLTRjZDMtYmJhMC1jMTc0OGRjZmVlOGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjlUMDEwNDUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDg5MTdlYmViZTExZmVmOGFmMWU0MTUzZDkxMGFlMjM1NTgwNjAyMzk3NTRiZjZlMWI4MWJkM2I5N2MwZjQ3ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lVG0rRfXaNLDlrE32BkQQOT_cusfWdZuUlCmuQzTI28) your temporary node is expiring just fine. you just also have a permanent group node as well that wont expire

The thing is I never set that permanent group node to the player, I just ran `lp user ivic_sans parent set fix` and then `lp user ivic_sans parent addtemp adepto 600s accumulate`.

**Comment by BNTFryingPan** [comment]
then show that user having neither a perm node or a temp node, you running *just* the parent addtemp command, and then them having both the perm and temp nodes

**Comment by ComicIvans** [comment]
First, deleted the user from the database:
![image](https://github.com/LuckPerms/LuckPerms/assets/83135925/21e2796a-fed9-4b4e-90cb-d8ed779f2a68)

Then, user joins and I run `lp user ivic_sans parent set fix` and `lp user ivic_sans parent addtemp adepto 300s accumulate`:
![image](https://github.com/LuckPerms/LuckPerms/assets/83135925/7ff18d67-43ba-4d5b-b3ec-c0e68bcbd9c2)

It expires without problem. However, if I do it a second time, running `lp user ivic_sans parent set fix`, then `lp user ivic_sans parent addtemp adepto 60s accumulate` and the user joins and leaves within the 60 seconds, it gets the perm node:
![image](https://github.com/LuckPerms/LuckPerms/assets/83135925/ffa92c9b-b8b9-49fd-aba3-4923e9f9696e)
