### ISSUE TITLE
MongoDB Exception authenticating MongoCredential

### ISSUE THREAD

**Issue by FierraCodes** [LuckPerms/LuckPerms#3656]
### Description

Luckperms having issues to authenciate with MongoDB, Throwing `Exception authenticating MongoCredential` and `Authentication failed.' on server ac-4ambohl-shard-00-01.2xhehw2.mongodb.net:27017. The full response is {"ok": 0, "errmsg": "bad auth : Authentication failed.", "code": 8000, "codeName": "AtlasError"}`

### Reproduction Steps

1. Set Up MongoDB On Luckperms
2. Start Server
3. Error

### Expected Behaviour

Authenticate Normally & Successfully

### Server Details

Velocity-3.2.0 & Paper git-Paper-538

### LuckPerms Version

v5.4.79

### Logs and Configs

All Logs & Configs:
https://gist.github.com/FierraCodes/4ef61f84f6f2abe1da24656c7802b279

### Extra Details

I made a new user on MongoDB specially for LuckPerms, used to work but doesn't work now. Permissions are read & write to all DBs

**Comment by Dominik48N** [comment]
Unfortunately I cannot reproduce the error. Have you ever considered that it's not because of LuckPerms but because of the database?

**Comment by FierraCodes** [comment]
It worked previously without any error, but after reinstalling luckperms it just doesnt work.

**Comment by Dominik48N** [comment]
What version did you use before that made it work?

**Comment by FierraCodes** [comment]
I have no idea, cause it was sort of a long time ago and i didn't back it up (server data, not databse)

**Comment by Dominik48N** [comment]
The last real change to the MongoDB storage implementation that I can understand here is from early 2022. If you were previously using a reasonably up-to-date version of LuckPerms, then it seems to me at first that there is a problem with the database.

As I can see, you didn't specify an authentication database in your connection string either. Depending on how MongoDB is configured, you might need this.

**Comment by FierraCodes** [comment]
May I ask how to do that? Because I don't see an option for that (im using a free cluster)

**Comment by Dominik48N** [comment]
It's hard to tell which source authenticates your user if your host doesn't let you know. I would just ask if I were you.
Does the connection to the database work via Studio3T or MongoDB Compass on your computer?

**Comment by FierraCodes** [comment]
Yep, after remaking the users. But luckperms side still doesnt work

**Comment by Dominik48N** [comment]
I just set up a brand new server with only LuckPerms on it. In addition, I created a new MongoDB database server and with this configuration I have no problems in version 5.4.82.

https://gist.github.com/Dominik48N/fbb0476495d5997bb34e2c12ec2b0779
![image](https://github.com/LuckPerms/LuckPerms/assets/46966988/d9c76b6d-5136-41dd-a920-9a46bfd27997)

**Comment by Dominik48N** [comment]
As I said, I can't reproduce the error. It really seems to me that the problem is with your database server right now. Maybe try to set up the MongoDB database on another server or look for another managed solution to try it out. I tried it with fresh MongoDB and LuckPerms on 1.19.4 and I have no problems.

**Comment by FierraCodes** [comment]
Fixed, its just me being stupid and accidentally blocking the connection with the firewall
