### ISSUE TITLE
Question: about Username or UUID of Banner Hybrid Server

### ISSUE THREAD

**Issue by 8MiYile** [LuckPerms/LuckPerms#3657]
### Description

I am using a Fabric with Bukkit running in one world at the same time
I run the Luckperms plugin in the Bukkit environment
However, under Luckperms, I can't find my name, only by UUID, but it shows unknown name, i.e. permission is not valid

### Reproduction Steps

1. install fabric server(include MC 1.19.4 & Fabric-API latest)
2. install Banner to fabric's `mods` folder [ExtraLink](https://github.com/MohistMC/Banner) [CI Build](https://ci.codemc.io/job/MohistMC/job/Banner/)
3. install Luckperms-Bukkit in `plugins` folder
4. Run and test `/lp user <user_id> info`, you can get `Not Found <user_id>`
5. if command is `/lp user <user_uuid> info`, you can get user info, but Username is Unknown

### Expected Behaviour

Not more

### Server Details

Bukkit Layer: Banner version 214 (MC: 1.19.4)
Fabric Layer: fabricloader 0.14.19 + fabric-api 0.80.0+1.19.4

### LuckPerms Version

v5.4.79-bukkit

**Comment by 8MiYile** [comment]
but CMI plugin can get my username
![image](https://github.com/LuckPerms/LuckPerms/assets/25455400/2052c716-d227-4299-854f-11dcf8ebb021)

**Comment by underscore11code** [comment]
Hybrid setups are completely unsupported.

**Comment by 8MiYile** [comment]
@underscore11code 
it's hybrid server (fabric & bukkit)

**Comment by LeotomasMC** [comment]
... which is *not* supported
