### ISSUE TITLE
Changes not working

### ISSUE THREAD

**Issue by Uzuark** [LuckPerms/LuckPerms#3658]
### Description

If I try to unset a permission it doesn't work. If I try to change my own group after a while or when I rejoin I get the old rank back.

### Reproduction Steps

/lp user Uzuark parent set default
/lp user Uzuark permission unset test.1

### Expected Behaviour

That my group changes on every server and I can unset the permission.

### Server Details

git-Purpur-1970

### LuckPerms Version

v5.4.79

**Comment by underscore11code** [comment]
Is the permission (in your repro steps `test.1`) set on the *user* or on a *group*? Unsetting a node is like deleting it. 

If your goal is to block a specific permission for a player/group that they already inherit, set the permission to false (if using commands, add `false` after the `permission set` command, if using the web editor, click the `true` to turn it to `false`)

**Comment by Uzuark** [comment]
Okay Thanks
