### ISSUE TITLE
Boolean Context(s)

### ISSUE THREAD

**Issue by JHaroLC** [LuckPerms/LuckPerms#3662]
### Description

Of context "value" in a context, please allow for boolean operators to return a false or true value; active by a true or false attribute of the permission involved.r

### Proposed Behaviour

Contexts from Plugins have a True | False active statement, followed by a context True | False statement.

### Extra Details

This type of usage applies a second layer to the already glorious permissions plugin "LuckPerms". Please consider this.

**Comment by lucko** [comment]
This is already possible, you can return the strings "true" and "false" :)
