### ISSUE TITLE
Failed to validate connection

### ISSUE THREAD

**Issue by TheMartyCZ** [LuckPerms/LuckPerms#3666]
### Description

![image](https://github.com/LuckPerms/LuckPerms/assets/45405349/369f9f31-a861-48b1-9e7a-e40ea3ed8d35)

I have the latest version of LuckPerms BungeeCord and this is what it shows me on the proxy. Nothing on spigot servers.

### Reproduction Steps

I don't know

### Expected Behaviour

Everything works for me, I just don't know why I get this warn/error.

### Server Details

flamecord-1.5.0

### LuckPerms Version

v5.4.79

**Comment by lucko** [comment]
https://luckperms.net/wiki/Storage-system-errors

**Comment by TheMartyCZ** [comment]
@lucko Hello, I have it exactly according to the instructions and still sometimes it doesn't work, thank you.
