### ISSUE TITLE
Bug when i do /lp user GoldGamerPT parent remove nobre

### ISSUE THREAD

**Issue by GoldGamerPT** [LuckPerms/LuckPerms#3668]
### Description

![image](https://github.com/LuckPerms/LuckPerms/assets/75499273/35d2daf9-3388-4416-8865-7046e99ee28f)

When i do the command "/lp user GoldGamerPT parent remove nobre" it starts doing this and i cant remove the "nobre" group

### Reproduction Steps

/lp user GoldGamerPT parent remove nobre

### Expected Behaviour

It should just remove the group and put me in the default right?

### Server Details

Spigot 1.19

### LuckPerms Version

v5.4.79

**Comment by underscore11code** [comment]
Send logs please.

**Comment by GoldGamerPT** [comment]
[log.txt](https://github.com/LuckPerms/LuckPerms/files/11710121/log.txt)


> Send logs please.
