### ISSUE TITLE
Webhook / Log System

### ISSUE THREAD

**Issue by augesrob** [LuckPerms/LuckPerms#3669]
### Description

Have an area where it logs changes
- Rank Changes
- Permission Changes
- Something random was changed

Im looking for either we website addition to show logs or possible a webhook
so that we can see logs in a discord channel.

### Proposed Behaviour

A away to see changes that occurred while i was offline.

### Extra Details

Looking for a system to view changes.

**Comment by emilyy-dev** [comment]
LuckPerms already performs action logging (see [`/lp log` commands](https://luckperms.net/wiki/Log-Commands)) and is stored with the rest of data in storage. Plugins/mods/extensions can use the API and listen to relevant [log events](https://javadoc.io/doc/net.luckperms/api/latest/net/luckperms/api/event/log/package-summary.html) and relay the log information however they see fit (or alternatively have an extension provide a custom storage implementation for actions logs, but for something like this the API should be enough).
This doesn't seem like something that belongs in LuckPerms itself, but handled for the custom needs of oneself, as "webhook" is not a standard or specification.
