### ISSUE TITLE
Permissions not showing on web editor and not working in game.

### ISSUE THREAD

**Issue by Sm982** [LuckPerms/LuckPerms#3674]
### Description

I've got a few plugins that aren't showing in luckperms web editor and aren't working in game. 

SimpleStaffChat2
SignShop
MineableSpawners
JoinSoundReloaded
ItemJoin
InfiniteBucket
StackMob
TabList
worldedit
worldguard

### Reproduction Steps

Using the above plugins or similar, opening web editor and trying to assign permissions.

### Expected Behaviour

I expected for all permissions to show up and work if I tell them to or not. I've set perms in the web editor and they simply do not work. Really discouraging. By not working, I mean I set them, I cannot use x plugin's commands or I can use them if I haven't set them at all depends on the plugin.

### Server Details

paper spigot 1.19.4

### LuckPerms Version

v5.4.40

### Logs and Configs

N/A - using default config

### Extra Details

n/a

**Comment by Turbotailz** [comment]
The suggestion list is exactly that - a list of suggestions. It's not a full set of permissions available on your server.

If a permission doesn't show in the list, you can still write it in the input.

Also would be helpful if you showed what you're actually setting, and a list of plugins on your server.
