### ISSUE TITLE
How can i make luckperms run with customnpc mod

### ISSUE THREAD

**Issue by wibonsue** [LuckPerms/LuckPerms#3677]
### Description

Hello so basically im using arclight it allows you to use forge mods and spigot/bukkit plugins in one server
and my problem is when i put customnpc mod and try to join server it gives that error that i put in photo
and when i remove the mod i can join to the server or when i remove the luckperms i can join to the server again
what should i do i dont know
![2023-06-13_20 59 29](https://github.com/LuckPerms/LuckPerms/assets/89047094/9ed6e5a6-0bc8-4cee-9a01-16538106b7aa)

### Reproduction Steps

told in description part

### Expected Behaviour

to be able to join server

### Server Details

Arclight 1.16.5

### LuckPerms Version

v5.4.55

### Logs and Configs

https://gist.github.com/wibonsue/107ada38c9b063620c4a76fb23000a99

**Comment by lucko** [comment]
Forge/bukkit hybrid servers are not supported
