### ISSUE TITLE
Better handling for %luckperms_current_group_on_track_[track]%

### ISSUE THREAD

**Issue by dandud100** [LuckPerms/LuckPerms#3678]
### Description

This plugin should have a better handling for the %luckperms_current_group_on_track_[track]% placeholder.

If a player have two groups that are both in the track, the placeholder will stop working.

### Reproduction Steps

1. Create three groups A, B, C
2. Summon them together in a track named player
3. Use the Placeholder %luckperms_current_group_on_track_player% in a hologram or scoreboard or whereever.
4. Do /lp user Pokemoon group add B
5. The placeholder should still work
6. Do /lp user YOURNAME showtracks
7. See that you are on the Track at B
8. Do /lp user Pokemoon group add C
9. See that the Placeholder is now empty
10. Do /lp user YOURNAME showtracks
11. See that you are on Track at both A and B!

### Expected Behaviour

To be honest i dont even think i am doing my group management like this properly, but i have no clue how i can safely put my player in a certain group.

I have a usecase where i want to promote my players after x hours ingame from A to B, but only if they haven't got the group B like already manually from an server mod. Thats why i want to manually add the group to the player instead of using the promote command. My problem is, that it is missing an argument like /lp user <user> promote <track> <group> or something.

I just dont want that players get into group C because someone already promoted them manually to B when they should only got promoted from A to B.

I use the placeholder on my scoreboard to display their highest playtimerank. I know i could use the general highest weighted group placeholder, but that's not the issue. Also i want to see the playtimerank group from myself there and not my admin rank because it have the highest weight.

So all in all the best solution for me is something like: /lp user <user> promote player B

### Server Details

git-Paper-524 (MC: 1.19.4)

### LuckPerms Version

v5.4.84

**Comment by underscore11code** [comment]
[parent settrack](https://luckperms.net/wiki/Parent-Commands#lp-usergroup-usergroup-parent-settrack-track-indexgroup-context) sounds like what you want.

Also, placeholder `%luckperms_<prefix|suffix>_element_<element>%` accepts any of the [prefix stacking elements](https://luckperms.net/wiki/Prefix-&-Suffix-Stacking#how-do-i-add-other-elements), meaning `%luckperms_prefix_element_highest_on_track_<track>%` is possible, among other potentially useful combos.

**Comment by dandud100** [comment]
> [parent settrack](https://luckperms.net/wiki/Parent-Commands#lp-usergroup-usergroup-parent-settrack-track-indexgroup-context) sounds like what you want.

That is exactly what i wanted i think! Thank you!
