### ISSUE TITLE
Unable to place blocks when in proximity of an OP.

### ISSUE THREAD

**Issue by KuromeSama6** [LuckPerms/LuckPerms#3679]
### Description

Blocks are unable to be placed down for a non-op player, when said player is in range of a OP.

- BlockPlaceEvent is not cancelled, and the corresponding block is removed from the player’s inventory after being placed, but the block disappears immediately.

### Reproduction Steps

> Give one player `luckperms.autoop`

> Have corresponding auto op features enabled.

> Have a non op player place a block near the opped player.

### Expected Behaviour

The block will disappear, but will not be return to the player’s inventory.

- Disablement of the LuckPerms plugin through Plugman fixes the problem.
- The OP is not affected.
- If no OPs are online, both players are not affected.

### Server Details

PaperMC 1.12.2 b1612

### LuckPerms Version

v5.4.88

**Comment by underscore11code** [comment]
Runtime loading/disabling/reloading of LP with Plugman or similar is not supported. Restart your server.

As for the actual issue, LP does not touch any ingame events i.e. block break, another plugin is at fault.
