### ISSUE TITLE
Invalid class name due to misshapen relocation

### ISSUE THREAD

**Issue by A248** [LuckPerms/LuckPerms#3681]
### Description

LuckPerms attempts to relocate certain class files, but for driver classes, it writes the incorrect class name.

### Reproduction Steps

The bug can be reproduced by running LibertyBans and LuckPerms at the same time. When LibertyBans attempts to class load the MariaDB driver class, a `NoClassDefFoundError` is thrown because the class file was incorrectly relocated by LuckPerms.
https://github.com/A248/LibertyBans/issues/213

### Expected Behaviour

LuckPerms writes valid class files

### Server Details

N/A

### LuckPerms Version

v5.4.77

### Logs and Configs

Here is an example from user logs
https://pastebin.com/bnRSvhyg

### Extra Details

In previous situations, this bug has been caused by jar-relocator 1.6 and below, which does not relocate entries under META-INF/services. https://github.com/lucko/jar-relocator/commits/master

With no accusation of blame -- I'm simply pointing out circumstances -- I wouldn't be surprised if the same bug exists in LuckPerms for the same reason as it did in jar-relocator. They are primarily written by the same author after all. In all probability, it is the same bug.

**Comment by lucko** [comment]
LuckPerms has been using jar-relocator 1.7 since this commit https://github.com/LuckPerms/LuckPerms/commit/6d2a5a63171e1084c5ccb9634aecea0931638827 (LP v5.4.80)

I suspect that upgrading to the latest version will fix the issue, but feel free to comment/re-open this ticket if it does not.

**Comment by ChromMob** [comment]
> LuckPerms has been using jar-relocator 1.7 since this commit [6d2a5a6](https://github.com/LuckPerms/LuckPerms/commit/6d2a5a63171e1084c5ccb9634aecea0931638827) (LP v5.4.80)
> 
> I suspect that upgrading to the latest version will fix the issue, but feel free to comment/re-open this ticket if it does not.

The issue is still happening with latest LuckPerms and LibertyBans
