### ISSUE TITLE
Silent Commands

### ISSUE THREAD

**Issue by expxx** [LuckPerms/LuckPerms#3682]
### Description

If you have a server, and you have a command like, `/givemerank` for example, you code it so when they do this it adds a group to them, but then everyone on the server with the permission gets a notification saying they did that. Maybe, add like a `--silent` flag so it doesn't send notifications. 

### Proposed Behaviour

Add a `--silent` flag, which would make it not send notifications in game, rather in console, or not at all. Depending on how you configure it.

**Comment by LeotomasMC** [comment]
Every time this has been brought up, it has been denied as the people suggesting this had a different issue at play (see #3484 and #3486 ). It was also brought up for someone with a badge plugin that ran LuckPerms commands, and a log filter was added to solve this. Does the resolution in #1980 not work for you? If not, please explain why. Additionally, if you would like to stop seeing log messages, you can disable them with `/lp log notify off`. You cannot disable log messages in the console as it would be possible to make changes that would not get tracked and you would not want to deal with someone abusing this to hide changes they made.
