### ISSUE TITLE
Wordpress Synchronization

### ISSUE THREAD

**Issue by chelminski** [LuckPerms/LuckPerms#3684]
### Description

Hey ;) 
I would like to ask you to add a new function that synchronized user permissions with wordpress instance. Most websites are built with the wordpress engine. Adding synchronization of permissions between wordpress and luckyperms would be something desired by a large group of users - including me :D .

### Proposed Behaviour

Luckperms would synchronize (or synchronization would only work unilaterally) permissions with the wordpress database so that depending on the rank on the server, players would see different content and different functions on the website. Wordpress offers many more possibilities than spigot/paper etc.

### Extra Details

Currently, the minecraft plugin that manages users is AuthMeReloaded. It allows you to create user accounts in the wordpress database and **adds the basic "subscriber" permission** to them. I hope it will be of any help.

https://github.com/AuthMe/AuthMeReloaded/

I don't know what else I can add, but I would love to see this feature implemented someday. 😁

**Comment by LeotomasMC** [comment]
> Most websites are built with the wordpress engine

what?

im not quite sure what you are trying to do, but something like this seems like it could (and should) be handled by an extension using the api

**Comment by lucko** [comment]
Sorry - this is really out of scope for LuckPerms at this time
