### ISSUE TITLE
Luckperms Tabcompleate Permission

### ISSUE THREAD

**Issue by ghost** [LuckPerms/LuckPerms#3687]
### Description

Hello, my suggestion is that you need a permission to be able to complete something in the tab.

### Proposed Behaviour

This means you don't have to use another plugin, most of which don't even have an API.

**Comment by LeotomasMC** [comment]
luckperms itself does hide its own autocompletions to users based on permissions. it is up to other plugins to do the same. plugins that allow you to hide autocompletions are a bandaid fix to plugin developers not handling autocompletions correctly, but this bandaid fix should not be part of luckperms itself

**Comment by Limeprog** [comment]
> luckperms itself does hide its own autocompletions to users based on permissions. it is up to other plugins to do the same. plugins that allow you to hide autocompletions are a bandaid fix to plugin developers not handling autocompletions correctly, but this bandaid fix should not be part of luckperms itself

I mean the Commands /lp or /lpv them have no permission every player can see them, you can't prevent it

**Comment by Limeprog** [comment]
@lucko

**Comment by LeotomasMC** [comment]
the is no permission for the tab completion as there is no permission for the command itself. any player can use `/lp`, `/lpv`, or `/lpb` to see the luckperms versions

**Comment by Emilbaercraft** [comment]
Yes his Idea is to set a permission for that

> the is no permission for the tab completion as there is no permission for the command itself. any player can use `/lp`, `/lpv`, or `/lpb` to see the luckperms versions

**Comment by Emilbaercraft** [comment]
Because noone will show everyone wich plugins *s*he use
