### ISSUE TITLE
Migration of both LuckPerms and LPC to Modrinth

### ISSUE THREAD

**Issue by Nukecraft5419** [LuckPerms/LuckPerms#3688]
### Description

Migrating the 2 plugins mentioned above to Modrinth would help a lot 

### Proposed Behaviour

Migrating the two above-mentioned plugins to Modrinth would help a lot there is more control by modrinth when it comes to viruses and the like and then they respect more the authors also have monetisation which gives the authors 100% of the income

**Comment by powercasgamer** [comment]
LPC is not made by or related to LuckPerms.

**Comment by LordSamosa** [comment]
And Luckperms is already on Modrinth [https://modrinth.com/mod/luckperms](https://modrinth.com/mod/luckperms)

**Comment by LeotomasMC** [comment]
LPC is not affiliated with LuckPerms.
the mod versions of luckperms [are already on modrinth](https://modrinth.com/mod/luckperms)
it has been proposed to also include the plugin on modrinth, but that would add 1-3 additional releases (depending on if the proxy versions get included) that need to made with every luckperms release, in addition to the current 2 modrinth releases, 2 curseforge releases, the spigot release, and the ore release.
luckperms is also entirely free, so not sure how the monetization matters at all

**Comment by Nukecraft5419** [comment]
Apologies for LPC I forgot I wrote the problem quickly

**Comment by Nukecraft5419** [comment]
But on modrinth I notice that it is only mod and not for servers
