### ISSUE TITLE
Changes do not fire NodeMutate-, NodeAdd and NodeRemoveEvent [...] on other servers

### ISSUE THREAD

**Issue by remadisson** [LuckPerms/LuckPerms#3695]
### Description

The `NodeMutate-`, `NodeAdd-`, and the `NodeRemoveEvent` are only fired on the server where you triggered the in-game command on. (I assume the Events `UserPromote-` or `UserDemoteEvent` aren't fired either.)

### Reproduction Steps

1. Register listeners for **NodeMutate**, **NodeAddEvent** and **NodeRemoveEvent**.
2. Make them print any debug message.
3. Compile and put it on the server.
4. Run `/lp user <name> parent set <someGroup>` -> See message; Same with `/lpb <sameCommand>` in case of bungee plugin.
5. Now run the opposite Command without changing the Plugin e.g. -> `Paper-Plugin` and run `/lpb command` or `Waterfall-Plugin` and run `/lp command` 
6. In case of action at 5 there should not be any debug message printed

### Expected Behaviour

I would suggest that triggering the events (e.g. `NodeMutate-`, `NodeAdd-`, `NodeRemove-`, `UserPromote-`, `UserDemoteEvent`) on both the executing server and the proxy would be useful.

### Server Details

git-Paper-518 (MC: 1.19.4) and git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536

### LuckPerms Version

v.5.4.98 on both paper and waterfall

**Comment by emilyy-dev** [comment]
That is intended behaviour, such events can only fire in the environment the changes were made in; if a messaging service is configured, the other servers will only receive a notification to reload data from storage, and related [messaging events](https://javadoc.io/doc/net.luckperms/api/latest/net/luckperms/api/event/sync/package-summary.html) are fired in those servers as well (or if a log is published to common log storage, the [log receive event](https://javadoc.io/doc/net.luckperms/api/latest/net/luckperms/api/event/log/LogReceiveEvent.html)).
