### ISSUE TITLE
Spongeforge api7 does not load luckperms

### ISSUE THREAD

**Issue by Xplodin** [LuckPerms/LuckPerms#3696]
### Description

It just doesnt seem to recognize luckperms, I upgraded from the ore page to the luckperms official dl and deleted all configs/luckperms folders.
There is nothing in the log besides it finding the mod but it never tries to initialize.

### Reproduction Steps

spongeforge latest 1.12.2
install luckperms and nucleus.
nucleus loads but luckperms doesnt

### Expected Behaviour

both to load and initialize

### Server Details

spongeforge-1.12.2-2838-7.4.8-RC4142

### LuckPerms Version

LuckPerms-Sponge-5.4.98

### Logs and Configs

https://gist.github.com/Xplodin/05d17adb2ede3c17584258665e78ed2c

### Extra Details

the one on Ore worked but this one doesnt

**Comment by Xplodin** [comment]
nvm, luckperms site says api 4 and higher. theres also 3 and lower
idk if its accidental or not to leave that there

**Comment by LordSamosa** [comment]
Luckperms for Sponge API 7 can be found here, as it is no longer being updated: [https://ore.spongepowered.org/Luck/LuckPerms/versions/5.3.98](https://ore.spongepowered.org/Luck/LuckPerms/versions/5.3.98)
