### ISSUE TITLE
Can't give access to vanilla commands on fabric 1.20.1

### ISSUE THREAD

**Issue by vipaoL** [LuckPerms/LuckPerms#3697]
### Description

Vanilla commands are not visible in luckperms autocompletions and doesn't work after I add them manually. I just copied commands from luckperms wiki to allow ban command, but it just doesn't work. Luckperms see only some mods' commands (ledger, commandspy, armor_stand_editor, polymer, voicechat, luckperms), but can't see others
![picture](https://github.com/LuckPerms/LuckPerms/assets/59665125/397d812a-af82-4057-bd5e-bae2daf1e0cc)

### Reproduction Steps

/lp creategroup admin
/lp group admin permission set minecraft.command.ban true
/lp user ViPaOl parent add admin
/ban ViPaOl

### Expected Behaviour

The server should allow me to use /ban command

### Server Details

Minecraft 1.20.1 with Fabric Loader 0.14.21, openjdk (build 17.0.7+0-suse-150400.3.18.2-x8664)

### LuckPerms Version

v5.4.98

### Extra Details

I deleted all my mods except luckperms and fabric api, but it didn't help. Can't see any errors in logs

**Comment by LeotomasMC** [comment]
vanilla does not have permissions. you need a mod to add them, such as https://github.com/lucko/minecraft-command-permissions-fabric/releases

**Comment by vipaoL** [comment]
Thank you for your answer. This mod is not updated to 1.20, but I found a new one in its issues: https://modrinth.com/mod/vanilla-permissions
