### ISSUE TITLE
[19:00:25] [Server thread/WARN]: [LuckPerms] Something went wrong whilst upgrading the LuckPerms database. Please report this on GitHub.

### ISSUE THREAD

**Issue by Polaproli** [LuckPerms/LuckPerms#3699]
### Description

Log error

### Reproduction Steps

I just started my server on my own computer.

### Expected Behaviour

Well, I don't really know, the error message asked to report it on github.

### Server Details

Paper-1.20.1-59

### LuckPerms Version

5.4.98

### Logs and Configs

https://pastebin.com/a4CEyWkt

### Extra Details

I happens everytime I run my server.

**Comment by lucko** [comment]
See suggested steps in #3693
