### ISSUE TITLE
Compile luckperms into 1 jar

### ISSUE THREAD

**Issue by expxx** [LuckPerms/LuckPerms#3704]
### Description

Instead of having 5 different JARs for the same plugin just different softwares, compile it all into 1 jar like LiteBans. Makes it simpler for end-users.

### Proposed Behaviour

Compile all jars of luckperms into 1 jar.

**Comment by powercasgamer** [comment]
This wouldn't work for multiple reasons, one of those being that both the `bukkit` module and `nukkit` module require a `plugin.yml`

**Comment by A248** [comment]
There exists `nukkit.yml`

**Comment by lucko** [comment]
The main reason for not doing this is that platforms such as SpigotMC put an arbritrary limit on the jar size of uploads - combining everything would tip us over that edge.

Also there's not really anything wrong with the current way IMO :)
