### ISSUE TITLE
Permission data is completely lost

### ISSUE THREAD

**Issue by 1470429149** [LuckPerms/LuckPerms#3706]
### Description

I rebooted the server while using LuckPerms and all the players' permissions were reset without using the LP command

### Reproduction Steps

I don't know if it's because I've never used the database, but the server has been running stably for a year and it didn't appear the problem of permission loss until it was restarted today.

### Expected Behaviour

LuckPerms does not lose data

### Server Details

paper1.17

### LuckPerms Version

5.4.0

### Logs and Configs

[2023-07-13-1.log.gz](https://github.com/LuckPerms/LuckPerms/files/12041596/2023-07-13-1.log.gz)
[2023-07-13-2.log.gz](https://github.com/LuckPerms/LuckPerms/files/12041597/2023-07-13-2.log.gz)

### Extra Details

In 2023-07-13-1. Log. GZ, LuckPerms was running normally. It was not until the server was turned on again (2023-07-13-2. Log. GZ) that it was found that LuckPerms lost the permission data.

**Comment by etztrefis** [comment]
The same thing happens from time to time

**Comment by lucko** [comment]
You're running quite an old version. My only suggestion is to restore from a backup and then upgrade to the latest LP version.
