### ISSUE TITLE
Show exact date instead of time

### ISSUE THREAD

**Issue by daniel-skopek** [LuckPerms/LuckPerms#3709]
### Description

It would be good if the log showed the exact date instead of the time it happened.

### Proposed Behaviour

Screenshot: 
![](https://i.imgur.com/WyOfIT9.jpeg)

**Comment by emilyy-dev** [comment]
Hovering your cursor over the time since the log's recording already displays the date & time as shown in #3597

**Comment by emilyy-dev** [comment]
it's a fairly recent change, make sure you have luckperms updated. https://luckperms.net/download
