### ISSUE TITLE
Permission Comments 

### ISSUE THREAD

**Issue by HydroYT** [LuckPerms/LuckPerms#3710]
### Description

I think luckperms should have an option for comments in the web editor  for each permission. This way its much easier to know what each permission does so you don't have to go through the hassle of checking each one. 

### Proposed Behaviour

It would provide a box in the web editor where you can provide a comment for each permission. I think this will be really beneficial to people using the plugin.

**Comment by LeotomasMC** [comment]
seems awfully similar to #3628
