### ISSUE TITLE
Rank Downgrade/Permission unsetting not working (no errors)

### ISSUE THREAD

**Issue by Uzuark** [LuckPerms/LuckPerms#3712]
### Description

If I want to set the rank of an admin to default it works. But if I rejoin he has the same admin rank again.

I can not unset permissions/metas etc. with the lp editor or with commands.

### Reproduction Steps

/lp user Uzuark parent set default
/lp user Uzuark permission unset 123

### Expected Behaviour

/lp user Uzuark parent set default --> Should clear your ranks and set it primarily to default
/lp user Uzuark permission unset 123 --> Should unset the permission

### Server Details

git-Purpur-2004

### LuckPerms Version

v5.4.88

**Comment by LeotomasMC** [comment]
i assume you are trying to negate "123" for that user, but that permission is in your default group. you would need to use `permission set 123 false` instead of `permission unset 123`.

**Comment by Uzuark** [comment]
No i really want to unset (for the User Not the Group) it. And any idea Why i can Not Change ranks

**Comment by Uzuark** [comment]
BUMP (using now v5.4.98)

**Comment by Uzuark** [comment]
I forgot to mention that i can give permissions or set higher Ranks. Not below ranks and unset permissions

**Comment by lucko** [comment]
> i assume you are trying to negate "123" for that user, but that permission is in your default group. you would need to use `permission set 123 false` instead of `permission unset 123`.
