### ISSUE TITLE
Possible login deadlock on Velocity

### ISSUE THREAD

**Issue by AoElite** [LuckPerms/LuckPerms#3713]
### Description

It appears Luckperms can possibly deadlock the Velocity LoginEvent & will prevent further logins from occurring. Also luckperms hangs when shutting down according to Velocity when this issue occurs.

### Reproduction Steps

It's hard to say what causes this occur, possibly a race condition or a continuation not being resumed, but one thing I did notice is when shutting down a proxy you have to usually kill it since luckperms won't shutdown properly according to Velocity.

### Expected Behaviour

You do not get stuck on logging in & you are able to shutdown the proxy without killing it.

### Server Details

Velocity 3.2.0-SNAPSHOT (git-5ef90c46-b258)

### LuckPerms Version

v5.4.98

### Logs and Configs

Config: https://pastebin.com/W7TMDgXD

### Extra Details

The only other plugins I'm using is SparkVelocity & my own plugin used to debug this issue. When debugging using my own plugin I can see that the other events are firing except the LoginEvent, which isn't firing at all. It could be a velocity issue but the fact that luckperms is not shutting down properly when this issue occurs is what leaves me to believe it could possibly be luckperms causing this.

**Comment by emilyy-dev** [comment]
I am unable to reproduce this. It would be very helpful to have the proxy's thread call stacks for when this happens and further diagnose what things are locked on, you can obtain it using the [`jstack` command](https://docs.oracle.com/en/java/javase/17/docs/specs/man/jstack.html) (bear in mind this command is part of the JDK and not the JRE)

**Comment by AoElite** [comment]
I do have a heap dump of when this occurred. I'll check that.
