### ISSUE TITLE
API question. How to get absolutely all permissions from a user? Including group permissions.

### ISSUE THREAD

**Issue by RadBe** [LuckPerms/LuckPerms#3714]
### Description

For example, there is a premium group that is inherited from VIP. The player has a premium group. How to get all permissions including premium group and vip group permissions?

I tried to get the primary group and its permissions, but there are no permissions from the vip group.
```
final Group group = LuckPermsProvider.get().getGroupManager().getGroup(user.getPrimaryGroup());
for (final Node node : group.nodes()) {
  ...
}
```

### Proposed Behaviour

-

### Extra Details

sorry, I don't have a discord to ask a question there.

**Comment by lucko** [comment]
You are looking for `user.resolveInheritedNodes()` :]
