### ISSUE TITLE
How to fix  essentials "/heal" at minecraft server, when i use it the command will come out like "you has't has access for that command"

### ISSUE THREAD

**Issue by Unn0wn002** [LuckPerms/LuckPerms#3715]
### Description

when I use Lp I set it for a group to be able to "/heal"

with Add command captions like this
- essentials.heal
- essentials.heal.other
- essentials.heal.cooldown
- essentials.heal.cooldown.bypass
- luckperms.viewcommand
- essentials
- essentials.viewcommand

but unable to work and still issue information "you has't has access for that command"
Is there a way out for this, 'please I'm almost out of ways'

**Comment by LeotomasMC** [comment]
please send a screenshot of the output of `/plugins`. in the future, you should follow the issue template

**Comment by Unn0wn002** [comment]
![image](https://github.com/LuckPerms/LuckPerms/assets/129099303/da33a2f4-70ba-4e2f-8f54-1f5efac050e5)

**Comment by Unn0wn002** [comment]
what should i do?

**Comment by LeotomasMC** [comment]
consult the docs for pl-hide to see how to allow commands, or alternatively, remove it entirely

**Comment by Unn0wn002** [comment]
oki thx
