### ISSUE TITLE
Luck perms all forge versions is failing saying cannot connect to logger api and crashing. 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [LuckPerms/LuckPerms#3719]
### Description

Technically I tested on 
1.16.5
1.19.2
1.20.1 

The crash was the same regardless of version. It seems to be a backend issue.

### Reproduction Steps

Get luck perms on those versions.

### Expected Behaviour

No crash on startup.

### Server Details

Multiple Test Environments

### LuckPerms Version

Multiple Test Environments

### Logs and Configs

I didn't keep them.

### Extra Details

I am shocked this happening.

**Comment by underscore11code** [comment]
Without logs, server details, and LP versions, there is absolutely no way we can possibly diagnose a crash, let alone fix it. Please follow the issue template.
