### ISSUE TITLE
Bedrock Player role not showing on tab list, nametag, chat.

### ISSUE THREAD

**Issue by RobinCodestoGitHub** [LuckPerms/LuckPerms#3723]
### Description

Hi.

I'm using GeyserMC and floodgate to enable bedrock players to join my server. 
But when I give them ranks, it is not showing up on the tab list (alas playerlist), chat, nametag.
Where for Java players, they work as expected.
Have any solution?

### Reproduction Steps

- GeyserMC & Floodgate
- LuckPerms setten up to allow bedrock players to get ranks
- Using LuckTab to show these things.
- Aternos server

### Expected Behaviour

I expected to work just like for Java Players.

### Server Details

PaperMC 1.20.1 (98)

### LuckPerms Version

v5.4.40

**Comment by underscore11code** [comment]
Assuming all data is displayed as expected for `/lp user <affected user> info`, this is out of scope for Luckperms. LP only manages the data and makes it available for other plugins to display - if they aren't displaying it correctly, that's not on us.
