### ISSUE TITLE
Luck perms not reconizing essentials permissions.

### ISSUE THREAD

**Issue by saminator0107** [LuckPerms/LuckPerms#3726]
### Description

luck perms not providing permission essentials.repair to players. I am not sure of this is a luck perms bug or an essentials bug, i reported this to both.

### Reproduction Steps

give a non-opped player essentials.repair and essentials.repair.enchanted
They will not be able to use /repair to repair items, enchanted or not.

Link to bug report on essentials github: https://github.com/EssentialsX/Essentials/issues/5460

### Expected Behaviour

the player should be able to repair the held item
![no perms luckperms](https://github.com/LuckPerms/LuckPerms/assets/132668102/a72cf760-e6aa-4658-8eed-66513df0414a)
![noperms](https://github.com/LuckPerms/LuckPerms/assets/132668102/56d2f7cb-4e3d-4599-8e6c-8502e9ee8f7f)

### Server Details

https://essentialsx.net/dump.html?id=963a7504809c47f5b8790e04432e2dc3

### LuckPerms Version

5.4.98

**Comment by ImDarkLaw** [comment]
This is unrelated to LuckPerms. You've already received a response on the EssentialsX github issue linked [here](https://github.com/EssentialsX/Essentials/issues/5460).

**Comment by saminator0107** [comment]
> This is unrelated to LuckPerms. You've already received a response on the EssentialsX github issue linked [here](https://github.com/EssentialsX/Essentials/issues/5460).

yes i got it taken care of. I forgot i had that plugin installed, dummy moment haha.
