### ISSUE TITLE
Relocate Difference into the API

### ISSUE THREAD

**Issue by MCMDEV** [LuckPerms/LuckPerms#3727]
### Description

I think it would be nice to have https://github.com/LuckPerms/LuckPerms/blob/master/common/src/main/java/me/lucko/luckperms/common/util/Difference.java available in the API.

### Proposed Behaviour

Eh, it would make it available in the API?!?

### Extra Details

I'm making a plugin that matches group permissions to a YAML file so I can version it with Git. Sync storage wouldn't work cause it's multiple servers.

Right now I can just copy the file, but the class being in the API would be nicer.

**Comment by lucko** [comment]
Feel free to copy-pasta it (in line with the license of course :))
