### ISSUE TITLE
Unable to build out of the box?

### ISSUE THREAD

**Issue by KweezyCode** [LuckPerms/LuckPerms#3728]
### Description

README says that java 8+ is required, but build process says 17 is minimum, at java 17 error appears:
![image](https://github.com/LuckPerms/LuckPerms/assets/36813920/df4c23b1-d701-4855-9efb-dcec7bd5c38b)

### Reproduction Steps

git clone project then build it

### Expected Behaviour

working jar

### Server Details

no server

### LuckPerms Version

latest

**Comment by LeotomasMC** [comment]
that just looks like the tests for the standalone version are failing, and the actual compile task appears to have run fine

**Comment by KweezyCode** [comment]
anyway, README is wrong, java 8 is not supported by fabric/forge

**Comment by lucko** [comment]
I've updated the readme, thanks
