### ISSUE TITLE
Exception stopping a server

### ISSUE THREAD

**Issue by UnsafeDodo** [LuckPerms/LuckPerms#3730]
### Description

error while stopping a server
![luckperms](https://github.com/LuckPerms/LuckPerms/assets/139406146/831be40b-7c70-4a51-83da-30612a29dca0)

### Reproduction Steps

happens sometimes (like twice every 10~ times) when you type `stop` in the console to stop a server

### Expected Behaviour

the server should have stopped normally

### Server Details

Fabric loader 0.14.21 (MC 1.20.1)

### LuckPerms Version

5.4.102

**Comment by lucko** [comment]
Hmm this is a tricky one, it is probably safe to ignore. I guess it happens if the server thread shuts down before all of the player disconnections have been processed
