### ISSUE TITLE
Temporary groups expires sooner than expected

### ISSUE THREAD

**Issue by MatinHQ** [LuckPerms/LuckPerms#3731]
### Description

 temp group doesn't work properly 

yesterday I gave user `yagami` supreme group for a month but today his temp group is gone I did run `lp log userhistory yagami` and nothing changed in logs but his rank is gone

Also yesterday I checked his info to make sure I added the rank and duration correctly and it was fine

Also multiple user reported this issue on my server

![image](https://github.com/LuckPerms/LuckPerms/assets/22664859/4cb51c55-7421-44af-b4ba-f14f13904fe3)
![image](https://github.com/LuckPerms/LuckPerms/assets/22664859/2e3c0b11-9f86-4060-b0c3-a70d1ecded3f)
![image](https://github.com/LuckPerms/LuckPerms/assets/22664859/e070f71a-fe97-46a9-bcf8-3409ace5814a)

### Reproduction Steps

I just add rank to the user and few hours later it will be gun

### Expected Behaviour

Don't remove the temporarily group until expire time

### Server Details

paper 1.19.4

### LuckPerms Version

ver 5.4.98

**Comment by underscore11code** [comment]
This is most likely a result of you running offline mode. I suspect you'll find that the group always disappears after the affected user disconnects and reconnects to the server. Make a note of the UUID of a player who receives a temporary group, when they loose it, check their UUID, it will most likely have changed. 

If this is indeed the case, there is absolutely nothing LP can do about it - UUIDs are supposed to be immutable, one UUID per player, and as such all proper plugins store their data under UUIDs, not usernames. If something is changing their UUID, as far as LP is concerned, it's a completely new player.

**Comment by MatinHQ** [comment]
> This is most likely a result of you running offline mode. I suspect you'll find that the group always disappears after the affected user disconnects and reconnects to the server. Make a note of the UUID of a player who receives a temporary group, when they loose it, check their UUID, it will most likely have changed.
> 
> If this is indeed the case, there is absolutely nothing LP can do about it - UUIDs are supposed to be immutable, one UUID per player, and as such all proper plugins store their data under UUIDs, not usernames. If something is changing their UUID, as far as LP is concerned, it's a completely new player.

I double checked doubled checked for left over permissions in the database in case of what you say and player UUID didn't changed, also they didn't change username
