### ISSUE TITLE
LuckPerms Prefixes in Chat Not Working

### ISSUE THREAD

**Issue by ChesterS1** [LuckPerms/LuckPerms#3735]
### Description

A friend and I are trying to setup LuckPerms on our server but the titles are only showing on the TAB list and not in chat. We tried the commands that should've fixed it but nothing worked.
![2023-08-14_23 36 06](https://github.com/LuckPerms/LuckPerms/assets/67078702/93764bfa-e9e7-4f55-bbf7-e30d6e4f5fce)
![2023-08-14_23 36 12](https://github.com/LuckPerms/LuckPerms/assets/67078702/0ca9cace-0a7f-49d6-882a-37ee325beaad)

### Reproduction Steps

Followed the commands from the website to setup the groups and prefixes.

### Expected Behaviour

No prefixes in chat.

### Server Details

Helbulus (1.19.2)

### LuckPerms Version

v5.4.46

**Comment by ImDarkLaw** [comment]
LuckPerms does not format the chat. You need a chat formatting plugin for your prefixes to be displayed. 

Additionally, if the prefix defined within LuckPerms shows when running `/lp user <user> info`, then LuckPerms is doing its job.

On our wiki page, you can find some chat plugin recommendations that go along with LuckPerms which you may want to checkout. Link [here](https://luckperms.net/wiki/Prefixes,-Suffixes-&-Meta#displaying-prefixes-and-suffixes).
