### ISSUE TITLE
Placeholders not working on Velocity

### ISSUE THREAD

**Issue by Iuliane0** [LuckPerms/LuckPerms#3736]
### Description

I'm setting up a velocity server where the luckperms plugin is in the velocity proxy server, not in every individual server. I'm using PlaceholderAPI and the luckperms placeholders are not working at all.

### Reproduction Steps

Install the luckperms plugin in the velocity proxy plugins folder, install the placeholder plugin in the server you want to test the placeholders on, set a placeholder in the config file of a supporting plugin (for example essentialsx chat, %luckperms_prefix% is just showing this text as it is)

### Expected Behaviour

Plugin's placeholders to work with velocity

### Server Details

Paper 1.20.1 108

### LuckPerms Version

v5.4.102

**Comment by LeotomasMC** [comment]
PAPI cannot pull values from luckperms on a proxy. luckperms must be installed on the backend for PAPI to be able to get data from it.
