### ISSUE TITLE
Database upgrade from V1 to V2 error.

### ISSUE THREAD

**Issue by Loving11ish** [LuckPerms/LuckPerms#3743]
### Description

When updating to the latest version of LP, the plugin automatically updates its database from V1 to V2.  The following error occurred when this happened and it told me to report this on GitHub.

https://mclo.gs/iyB2Xqn

### Reproduction Steps

Perform a V1 database update to V2 on git-Paper-"c016e03" (MC: 1.20.1).  The error message is then printed to the console.

### Expected Behaviour

The V1 database should be automatically updated to V2 without any errors.

### Server Details

git-Paper-"c016e03" (MC: 1.20.1)

### LuckPerms Version

LuckPerms-Bukkit-5.4.102

### Logs and Configs

Here is an Mc.Logs link to the exact error that was produced.

Error message: https://mclo.gs/iyB2Xqn

Attached is the config files for LP after this error.
[LuckPerms.zip](https://github.com/LuckPerms/LuckPerms/files/12496438/LuckPerms.zip)

Server plugin list: https://mclo.gs/IECkT1R

**Comment by lucko** [comment]
Please see comments on other issues: https://github.com/LuckPerms/LuckPerms/issues?q=Something+went+wrong+whilst+upgrading+the+LuckPerms+database
