### ISSUE TITLE
High ticks on permission check

### ISSUE THREAD

**Issue by xF3d33** [LuckPerms/LuckPerms#3755]
### Description

![image](https://github.com/LuckPerms/LuckPerms/assets/67204462/c248908d-f5f7-4864-ba8b-2c964f0f0138)

luckperms is causing high ticks 
![image](https://github.com/LuckPerms/LuckPerms/assets/67204462/9116165e-b5a8-4f6d-b999-37c861990461)

### Reproduction Steps

actually idk

### Expected Behaviour

no lag

### Server Details

Pufferfish version git-Pufferfish-22 (MC: 1.17.1)

### LuckPerms Version

v5.4.102

**Comment by ImDarkLaw** [comment]
LuckPerms is responding to a high amount of permission checks made by other plugins. A full spark report would be more useful here to clear the air and gather some additional info on this, however, this is not something directly related to LuckPerms.

**Comment by lucko** [comment]
I'm guessing that a context calculator (nested below getQueryOptions) is causing the performance issue, not LuckPerms itself
