### ISSUE TITLE
The server is stuck in threads

### ISSUE THREAD

**Issue by yuankun1** [LuckPerms/LuckPerms#3759]
### Description

I don't know

### Reproduction Steps

I don't know

### Expected Behaviour

I don't know

### Server Details

git-catserver-74 MC:1.16.5

### LuckPerms Version

5.4.102

### Logs and Configs

https://gist.github.com/yuankun1/58c261bb761fa6ad9d2dd55f9a596a25

**Comment by ImDarkLaw** [comment]
Bukkit and Forge hybrids, such as the server software you're using - CatServer, are not officially supported. 

Please reproduce on a platform LuckPerms supports and install the proper LuckPerms jar from the [download page](https://luckperms.net/download).
