### ISSUE TITLE
Permission on the gamemode can't be specified

### ISSUE THREAD

**Issue by DAYOREAM** [LuckPerms/LuckPerms#3761]
### Description

With lp, I can see the permissions minecraft.command.gamemode.survival/creative/spectator/adventure. But when I set one of the four to ture, the player can use gamemode to change into all four modes, even if I set others to false.
So do I mistake the use of minecraft.command.gamemode.survival/creative/spectator/adventure, or it's really a problem?

### Reproduction Steps

set minecraft.command.gamemode.creative and survival to ture, others to false--> fail
set minecraft.command.gamemode.creative.* and survival.* to ture, others to false--> fail
set minecraft.command.gamemode to true, minecraft.command.gamemode.creatiev and creative.* to false--> fail

### Expected Behaviour

I hope the management of gamemode can be specified because I don't really want to add more plugins like es.

### Server Details

pupur.1.20.1

### LuckPerms Version

LuckPerms-Bukkit-5.4.102

**Comment by ZeromaniacMc** [comment]
If you have essentials installed, know that it overrides the /gamemode command. Meaning the vanilla gamemode permissions aren't even asked. Furthermore, the vanilla gamemode permissions can NOT be split into different modes BUT essentials has this feature. Please note that luckperms does not own, implement, or invent these permissions,  not even vanilla ones. Vanilla permissions are added by your server software such as purpur, paper etc.
