### ISSUE TITLE
Avast reports luckperms.net as malware

### ISSUE THREAD

**Issue by Bloodrayne1995** [LuckPerms/LuckPerms#3762]
### Description

Avast reports the website "https://luckperms.net" as a HTML:Script-inf malware. Don`t know if this legit. But I can not use some of the plugins functionalities.

It just comes up, if something of luckperms.net is used.

Don`t know if its false alarm, but better be safe.

### Reproduction Steps

Just go on website or use website related commands like /lp editor

### Expected Behaviour

Website works as intended.

### Server Details

No plugin problem

### LuckPerms Version

Not relevant

### Extra Details

[Screenshot of avast report](https://imgur.com/a/5IdG4P9)

Rough translation:
THREAT BLOCKED
We have blocked the connection to luckperms.net because it was infected with HTML:Script-inf [Susp]

**Comment by Turbotailz** [comment]
This is known. Please disable your antivirus or add luckperms.net to the whitelist if possible. It will remain this way until I can get them to remove the block (it happened a few months ago as well).
