### ISSUE TITLE
NEED URGENT HELP!!! A database error occurred whilst loading permissions data. Please try again later. If you are a server admin, please check the console for any errors.

### ISSUE THREAD

**Issue by FurryBush** [LuckPerms/LuckPerms#3764]
### Description

Please I am having this error only when connecting when connecting luckperms to the database and I keep receiving this error A database error occurred whilst loading permissions data. Please try again later. If you are a server admin, please check the console for any errors. I have already checked My credentials are absloutely right help is really really appreciated thank you.

### Reproduction Steps

Even reproducing and causing problem when all plugins and their folders deleted only happens when changing config/connecting database to luckperms.

### Expected Behaviour

I expect everything to be working perfectly fine with the database when creating rank and other things using the plugin it is shared among all the servers using the database.

### Server Details

Causing in Paper and others too Servers:Bedwars:1.8.9 and Hunger Games:1.8.9 and Proxy is Waterfall 1.20

### LuckPerms Version

LuckPerms-Bukkit-5.4.40 in paper servers and LuckPerms-Bungee-5.4.104 for Waterfall Proxy Server BungeeCord

### Logs and Configs

[latest (2).log](https://github.com/LuckPerms/LuckPerms/files/12856332/latest.2.log)
OR
https://pastebin.com/XHBe3xSS

### Extra Details

CREDENTIALS ARE ALREADY MATCHING AND CORRECT.

**Comment by smashyalts** [comment]
Caused by: java.net.SocketTimeoutException: connect timed out

firewall or your using the wrong IP in config

**Comment by FurryBush** [comment]
nope already done that not working

**Comment by smashyalts** [comment]
you've done it wrong then, because it has nothing to do with luckperms, its a database connection issue

**Comment by LeotomasMC** [comment]
as you have been told now both on discord several times and here on github now too, the issue is with your setup, not with luckperms.

**Comment by FurryBush** [comment]
It was hosting issue they said that it was bugged but finally they fixed it so it was ultimately their fault

**Comment by FurryBush** [comment]
Ok, thanks for the clarification.
