### ISSUE TITLE
LuckPerms already has data for player even when online mode

### ISSUE THREAD

**Issue by ThrowerWay** [LuckPerms/LuckPerms#3768]
### Description

When there is a minecraft account, with for example the name "test123", and they join my server, then they change their name and someone else claims the name "test123" and they also join my server, luckperms nags me about it:

```
LuckPerms already has data for player 'SpicyRamen' - but this data is stored under a different UUID.
'SpicyRamen' has previously used the unique ids [f5e5393e-4bfa-44e2-a767-c29c4597b232] but is now connecting with '7a7736a0-f76a-4004-9f3d-89a645f882eb'
The UUID the player is connecting with now is Mojang-assigned (type 4). This implies that one of the other servers in your network is not authenticating correctly.
If you're using BungeeCord/Velocity, please ensure that IP-Forwarding is setup correctly on all of your backend servers\!
See here for more info\: https\://luckperms.net/wiki/Network-Installation\#pre-setup
```

I know 100% I am fully on online mode, looking at namemc shows that those 2 uuids have indeed had that name:
https://namemc.com/search?q=spicyramen

### Reproduction Steps

When there is a minecraft account, with for example the name "test123", and they join my server, then they change their name and someone else claims the name "test123" and they also join my server, luckperms nags me about it

### Expected Behaviour

No warning

### Server Details

git-Paper-"4b0bc74" (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT

### LuckPerms Version

v5.4.40

### Extra Details

Why not just test for offline mode uuid?
it is generated like this:

` profile = new GameProfile(UUID.nameUUIDFromBytes(("OfflinePlayer:" + name).getBytes(Charsets.UTF_8)), name);`

**Comment by LeotomasMC** [comment]
unless this is actually preventing it from loading data, you can just ignore the warning

**Comment by lucko** [comment]
I thought this edge case was so unlikely that I didn't even consider it :P

You can safely ignore the warning :)
