### ISSUE TITLE
Allow players to be added

### ISSUE THREAD

**Issue by fengguowudi** [LuckPerms/LuckPerms#3769]
### Description

Luckperms is a plug-in added after we have been playing for a while. After startup, it is found that players who enter the server before adding the plug-in will not be recorded as user by luckperms, which makes their permissions beyond my control.I hope there can be an instruction to manually add users to the user table.

### Proposed Behaviour

None...

**Comment by lucko** [comment]
You can give them permissions using their unique id (UUID) with all LuckPerms commands.
