### ISSUE TITLE
Error when start server

### ISSUE THREAD

**Issue by rodopoulos1** [LuckPerms/LuckPerms#3772]
### Description

There is i think its a bug but i dont know

[00:41:50 ERROR]: Error occurred while enabling LuckPerms v5.4.106 (Is it up to date?)

### Reproduction Steps

Put the luckperms on folder
start server

### Expected Behaviour

to work

### Server Details

spigot 1.8.8

### LuckPerms Version

5.4.106

### Logs and Configs

https://gist.github.com/rodopoulos1/54809fada49601c240114a434f74045c

**Comment by underscore11code** [comment]
Please don't comment unrelated things on someone else's issue.

**Comment by Deadcode-rgb** [comment]
is fucking issue fix that plz

**Comment by Deadcode-rgb** [comment]
you fucking issue

**Comment by Turbotailz** [comment]
Make sense please

**Comment by Deadcode-rgb** [comment]
idk how :(

**Comment by ImDarkLaw** [comment]
> idk how :(

The best place to receive quick support for LuckPerms is the official Discord server linked [here](https://discord.gg/LuckPerms). Feel free to ask on one of the support channels on there instead of commenting on another person's bug report.

**Comment by Deadcode-rgb** [comment]
i did

**Comment by smashyalts** [comment]
a good start would be to... not use bukkit

**Comment by smashyalts** [comment]
use paper 1.8.8
