### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by PingvinchikPororo8814** [LuckPerms/LuckPerms#3779]
### Description

We have a problem with the database. Error with saving user. Here's the error: https://paste.anfanik.me/fureyirobo.sql

### Reproduction Steps

I don't know how the problem occurred

### Expected Behaviour

Changes in the database are not saved

### Server Details

git-Mohist-320 (MC 1.12.2)

### LuckPerms Version

v5.4.9

### Logs and Configs

https://luckperms.net/download

**Comment by ImDarkLaw** [comment]
While [LuckPerms](https://luckperms.net/) **doesn't officially support hybrid software**, such as Mohist, you may want to:

- Ensure that the user connecting to the H2 database has the necessary permissions to perform database operations. 
- Confirm that the file system permissions on the directory containing the H2 database files allow write access. If the server process doesn't have the necessary file system permissions, it won't be able to write to the database files and save any users. 

Additionally, you're few versions behind and would suggest you update to the latest LuckPerms version which you can download from the [official downloads page](https://luckperms.net/download).
