### ISSUE TITLE
LuckPerms Bungeeperms Migration Script Plugin.yml

### ISSUE THREAD

**Issue by austinpilz** [LuckPerms/LuckPerms#3783]
### Description

When downloading the _latest_ LuckPerms migration script for bungeeperms [here](https://ci.lucko.me/job/luckperms-migration/lastSuccessfulBuild/artifact/bungeeperms/build/libs/luckperms-migration-bungeeperms.jar), the plugin cannot be started by Velocity, Paper, nor Spigot.

```Caused by: java.lang.IllegalArgumentException: Directory 'plugins\luckperms-migration-bungeeperms.jar' does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!```

### Reproduction Steps

1. Follow migration advice [here](https://luckperms.net/wiki/Migration)
2. Place bungeeperms migration script in plugins folder
3. Start server
4. Receive error

### Expected Behaviour

1. Follow migration advice [here](https://luckperms.net/wiki/Migration)
2. Place bungeeperms migration script in plugins folder
3. Start server
4. Plugin loaded successfully

### Server Details

paper-1.20.2

### LuckPerms Version

v5.4.108

### Logs and Configs

https://gist.github.com/austinpilz/e7fe761145d3d1628ab2aa1042d1dd0e

**Comment by austinpilz** [comment]
Looking at the resources in the bungeeperms folder [here](https://github.com/LuckPerms/migration/blob/master/bungeeperms/src/main/resources/bungee.yml), it looks like it names itself bungee.yml

BungeePerms _also_ runs natively on Velocity, so I think we also need a velocity yaml in there

**Comment by austinpilz** [comment]
As a solution for anyone else in this situation: I spun up a local Bungeecord instance just to run the BungeePerms, LuckPerms, and LuckPerms Migration plugins. Allowed me to migrate the BungeePerms -> LuckPerms, and retire using BungeePerms all together.

**Comment by emilyy-dev** [comment]
For closure: the BungeePerms migration plugin can only run on BungeeCord, where both LP and BP need to run too.
