### ISSUE TITLE
Mixin apply for mod luckperms failed on 1.20.2

### ISSUE THREAD

**Issue by Coosanta17** [LuckPerms/LuckPerms#3789]
### Description

I updated server and now it crashes on startup with this error message

### Reproduction Steps

1. Update server from 1.20.1 to 1.20.2
2. Crash, you have to kill the server to use it again.

### Expected Behaviour

It functions properly on new version

### Server Details

Fabric 1.20.2 loader version 0.15.1

### LuckPerms Version

5.4.111

### Logs and Configs

[Full server log](https://gist.github.com/Coosanta17/847a7d189dba9e474d614212f119c0dd)

### Extra Details

I deleted every luckperms related file but no work.

**Comment by BNTFryingPan** [comment]
5.4.111 is for fabric 1.20.3, not 1.20.2. downgrade to 5.4.110

**Comment by Coosanta17** [comment]
Thanks it now works.
The [downloads page](https://luckperms.net/download) on luckperms.net says fabric 1.20.2 but it's actually 1.20.3
![image](https://github.com/LuckPerms/LuckPerms/assets/85379921/d6e0d901-975c-4f64-bf3c-6ea583fa5a0d)
