### ISSUE TITLE
Fabric 1.20.4 - Mixin Injection Exception

### ISSUE THREAD

**Issue by SirReal314** [LuckPerms/LuckPerms#3791]
### Description

Fabric LP `5.4.112` (and `v5.4.111`) fail to start server using Fabric requirements from `build.gradle`. This is due to `CommandManagerMixin` injection exception (see log below).

### Reproduction Steps

- Create Fabric server with loader `v0.15.1`, api `v0.91.2`, and LP `v5.4.112` (and nothing else).
- Start server.

### Expected Behaviour

Server launches properly.

### Server Details

Fabric 1.20.4, loader v0.15.1

### LuckPerms Version

v5.4.112

### Logs and Configs

[https://pastebin.com/nxHr8yeW](https://pastebin.com/nxHr8yeW)

**Comment by wh0oo** [comment]
That commit fixed it.
