### ISSUE TITLE
[Fabric 1.20.1 server fails to load with LuckPerms installed] [main/ERROR]: Mixin apply for mod luckperms failed luckperms.mixins.json:ServerLoginNetworkHandlerAccessor from mod luckperms

### ISSUE THREAD

**Issue by kaolincash** [LuckPerms/LuckPerms#3792]
### Description

Server loads normally with any of the other installed mods, but breaks when LuckPerms is installed.

### Reproduction Steps

Install mods listed with LuckPerms for 1.20.1

### Expected Behaviour

Server to boot normally

### Server Details

Fabric_Latest_1.20.1 (via Shockbyte)

### LuckPerms Version

LuckPerms-Fabric-5.4.109

### Logs and Configs

https://gist.github.com/kaolincash/7ff7ca2fa751c8b5b09e2d7f1043603b

### Extra Details

I also hit the same issue with LuckPerms-Fabric-5.4.113

**Comment by BNTFryingPan** [comment]
LuckPerms Fabric 5.4.109 is for 1.20.2, not 1.20.1. The highest version that supports 1.20.1 is 5.4.102

**Comment by kaolincash** [comment]
Oh, huh. I installed it via the curseforge loader, so it's odd that the loader claims it's compatible with this fabric version.
It works with 5.4.102 though so you can consider this resolved.

**Comment by FoxMcloud5655** [comment]
CurseForge also installs 5.4.109 for the Forge version as well on Minecraft 1.20.1.  This needs to be labeled differently on Curseforge so users don't install the incorrect version automatically by default.
