### ISSUE TITLE
CUSTOM.json

### ISSUE THREAD

**Issue by SlimeDog** [LuckPerms/LuckPerms#3798]
### Description

`plugins/Plan/AnalysisResults/locale/CUSTOM.json` seems to have incorrect content on my server -- the wrong web server URL. Where/how is the file content generated?

### Reproduction Steps

- Stop server
- Edit plugins/Plan/AnalysisResults/locale/CUSTOM.json to provide correct URL
- Start server
- Observe that file content has changed

### Expected Behaviour

Understand where/how the file content is generated, so I can correct it

### Server Details

git-Paper-339 (MC: 1.20.4)

### LuckPerms Version

5.4.113

**Comment by lucko** [comment]
This has nothing to do with LuckPerms - I'm not sure what made you think it did? (genuine question - am I missing something?)

If I had to guess it's this??  https://www.spigotmc.org/resources/plan-player-analytics.32536/

**Comment by SlimeDog** [comment]
Of course not. Brain freeze. Apologies.
