### ISSUE TITLE
[LuckPerms] Failed to init storage implementation

### ISSUE THREAD

**Issue by GamingWithJohn12** [LuckPerms/LuckPerms#3803]
### Description

im trying to connect my servers with bungeecord and then have a mysql database to connect luckperms and luck perms is giving me this error [LuckPerms] Failed to init storage implementation

when i try to join my server it gives this
Kicked whilst connecting to lobby: [LP] A database error occurred whilst loading permissions data. Please try again later. If you are a server admin, please check the console for any errors.

### Reproduction Steps

1. download luckperms bungee
2. download luckperms hub
3. connect them with mysql databse
4. error

### Expected Behaviour

when i try to join it gives me this error "Kicked whilst connecting to lobby: [LP] A database error occurred whilst loading permissions data. Please try again later. If you are a server admin, please check the console for any errors."

console says this error
[LuckPerms] Failed to init storage implementation

### Server Details

1.20.4 paper

### LuckPerms Version

v5.3.70 (newest)

### Logs and Configs

https://gist.github.com/GamingWithJohn12/3b50f4506b8bd0833c20a4e83e064f60 bungee
https://gist.github.com/GamingWithJohn12/3bfdc8fe213f1aa9e512845579fbd047#file-hub-console hub

**Comment by BNTFryingPan** [comment]
5.3.70 is not the newest version. the latest (as of posting this) is 5.4.113

**Comment by GamingWithJohn12** [comment]
omg how did i mess that up

**Comment by GamingWithJohn12** [comment]
> 5.3.70 is not the newest version. the latest (as of posting this) is 5.4.113
> 
> edit: that version isnt even in either of your servers. the proxy is on .4.113 and the hub is on .4.108

should i update them?

**Comment by GamingWithJohn12** [comment]
what should i be doing

**Comment by emilyy-dev** [comment]
> Access denied for user 'u2_ZhdmUp7lrl'@'172.18.0.5' (using password: YES)

The only thing that can be said is that the credentials entered in the config file are incorrect, double check them with the correct info. Otherwise please reach out to our [discord server for support](https://discord.gg/luckperms)
Side note, LP on bungee seems to be using H2, not MySQL, but that's a separate problem easily solved.
