### ISSUE TITLE
bukkit.command.plugins [False] Doesn't work

### ISSUE THREAD

**Issue by welove69** [LuckPerms/LuckPerms#3809]
### Description

/lp group Default permission set bukkit.command.plugins false
/plugins can still be used

### Reproduction Steps

/lp group Default permission set bukkit.command.plugins false

### Expected Behaviour

/plugins can't be used

### Server Details

Paper 1.20.1

### LuckPerms Version

v5.4.113

### Logs and Configs

null

### Extra Details

null

**Comment by BNTFryingPan** [comment]
did you try with a lowercase "d" in `default`?

**Comment by welove69** [comment]
> did you try with a lowercase "d" in `default`?

Of course

**Comment by powercasgamer** [comment]
Cannot reproduce on Paper 1.20.4 build #\361  w/ luckperms 5.4.113. Can you try using [verbose](https://luckperms.net/wiki/Verbose) and sharing a list of your plugins and latest.log? Also please follow the issue template next time.
