### ISSUE TITLE
Failed to start server with new update (LuckPerms-Fabric-5.4.109)

### ISSUE THREAD

**Issue by gamerpotion** [LuckPerms/LuckPerms#3812]
### Description

Hi, im currently updating LuckPerms on DarkRPG and noticed when testing a server it fails to load after updating to the latest version.
5.4.102  seems to work fine
but after updating to 5.4.109 it doesnt load.  Here is the log - https://pastebin.com/bNgeTxDN
This is on Fabric 1.20.1 0.15.3

### Reproduction Steps

Update LuckPerms to 5.4.109 on DarkRPG Modpack and run a server with it

### Expected Behaviour

Does not load server

### Server Details

1.20.1

### LuckPerms Version

v5.4.109

### Logs and Configs

https://pastebin.com/bNgeTxDN

**Comment by ProfessorSherbert** [comment]
Yeah, I'm having a similar issue. (If not the same one) I haven't been able to get LuckPerms-Fabric-5.4.109 to load on my fabric 1.20.1 server either.

Is there a way to find an older version for 1.20.1 and use that? Or did you find a fix?

**Comment by gamerpotion** [comment]
> Yeah, I'm having a similar issue. (If not the same one) I haven't been able to get LuckPerms-Fabric-5.4.109 to load on my fabric 1.20.1 server either.
> 
> Is there a way to find an older version for 1.20.1 and use that? Or did you find a fix?

I am using this file and it works fine - https://www.curseforge.com/minecraft/mc-mods/luckperms/files/4738951
the update fails to start the server, hopefully can be looked into

**Comment by BNTFryingPan** [comment]
luckperms for forge and fabric can only easily support 1 version of minecraft at a time, that usually being the latest version. modrinth and curseforge are an easy place to find older versions of luckperms for older versions of minecraft for those platforms.

**Comment by emilyy-dev** [comment]
As listed on Modrinth, 5.4.109 is for 1.20.2, for 1.20.1 you need to use 5.4.102 which is listed there as the supported for that version.

**Comment by gamerpotion** [comment]
> As listed on Modrinth, 5.4.109 is for 1.20.2, for 1.20.1 you need to use 5.4.102 which is listed there as the supported for that version.

Hi thanks. On CurseForge client it was allowing 5.4.109 to be downloadable for 1.20.1. I think you had ticked the box for it in the file upload but seems to be resolved now.
