### ISSUE TITLE
editor can't use

### ISSUE THREAD

**Issue by Coquettishpig** [LuckPerms/LuckPerms#3813]
### Description

[16:51:45 WARN]: [LuckPerms] Command execution [editor] has not completed. Trace:
  java.base@17.0.3/sun.nio.ch.Net.poll(Native Method)
  java.base@17.0.3/sun.nio.ch.NioSocketImpl.park(NioSocketImpl.java:181)
  java.base@17.0.3/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:285)
  java.base@17.0.3/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309)
  java.base@17.0.3/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
  java.base@17.0.3/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
  java.base@17.0.3/java.net.Socket$SocketInputStream.read(Socket.java:966)
  java.base@17.0.3/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
  java.base@17.0.3/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
  java.base@17.0.3/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
  java.base@17.0.3/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
  java.base@17.0.3/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
  java.base@17.0.3/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
  java.base@17.0.3/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
  java.base@17.0.3/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
  me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:336)
  me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:300)
  me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:185)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
  me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
  me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:81)
  me.lucko.luckperms.common.http.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:47)
  me.lucko.luckperms.common.http.BytesocksClient.createSocket(BytesocksClient.java:67)
  me.lucko.luckperms.common.webeditor.socket.WebEditorSocket.initialize(WebEditorSocket.java:88)
  me.lucko.luckperms.common.webeditor.WebEditorSession.createSocket(WebEditorSession.java:94)
  me.lucko.luckperms.common.webeditor.WebEditorSession.open(WebEditorSession.java:86)
  me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:110)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:55)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:47)
  me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:279)
  me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:183)
  me.lucko.luckperms.common.command.CommandManager$$Lambda$10859/0x0000000802d6d1d0.run(Unknown Source)
  java.base@17.0.3/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
  java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  java.base@17.0.3/java.lang.Thread.run(Thread.java:833)

### Reproduction Steps

[16:52:05 INFO]: [LP] Running LuckPerms v5.4.116 by Luck.
[16:52:05 INFO]: [LP] -  Platform: Bukkit
[16:52:05 INFO]: [LP] -  Server Brand: Purpur
[16:52:05 INFO]: [LP] -  Server Version:
[16:52:05 INFO]: [LP]      git-Purpur-2095 (MC: 1.20.2) - 1.20.2-R0.1-SNAPSHOT
[16:52:05 INFO]: [LP] -  Storage:
[16:52:05 INFO]: [LP]      Type: H2
[16:52:05 INFO]: [LP]      File Size: 0.05MB
[16:52:05 INFO]: [LP] -  Extensions:
[16:52:05 INFO]: [LP]      None
[16:52:05 INFO]: [LP] -  Messaging: None
[16:52:05 INFO]: [LP] -  Instance:
[16:52:05 INFO]: [LP]      Static contexts: None
[16:52:05 INFO]: [LP]      Online Players: 0 (0 unique)
[16:52:05 INFO]: [LP]      Uptime: 55s
[16:52:05 INFO]: [LP]      Local Data: 0 users, 2 groups, 0 tracks

### Expected Behaviour

use

### Server Details

git-Purpur-2095

### LuckPerms Version

LuckPerms-Bukkit-5.4.116

**Comment by emilyy-dev** [comment]
This is a network issue outside of LP's reach, looks like it's taking a really long time to reach or connect to the editor servers (`usersockets.luckperms.net` unless changed in the settings). If that keeps happening you should contact your server host about it.
