### ISSUE TITLE
Folders In Luckperms

### ISSUE THREAD

**Issue by rbcoder117** [LuckPerms/LuckPerms#3817]
### Description

I personally think that luckperms can get a bit messy after a while. I think having folders to organize ranks would make the plug-in a lot cleaner!

### Proposed Behaviour

It should be in folders like

Default, 📂 (Rewards)
__________|
  Daily, weekly, etc.

But able to be called like Daily without calling the folder.

**Comment by BNTFryingPan** [comment]
duplicate of #3553
