### ISSUE TITLE
/lp editor not working

### ISSUE THREAD

**Issue by skcorylati** [LuckPerms/LuckPerms#3820]
### Description

When I try to execute the command /lp editor the command isn’t completing as expected. It has worked previously in the past and I have the most recent development build running on our server. 

### Expected Behaviour

The link to be displayed in chat. 

### Server Details

Paper 1.20.2

### LuckPerms Version

v5.4.116

### Logs and Configs

https://gist.github.com/skcorylati/5dbaca376e642baaadc9f3c236d5634c

**Comment by emilyy-dev** [comment]
Update EssentialsX, you're running a build over 3 years old, that should fix the problem.
