### ISSUE TITLE
LuckPerms doesn't recognize the game client language?

### ISSUE THREAD

**Issue by BangXi** [LuckPerms/LuckPerms#3826]
### Description

Now I need to re-set the language on the client side every time I enter the server so that LuckPerms can correctly recognize the corresponding language.
Otherwise, English is displayed by default.
My previous server version was 1.20.1 and the language recognition was working fine.
As soon as I entered the game, "luckperms" were able to recognize the language correctly.
The language of the game client is Chinese.

### Reproduction Steps

The game client sets Chinese, enters the server, and uses the luckperms command to view the language.

### Expected Behaviour

Once inside the server, luckperms should recognize the language correctly

### Server Details

paper1.20.4#496      purpur1.20.4 #2171        spigot 1.20.4

### LuckPerms Version

LuckPerms-Bukkit-5.4.128

### Logs and Configs

Brand new and default

### Extra Details

LuckPerms-Velocity-5.4.128 language recognition is normal

**Comment by BangXi** [comment]
It doesn't matter

**Comment by Lnpyz** [comment]
确实 这鸟bug挺烦 我的建议是直接用旧版本

**Comment by lucko** [comment]
Can you see if this is fixed by 9805f8b2c41c77afbda83bcd1f14cc1fdb7b6c67 (v5.4.131 or newer - https://luckperms.net/download)

**Comment by Lnpyz** [comment]
> Can you see if this is fixed by [9805f8b](https://github.com/LuckPerms/LuckPerms/commit/9805f8b2c41c77afbda83bcd1f14cc1fdb7b6c67) (v5.4.131 or newer - https://luckperms.net/download)
That's great! This problem has been solved!
