### ISSUE TITLE
LP Promote & parent settrack is adding additional group perms to users.

### ISSUE THREAD

**Issue by KoalaServers** [LuckPerms/LuckPerms#3841]
### Description

We use CMI to read players votes and execute lp user [playerName] parent settrack <TRACKNAME> <GROUP> once a certain vote count is hit. Now 8/10 luckperms promotes players correctly and removes the old group perfectly, but for those 2 the players will retain both groups, and then when they are ready to get promoted again, they can’t due to “user is in multiple groups so can’t promote them error”. We did previously use lp promote <PLAYER> <TRACK> with the same issue.

Example user: DesiOnRTX

[luckperms-command-executor/INFO]: [LP] desionrtx had their existing parent groups on track players cleared, and now only inherits wallaby in context global. But if you take a look at the attached image as you can see they are in two groups.
![Screenshot 2024-02-20 204659](https://github.com/LuckPerms/LuckPerms/assets/39786495/69abe7b6-e789-4fdb-8cbb-1acba78bff97)

### Reproduction Steps

Creating a track, promoting a player up and down the track until it catches them in two groups.

### Expected Behaviour

The user will retain two groups and won't be promoted along the track until one group is removed.

### Server Details

git-Paper-430 (MC 1.20.4)

### LuckPerms Version

v5.4.119

**Comment by Slimified** [comment]
Have you tried this on an isolated server in order to ensure this is not an external plugin interfering with Luckperms?

**Comment by KoalaServers** [comment]
![Screenshot 2024-02-25 160323](https://github.com/LuckPerms/LuckPerms/assets/39786495/d4af0c68-62e5-4b4e-a416-5c2bbd2e06ac)

Again

**Comment by KoalaServers** [comment]
![Screenshot 2024-02-25 200758](https://github.com/LuckPerms/LuckPerms/assets/39786495/ec2bc007-6076-4a1f-aa13-74757bfe9769)

8/10 times it does it fine.

**Comment by KoalaServers** [comment]
Just decided to give every user the default group now as well.

**Comment by KoalaServers** [comment]
![image](https://github.com/LuckPerms/LuckPerms/assets/39786495/eb4103ef-053f-42e2-9891-1eded66384ef)
![image](https://github.com/LuckPerms/LuckPerms/assets/39786495/a2b13a69-d56d-46c7-86ac-196592e957a7)

This is still happening with 2/10 rankups.

**Comment by KoalaServers** [comment]
**This appears to be fixed.** As we use groups/ranks with + within the name, replacing + with plus (so wallaby+ is no wallabyplus) on the backend solved this issue.

**Comment by KoalaServers** [comment]
This appears to be fixed. As we use groups/ranks with + within the name, replacing + with plus (so wallaby+ is no wallabyplus) on the backend solved this issue.
