### ISSUE TITLE
Luckperms Velocity - 5.4.120 - Windows 11 Security

### ISSUE THREAD

**Issue by Lorias-Jak** [LuckPerms/LuckPerms#3849]
### Description

I tryed to download Luckperms Velocity from Luckperms.net. After several failed attempts i foced windows to download it and check it via defender and my other security programms. Seems like it's detecting a Trojan. Used the newest Win 11 Version

![image](https://github.com/LuckPerms/LuckPerms/assets/62625225/756fdc2b-96ef-44c5-acac-dc23aae0f8a8)

### Reproduction Steps

Step 1: Try to download LuckPerms - Velocity from Luckperms.net
Step 2: If it doesnt fail - check via defender

### Expected Behaviour

Expected behaviour would be no issue from defender or other security programs

### Server Details

/

### LuckPerms Version

5.3.120

### Logs and Configs

/

### Extra Details

Several restart attemps, checked for newest windows updates, switched browsers to download luckperms. Every time the same result

**Comment by emilyy-dev** [comment]
Thanks for the report
https://www.virustotal.com/gui/file/90d0cfacd0ca1f9415d4526b6474c9f00e1061ba26af74dec735df4f0aebc95d
JAR files are generally a pain for antiviruses to accurately scan and it seems to not be a worthy investment in the industry given that false-positives are way too common. I recommend giving your setup a full scan if anything.
If this becomes a problem for more people as time goes on, we can reach out to whatever AVs are flagging it, but until then (and without something like virustotal flagging any threats in any of their AV tests) there isn't really anything we can do.
I will leave this issue opened however for some grace period just to be aware of this, if after some time no more reports arise it will be considered not an issue.
