### ISSUE TITLE
playsound command doesn't work

### ISSUE THREAD

**Issue by LPTEole** [LuckPerms/LuckPerms#3889]
### Description

I need to autorise playsound command in a server. I used the "minecraft.command.playsound" to ad the habilitation, but still not work.

I don't know if an other one exist and is required for the plugin.

To ad more informations, I'm in server with mods and plugins

### Reproduction Steps

impossible to use the command /playsound (except of admin)

### Expected Behaviour

command work...

### Server Details

Mohist 1.16.5

### LuckPerms Version

5.4.102 

### Logs and Configs

No more logs except "unknown command", reference command is "/playsound minecraft:block.iron_door.open voice @p" (work in my side as admin)

**Comment by BNTFryingPan** [comment]
"last one" is not a version, and forge-bukkit hacks are not exactly well supported. try reproducing on a supported server software like paper or an up-to-date version of forge

**Comment by LPTEole** [comment]
I gave you the fine version of luckperms

Mohist use spigot for plugins, I don't know if it makes a difference with paper...

**Comment by emilyy-dev** [comment]
Checking permissions for vanilla commands is up to the platform to do, or an external mod/plugin that does it if the platform doesn't provide it, real Paper provides such check, other platforms like Fabric require a mod to add them; Mohist nott checking permissions like Paper does is not something LuckPerms can fix, LP allows you to configure the permission access.
