### ISSUE TITLE
`Mohist Server` doesn't have data pre-loaded, they have never been processed during pre-login in this session. - denying login.

### ISSUE THREAD

**Issue by 8MiYile** [LuckPerms/LuckPerms#3891]
### Description

Velocity have plugin Ambassador
Mohist have mod proxy-compatible-forge-1.18.2-1.1.4.jar and plugin luckperms-bukkit

### Reproduction Steps

i'm try join mohist passthrough velocity server
i get this outout

### Expected Behaviour

can join Mohist server

### Server Details

Mohist version 1.18.2-170 (Implementing API version 1.18.2-R0.1-SNAPSHOT, Forge version 40.2.17)

### LuckPerms Version

v5.4.128

### Logs and Configs

https://gist.github.com/8MiYile/73316608c595ccb6ce9cb1a6cf3c1f31

### Extra Details

if you need config and another info
pls reply me

**Comment by thisfeeling** [comment]
what happend? you fixed it?

**Comment by 8MiYile** [comment]
@thisfeeling it's fixed from mohist's velocity support
and i'm using luckperms-bukkit

**Comment by VRHighLow** [comment]
what did you do to fix it?

**Comment by VRHighLow** [comment]
ah all good I made a fork of luckperms which should work on all mohist versions
