### ISSUE TITLE
Support specific schema for PostgresSQL

### ISSUE THREAD

**Issue by misterquestions** [LuckPerms/LuckPerms#3892]
### Description

When using PostgreSQL as data storage it would be really handy to have an option to use an specific schema, that way a single database could be used on multiple purposes divided by schemas, for example in a network having a shared schema with permissions only could be really great.

### Proposed Behaviour

Within configuration file being able to have some connection extra option for postgres like "schema" should be sufficient.

### Extra Details

None.

**Comment by lucko** [comment]
https://github.com/LuckPerms/LuckPerms/blob/c3802c2a5ad0b644b7eeb1d2b2a617d661413300/bukkit/src/main/resources/config.yml#L156-L160

**Comment by misterquestions** [comment]
The schema isn't the same as table prefix. In PostgreSQL schemas are like folders that contain other tables. By default its public, but what if I wanted to use something different but in the same database?

**Comment by Kinqdos** [comment]
1 up for this. Shouldn't be too hard to implement. Just add "schema." in front of the table name. Table prefix does not work, because luckperms escapes the table name in the queries
