### ISSUE TITLE
[me.lucko.luckperms.lib.hikari.pool.PoolBase] luckperms-hikari - Failed to validate connection me.lucko.luckperms.lib.mariadb.Connection@7e20ff86 ((conn=5955) Connection.setNetworkTimeout cannot be called on a closed connection). Possibly consider using a shorter maxLifetime value.

### ISSUE THREAD

**Issue by Playsus1234** [LuckPerms/LuckPerms#3893]
### Description

[me.lucko.luckperms.lib.hikari.pool.PoolBase] luckperms-hikari - Failed to validate connection me.lucko.luckperms.lib.mariadb.Connection@7e20ff86 ((conn=5955) Connection.setNetworkTimeout cannot be called on a closed connection). Possibly consider using a shorter maxLifetime value.

Mariadb config: https://pastebin.com/QwTZjwDP
Luckperms config: https://pastebin.com/02Tkf6YF

### Reproduction Steps

1

### Expected Behaviour

1

### Server Details

purpur 1.20.6-2211-3d25693 (MC: 1.20.6)*

### LuckPerms Version

v5.4.128

### Logs and Configs

1

**Comment by Playsus1234** [comment]
same with the velocity

**Comment by ichibanS** [comment]
I also have this issue I am using velocity 3.4.0
