### ISSUE TITLE
Can't disable "luckperms_action"

### ISSUE THREAD

**Issue by WarnDa** [LuckPerms/LuckPerms#3898]
### Description

Hello,
I am using MariaDB and I'm searching how to disable the table "luckperms_actions" as I'm using a single server. 

### Reproduction Steps

try `messaging-service: notsql` and `messaging-service: none` and check the table "luckperms_actions"

### Expected Behaviour

The table should stay empty, before it was working but now it's not

### Server Details

UniverseSpigot 1.20.4

### LuckPerms Version

5.4.126

### Logs and Configs

![image](https://github.com/LuckPerms/LuckPerms/assets/31826333/1372ff04-2b72-42d9-ad62-29fbf6b43710)

config : https://paste.gg/p/anonymous/115df801ea3149608458d9964742d00b

**Comment by emilyy-dev** [comment]
That table is for saving action logs, it is not used for messaging and is available for all storage formats, local ones too. LuckPerms will save action logs when a change is made, e.g. when you run a command such as `/lp group default permission set essentials.fly` or make changes in the editor, LP will save a description of those changes in a readable log you can see with `/lp log`, see https://luckperms.net/wiki/Log-Commands
