### ISSUE TITLE
Its crash my server

### ISSUE THREAD

**Issue by justlead** [LuckPerms/LuckPerms#3908]
### Description

When some player join server is cant connect and server crashes

### Reproduction Steps

Randomly player joins the server

### Expected Behaviour

I want my server not crash

### Server Details

Paper 1.16.5

### LuckPerms Version

LuckPerms-Bukkit-5.4.131

### Logs and Configs

config - https://pastebin.com/WtsDxzhU

error - https://pastebin.com/T6h0xQp6

**Comment by underscore11code** [comment]
Your server failed to reach Mojang's authentication servers. This is a server-wide issue that is not related to/caused by LuckPerms.
