### ISSUE TITLE
Add silent(-s) argument in the permission settemp command.

### ISSUE THREAD

**Issue by Lia-LV** [LuckPerms/LuckPerms#3909]
### Description

I am providing permission to users with settemp, such as experience boost. but there is a problem that the op's chat is seriously obscured. 
Please add a silent(-s) argument to prevent LuckPerms LOG message from being output in settemp as well.

### Proposed Behaviour

`/lp user/group <user|group> permission settemp <node> <true|false> <duration> [temporary modifier] [context...]`
-> `/lp user/group <user|group> permission settemp <node> <true|false> <duration> [temporary modifier] [silent and else flags] [context...]`
if command executed with silent flag, LOG message isn't output in the chat of op.

**Comment by BNTFryingPan** [comment]
you can disable seeing log messages in-game with the `/lp log` command

**Comment by emilyy-dev** [comment]
You can use these settings to configure logging to online admins https://github.com/LuckPerms/LuckPerms/blob/9805f8b2c41c77afbda83bcd1f14cc1fdb7b6c67/bukkit/src/main/resources/config.yml#L340-L351
