### ISSUE TITLE
useSSL: true

### ISSUE THREAD

**Issue by Playsus1234** [LuckPerms/LuckPerms#3910]
### Description

useSSL: true

message is displayed -> https://pastebin.com/VLaXURex

### Reproduction Steps

https://pastebin.com/VLaXURex

### Expected Behaviour

https://pastebin.com/VLaXURex

### Server Details

Velocity 3.3.0-SNAPSHOT (git-07f1f9e7-b396)

### LuckPerms Version

v5.4.131

### Logs and Configs

https://pastebin.com/VLaXURex

### Extra Details

https://pastebin.com/VLaXURex

**Comment by BNTFryingPan** [comment]
please follow issue templates. you have ignored it in every issue you have created on this repository, and all the ones i see you have made on other projects. following such template makes it easier to solve the issues you report.

**Comment by emilyy-dev** [comment]
As mentioned, next time follow the issue template. The log says "Trying to connect with ssl, but ssl not enabled in the server", which means that ssl is not enabled on the MariaDB configuration, see https://mariadb.com/kb/en/using-tls-ssl-with-mariadb-java-connector/#ssl-not-enabled-on-server
