### ISSUE TITLE
plugin LuckPerms v5.4.131 - plugin is disabled - Error and Bug

### ISSUE THREAD

**Issue by PABLOSKI531** [LuckPerms/LuckPerms#3914]
### Description

**Description**

I have tried changing the version, removing all the plugins, and it still doesn't work, I have used all versions 2023 and 2024 and it still gives the plugin deactivated error

### Reproduction Steps

1. I start the server

2. I enter the server

3. I enter the command /lp edit or any other

4.does nothing

### Expected Behaviour

luckperms has always worked for me but not now

### Server Details

1.16.5 (384 - 36.2.42) ARCLIGHT 

### LuckPerms Version

5.4.131,5.4.102 etc

### Logs and Configs

<html>
<body>

[12Jun2024 13:03:16.240] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: PabloskiSSS50 issued server command: /lp edit
--
284 | [12Jun2024 13:03:16.241] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
285 | org.bukkit.command.CommandException: Cannot execute command 'lp' in plugin LuckPerms v5.4.131 - plugin is disabled.
286 | at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[arclight:arclight-1.16.5-1.0.26-SNAPSHOT-5c6b7953]
287 | at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[arclight:arclight-1.16.5-1.0.26-SNAPSHOT-5c6b7953]
288 | at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServerMixin.java:761) ~[arclight:arclight-1.16.5-1.0.26-SNAPSHOT-5c6b7953]
289 | at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandlerMixin.java:2547) ~[?:?]
290 | at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandlerMixin.java:2397) ~[?:?]
291 | at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacketMixin.java:36) ~[?:?]
292 | at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacketMixin.java:9) ~[?:?]
293 | at net.minecraft.network.PacketThreadUtil.md4740e6$lambda$checkThreadAndEnqueue$0$0(PacketThreadUtilMixin.java:536) ~[?:?]
294 | at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
295 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
296 | at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
297 | at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:734) ~[?:?]
298 | at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:159) ~[?:?]
299 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
300 | at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServerMixin.java:717) ~[?:?]
301 | at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServerMixin.java:711) ~[?:?]
302 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
303 | at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServerMixin.java:697) ~[?:?]
304 | at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1921) ~[?:?]
305 | at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?]
306 | at java.lang.Thread.run(Thread.java:750) [?:1.8.0_412]

</body>
</html>

### Extra Details

I use Aternos Server and Arclight 1.16.5 (384 - 36.2.42) <html>
<body>

Version arclight-1.16.5-1.0.26-SNAPSHOT-5c6b7953
--
11 | Build Date 2024-05-01 09:30:27

</body>
</html>

https://mclo.gs/kH66jBb ALL registre

**Comment by BNTFryingPan** [comment]
luckperms isnt loading for some reason, but hybrids are not supported (because they are known to cause issues like this), and offline mode

**Comment by emilyy-dev** [comment]
I don't see the server attempting to load LuckPerms altogether. As mentioned, hybrids are not a supported environment; if you can reproduce the issue on a supported server (Spigot/Paper, SpongeForge, Fabric, etc) you can open a new issue for that instead.

**Comment by PABLOSKI531** [comment]
In version 1.20.1 everything works, plugins and mods but in this version it also worked but now it no longer works
