### ISSUE TITLE
bug when shutting down the server

### ISSUE THREAD

**Issue by tecMT** [LuckPerms/LuckPerms#3916]
### Description

Every time I restart my server this error appears

### Reproduction Steps

Restart the server or turn it off:
https://pastes.dev/DtEYRumeYr

### Expected Behaviour

start without errors

### Server Details

git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)

### LuckPerms Version

v5.4.131

**Comment by emilyy-dev** [comment]
Several of your plugins failed to load due to "message from server: "Too many connections"", it isn't specific to LuckPerms but your database configuration, see https://dev.mysql.com/doc/refman/8.4/en/too-many-connections.html
