### ISSUE TITLE
Add minecraft.command.whitelist.add and minecraft.command.whitelist.remove as a permission

### ISSUE THREAD

**Issue by EnderMaster77** [LuckPerms/LuckPerms#3922]
### Description

Title. At the current state, you can only give players the permission to use the entire whitelist  command. This includes turning the whitelist off. The additions of the `minecraft.command.whitelist.add ` and `minecraft.command.whitelist.remove`  will allow for finer control over which players can add or remove others from the whitelist without giving them the power to turn the whitelist off.

### Proposed Behaviour

The permission `minecraft.command.whitelist.add` would allow player with the permission to  run `whitelist add <player>` and `minecraft.command.whitelist.remove` would allow for the players with the permission to run `whitelist remove <player>`.

### Extra Details

The main use case for this is allowing players to add others into the whitelist without giving them other subcommands like whitelist off. At the current state, this is impossible as you can only toggle `minecraft.command.whitelist`.

**Comment by underscore11code** [comment]
LP is not responsible for restricting anything, it only *manages* permissions. The permissions for the vanilla commands are handled by either the platform itself (i.e. Bukkit/Spigot/Paper, Sponge), or a third-party mod (i.e. when using fabric).
