### ISSUE TITLE
Testing mode for testing groups-permissions

### ISSUE THREAD

**Issue by burdoto** [LuckPerms/LuckPerms#3925]
### Description

It would be very helpful to have a command that would temporarily put you into some kind of permission test mode; where LP pretends like you're not OP or in a whole different group.

### Proposed Behaviour

For admins, its not always clear what permissions have which effect; so they always have to fire up a secondary instance with an alt account for testing.

A command such as for example `/lp simulate <group>` could work around this.
Verify for permissions is good, but it does not give much insight on the ACTUAL effect on command usage.

**Comment by burdoto** [comment]
The proposed solution is only a workaround, as I would still have to change my groups back and forth every time. This could be simplified with a command to toggle such test mode on or off

**Comment by burdoto** [comment]
What about a counter-suggestion about this, similar to `/lp group default permission check ...` that can be used to check LPs result for a command; such as running `/lp group default permission checkcmd gamemode creative` to see if group `default` can run the command `/gamemode creative`?

**Comment by BNTFryingPan** [comment]
the existing `/lp verbose command` command works since it actually runs the commands as a player with everything that entails. there is no way to run the command as a group. also the `permission check` command returns the result of a single permission, not of a command

**Comment by burdoto** [comment]
> the permission check command returns the result of a single permission, not of a command
yes thats why i was asking about this.

however, i did not know that the verbose command exists. thank you for pointing that out; that would obsolete this suggestion, at least from my side

**Comment by burdoto** [comment]
it seems to me this belongs into a different issue, not only because it seems to be encountering more in-depth problems, since after using `/lp verbose record`, the server started stalling unpredictably. i will investigate further and open a bug report when i get the chance
