### ISSUE TITLE
LuckPerm Plugin error with Custom Npcs 1.16.5

### ISSUE THREAD

**Issue by Dieguini227** [LuckPerms/LuckPerms#3926]
### Description

I open a server just with the Custom NPCs mod and the LuckPerms Plugin and it shows me this error when im trying to enter
![error](https://github.com/LuckPerms/LuckPerms/assets/173714500/1e1d4317-a80d-4cba-9dae-0d87a8c69c77)

### Reproduction Steps

1.Arclight Server 1.16.5
2.Put CustomNPCs in the mods folder and LuckPerms in the plugins folder
3.Open the server
4.Try to enter the server (error)

### Expected Behaviour

When you enter this shows up:
![image](https://github.com/LuckPerms/LuckPerms/assets/173714500/a021b605-fe7a-4641-8e3b-ce79bdaecef0)

### Server Details

arclight-forge-1.16.5-1.0.25.jar

### LuckPerms Version

LuckPerms.28140.jar

**Comment by underscore11code** [comment]
Hybrid servers such as Arclight are not supported. If you can reproduce on a supported platform like Paper or Spigot, please open a new issue.
