### ISSUE TITLE
Luckperm did not give me the editor link

### ISSUE THREAD

**Issue by YuiHotaru** [LuckPerms/LuckPerms#3933]
### Description

Few days ago, i was able to do /lp editor before and it gave me the link but now, it stuck on "preparing a new editor session, please wait..." It also do the same with other /lp command. I keep removing the plugin and put it back in, it did not fix it. Im not sure if there's an error or something that prevent it or the plugin is not stable

### Reproduction Steps

- Removing and re-adding the plugins
- Do the /lp editor
- The command works but does not give the link

### Expected Behaviour

Need something that actual help fixing the issue

### Server Details

Paper Lastest (Java 21 - current 1.21 #39)

### LuckPerms Version

v5.4.134

### Logs and Configs

Logs:
![image](https://github.com/LuckPerms/LuckPerms/assets/174318870/e4b554f3-c697-47d1-8bd9-ad3ebc5dc781)

**Comment by dedestem** [comment]
Would been nice to say a fix
