### ISSUE TITLE
Luckperms affecting respawn after death.

### ISSUE THREAD

**Issue by OGBubba22** [LuckPerms/LuckPerms#3934]
### Description

Running luckperms on my 1.20.1 forge cobblemon server. Everything works great till a player dies and respawns almost like the server can't find there data file. To fix it I have to delete that players data file. But if they die again, I need to delete it again. If I remove luckperms from the server everything is fine even after respawning. I have no idea what's going on with it. Here's a file of the exact moment of death and respawn from the console. 
[New_Text_Document.txt](https://github.com/user-attachments/files/16103252/New_Text_Document.txt)

### Reproduction Steps

Unknown, to create this I fear you might need a full server download. 

### Expected Behaviour

What should happen is a player should just die and respawn like normal. But instead after they reapawn it's almost like they don't exist on the server, they can't die again, no mobs spawn around then and they can't inoract with anything. 

### Server Details

Forge 1.20.1

### LuckPerms Version

5.4.102 and 5.4.88

**Comment by clemmun** [comment]
Hey did you find a fix for this issuse?

**Comment by Scizith** [comment]
I believe im having this issue too. couldnt figure out which mod it is but saw some reference to luckperms in the log similar to what OP posted.

**Comment by Scizith** [comment]
im using 5.4.108, also forge for 1.20.1

**Comment by The0neAshPash** [comment]
I was able to replicate the issue and isolate it to the following mod: 
<img width="874" alt="image" src="https://github.com/user-attachments/assets/3a2960ea-a5c0-4a54-a5e2-40addc8398c2" />


When looking at the logs, player data is modified in a way that causes something to break when combined with luckperms.

**Comment by underscore11code** [comment]
See comment in #4002, the capability missing error should be fixed by [`b18717e`](https://github.com/LuckPerms/LuckPerms/commit/b18717edefabae99a8aa75ee5f49cda2e2ee823c).
