### ISSUE TITLE
DB upgrade fails from MC 1.17.1 to 1.21 on Fabric

### ISSUE THREAD

**Issue by StayKwimp** [LuckPerms/LuckPerms#3951]
### Description

I tried to upgrade my server from 1.17.1 to 1.21, but the LP database continues to fail to upgrade, even when restarting the server and my PC. The 1.17.1 server also ran on Fabric (the specific version is fabric-server-mc.1.17.1-loader.0.15.11-launcher.1.0.1), as does my 1.21 server.

### Reproduction Steps

Create a DB on Fabric 1.17.1
Create some permission group and assign players to them
Upgrade the DB by running the server on Fabric 1.21 with a new mod version

### Expected Behaviour

The database should've upgraded to a later version.

### Server Details

fabric-server-mc.1.21-loader.0.15.11-launcher.1.0.1 (MC 1.21)

### LuckPerms Version

v5.4.133

### Logs and Configs

Server log with error and stacaktrace: https://gist.github.com/StayKwimp/9f09238e8726e7590612eb47a4705923

### Extra Details

The LP version used to create the DB on 1.17.1 was v5.3.84.  I also checked to see if the error persisted when i only had the luckperms and fabric api mods in the mods folder of the server, and the error still occurred.

**Comment by BNTFryingPan** [comment]
load your data with the old version of LP, and use `/lp export`. move the h2 file somewhere (and delete the h2 v2 file if the newer version of LP was able to create it). load the server with the latest LP version, and use `/lp import`

**Comment by StayKwimp** [comment]
> load your data with the old version of LP, and use `/lp export`. move the h2 file somewhere (and delete the h2 v2 file if the newer version of LP was able to create it). load the server with the latest LP version, and use `/lp import`

Worked, thanks!
