### ISSUE TITLE
Cant Use Command Selector

### ISSUE THREAD

**Issue by KKW557** [LuckPerms/LuckPerms#3956]
### Description

`minecraft.command.selector` is `true`, but player cant use selector in command.

vanilla op system disabled

1.21 is working but 1.21.1 is broken

### Reproduction Steps

`/minecraft:kill @e`

then
```
Selector not allowed
...raft:kill @e<--[HERE]
```

### Server Details

Paper version 1.21.1-15-master@11b4ac7

### LuckPerms Version

v5.4.139

**Comment by DasBabyPixel** [comment]
This happens since the first 1.21.1 paper build

**Comment by DasBabyPixel** [comment]
This was just fixed in https://github.com/PaperMC/Paper/pull/11286
