### ISSUE TITLE
Client hangs when joining a NeoForge server with just LuckPerms installed

### ISSUE THREAD

**Issue by 3TUSK** [LuckPerms/LuckPerms#3960]
### Description

Client will stuck at "Joining World...." when joining a Minecraft 1.21.1 server with just NeoForge and LuckPerms installed.

### Reproduction Steps

1. Setup a Minecraft 1.21.1 server
2. Install NeoForge 21.1.8
3. Get & install `LuckPerms-NeoForge-5.4.139.jar`
4. Start the server 
5. Get a Minecraft 1.21.1 client. It can be either vanilla or w/ NeoForge.
6. Join the server in step 4

### Expected Behaviour

You join in the game.

### Server Details

Minecraft 1.21.1 w/ NeoForge 21.1.8

### LuckPerms Version

5.4.139

### Logs and Configs

There is no error in either server or client log.

Nevertheless, this is the `debug.log` from server, with logging level manually set to `TRACE`.

https://gist.github.com/3TUSK/d3f414d34abbe193c20cc20f2f8a9dc7

### Extra Details

It was only mentioned here https://github.com/LuckPerms/LuckPerms/issues/3936#issuecomment-2287836735, and I managed to let it slip away in my first few rounds of search. 

Considering the nature of this issue, I think it is worth having a new ticket.

**Comment by 3TUSK** [comment]
Update:

Swapping the environment to:

- Fabric Loader 0.16.2
- fabric-api 0.102.1+1.21.1
- LuckPerms-Fabric-5.4.139.jar

will let vanilla client to join. 

Note that LuckPerms version does not change. Only changed from NeoForge version to the Fabric one.

**Comment by lucko** [comment]
Thanks for the issue report and the fix!
