### ISSUE TITLE
Invalid Data error

### ISSUE THREAD

**Issue by Santu014** [LuckPerms/LuckPerms#3964]
### Description

My server was working normally until I installed luckperms, now all players who want to join are kicked with a message saying "Invalid player data".

### Reproduction Steps

1. Join the server (java/bedrock)
2. Get kicked with that message

### Expected Behaviour

Players joining the server normally

### Server Details

Neoforge Server 1.21.1

### LuckPerms Version

5.4.141

### Logs and Configs

https://gist.github.com/Santu014/b1e65e5a0e15269742e487802e6ca473
https://gist.github.com/Santu014/4eac942cf9817d06062b886e59fd43fb

### Extra Details

Using geyser

**Comment by Belu97** [comment]
https://github.com/LuckPerms/LuckPerms/issues/3963 have the same problem

**Comment by sanomi78** [comment]
Adding me to the list.

On Direwolf20 S14 1.3.0 (1.21) which is Neoforge and using LuckPerms-Neoforge-5.4.141.

Evert player gets "invalid player data" in the console and a java error on join.

Removing the mod fixes the problem.

**Comment by kaidenart** [comment]
I second this on neoforge

**Comment by underscore11code** [comment]
See comment in #4002, should be fixed by [`b18717e`](https://github.com/LuckPerms/LuckPerms/commit/b18717edefabae99a8aa75ee5f49cda2e2ee823c).
