### ISSUE TITLE
MySQL Database error

### ISSUE THREAD

**Issue by minecraftprogrammer23** [LuckPerms/LuckPerms#3966]
### Description

So I made a website in PHP, and if i click on the button that says "rank" for example, then in luckperms_players sets the primary_group column to something for a player getting by their name. It sets to the rank that IS AVALIABLE, made, set up, added permissions to it, etc. But however when I join the server, I still have the latest primary group, but the database says otherwise, but when i use lp user [name] parent set [rank] to the rank, then i have that primary group. Tried with different accounts, capital letter names, etc stame issue. Also if i have for example "vip" primary group in server and in database, and i change it in game to something else, then it changes in database also.

### Reproduction Steps

Already said it.

### Expected Behaviour

It should change the rank if I change it in SQL, not just typing a game command.

### Server Details

Spigot 1.8.8 but not version problem.

### LuckPerms Version

9.1.2

**Comment by underscore11code** [comment]
Group membership is determined by the presence of an inheritance node `group.<group name>` on the user. 

Primary group is a separate thing - many other plugins use the concept of a "primary group", which by default LP will calculate as the user's highest weighted group. The primary group column on the users table is *only* used if you explicitly change the primary group calculation method to manual (which we generally discourage) - and even then, setting a player's primary group will not make them inherit permissions from it unless they also have the inheritance node.
