### ISSUE TITLE
Internal Exception: java.net.SocketException: Connection reset,

### ISSUE THREAD

**Issue by kuretoshi** [LuckPerms/LuckPerms#3975]
### Description

I tried installing LuckPerms on a NeoForge 1.21.1-21.1.54 server, but when I tried to log in, I got the message "Internal Exception: java.net.SocketException: Connection reset," and I couldn't log in.
Do you know what might be causing this issue?
By the way, I was able to log in when LuckPerms was removed.

### Reproduction Steps

・NeoForge 1.21.1-21.1.54
・LuckPerms-NeoForge-5.4.141

### Expected Behaviour

Being able to log in successfully.

### Server Details

NeoForge 1.21.1-21.1.54

### LuckPerms Version

v5.4.141

### Logs and Configs

https://pastes.dev/TR51w4JwYb
https://pastes.dev/QVM9eDhmnX

**Comment by YangYuS8** [comment]
Your issue is similar to this one: #3963 , maybe wait for this one to be fixed: #3965

**Comment by lucko** [comment]
See comment in #4002, should be fixed by b18717edefabae99a8aa75ee5f49cda2e2ee823c
