### ISSUE TITLE
Random full corruption of H2 database

### ISSUE THREAD

**Issue by Paradis4432** [LuckPerms/LuckPerms#3977]
### Description

we have a set of servers, all use the same config and setup.
from time to time one of them will random corrupt the local H2 database
all servers restart every 24Hs.
the issue occurs on startup (we think it might have something to do with saving and or loading as it doesnt happen during the uptime of the servers, only startup)
we also tried to update to latest version but had issues making it work. if the solution is that then i can review it again.

### Reproduction Steps

we have not a clue, atm the only thing we can do is use an automatic backup to restore to the point before the restart

### Expected Behaviour

load h2 database 

### Server Details

Arclight 1.16.5

### LuckPerms Version

LuckPerms-Bukkit-5.4.30 on all servers

### Logs and Configs

message seen on start: https://paste.md-5.net/awigesejab.css
more complete message: https://paste.md-5.net/vijonefido.md
message for players trying to login: ![image](https://github.com/user-attachments/assets/7937fa01-87c0-4961-980e-fd45328ede90)
spamming the log: https://paste.md-5.net/ovirocuzap.sql
full log: [log.txt](https://github.com/user-attachments/files/17185244/log.txt)

i can provide the corrupted h2.mv.db and h2.trace.db files via DM in discord as its not allowed in git issues.

### Extra Details

feel free to contact me: .paradis

**Comment by underscore11code** [comment]
The version you are running is outdated and has an older version of the H2 database driver that is far more prone to corruption. [Updating](https://luckperms.net/download) should resolve this.

If you encounter any further problems, please reproduce on supported platform (i.e paper) as hybrid server softwares such as Arclight are unsupported.
