### ISSUE TITLE
Entering a command in-game will show "An unexpected error occurred while executing the command"

### ISSUE THREAD

**Issue by MechRW** [LuckPerms/LuckPerms#3998]
### Description

Entering a command in-game will show "An unexpected error occurred while executing the command"
However, it is no problem to type commands in the console, but there is no completion and the instructions cannot be directly pasted into the console, which will cause very trouble.
Maybe the problem is caused by arclight, I don't know why. At the same time, the import and export can only import and export the entire GZ file, which <file>will cause an error to be reported. In addition, my playername has uppercase letters, but when I got permission, I noticed that my playername became lowercase, but the permission should be normal, for example, my game mode will not change randomly when using multi-world.
![QQ20241112-234934](https://github.com/user-attachments/assets/1da0c465-6ccd-46a6-8539-5136f5c53dc5)

### Reproduction Steps

just Entering a command in-game will show "An unexpected error occurred while executing the command"

### Expected Behaviour

I'd like commands to work directly in the in-game chat, rather than having to type them through the console

### Server Details

arclight-forge-1.20.1-1.0.5-SNAPSHOT 

### LuckPerms Version

LuckPerms-Bukkit-5.4.30

**Comment by underscore11code** [comment]
Hybrid server softwares, such as Arclight, are unsupported by LuckPerms.

>At the same time, the import and export can only import and export the entire GZ file, which will cause an error to be reported.

Yes, this is intended behavior - the import command will import a `.json.gz` file outputted by the export command.
