### ISSUE TITLE
Wont let me log in ( Velocity Server )

### ISSUE THREAD

**Issue by SkeloD** [LuckPerms/LuckPerms#4008]
### Description

Whenever i try to log on it would not let me join, i contacted paper they said that it was a plugin issue. After some test i found out which plugin was producing the issue it was Luckperms, the luckperm is on my velocity server and is connected on a sql remote database, the only solution to fix this is to have the default config but with my config it just wont let me join and only me cause for other they can join but me even tho i switch to bedrock phones,computer,country,wifi but nothing works i feel like is a curse.

On the client side it just said Timed out but on the server side it says that i connected but its not letting me connect to lobby normally its suppose to be like this

[connected player] SkeloD (/############) has connected
[server connection] SkeloD -> lobby has connected

But on the console it just says

[connected player] SkeloD (/##########) has connected

### Reproduction Steps

I don't have a list that would reproduce the issue but i can give you the config and you can take a look at it

### Expected Behaviour

This problem will be fix in the next update?
Sorry i don't understand this question

### Server Details

1.21.4 ( Running on Velocity 3.4.0-SNAPSHOT  build number #455)

### LuckPerms Version

v5.4.150

### Logs and Configs

Console Log: https://gist.github.com/SkeloD/fb66793e727baa55a45f1b2388e0dfb2

Config: https://gist.github.com/SkeloD/26ea36cf3d09bb2201f86ceb26e71b72 ( tell me if i put sensitive info in here cause i removed the password for the database )

### Extra Details

I checked the config with the wiki and everything seems to be good and when i was modifying a rank it sent out a message to other server and its working well

**Comment by underscore11code** [comment]
Can you please share the disconnect message you're getting on the client when the issue occurs?

As there's zero errors in console on the proxy, my suspicion is this is actually an issue with the backend server you're connecting to. Can you also check the logs of that backend server for any errors from LP?

**Comment by SkeloD** [comment]
The disconnect message i already said in the report but ok i will send a screenshot
![image](https://github.com/user-attachments/assets/0af366c9-89bb-44c4-b641-e40253c9f501)

I use ATlauncher they have a console on the client but idk if its gonna help or not
Client Console ( https://gist.github.com/SkeloD/6f93d6a7bda5928b07be55a376b8018a )

I checked the backend server and there is nothing wrong with it or no errors at all
Console logs ( https://mcpaste.io/ced5c66deb5ae531 )
Config ( https://gist.github.com/SkeloD/64aced1efa486a1d832b699bd750cdd8 )
When trying to connect to the velocity server it did not send me to the lobby and when i check the console of the backend server it did not said anything about me joining

**Comment by SkeloD** [comment]
Umm hello?

**Comment by Runkang10** [comment]
Isn't because your backend is not configured properly to let Velocity to send you?

**Comment by Runkang10** [comment]
Because Timed out usually refer that Velocity or your backend has connection issues.

**Comment by Runkang10** [comment]
Make sure that Firewall allows Velocity or Backend server to access the internet.

**Comment by SkeloD** [comment]
I have properly set it up, there is no firewall that is blocking it

**Comment by SkeloD** [comment]
but it got fixed on a new velocity update but then i got another problem which is not related to this anymore so i think my issue is finished
