### ISSUE TITLE
Error Closing Server

### ISSUE THREAD

**Issue by xXTallBoyXx** [LuckPerms/LuckPerms#4010]
### Description

It shows me this error when stopping my server
![Captura de pantalla (365)](https://github.com/user-attachments/assets/67fd7022-733c-42d1-8c23-40c3a7e75c9d)

### Reproduction Steps

I just updated the jar folder and when stopping the server I got this error when starting it and during no.

### Expected Behaviour

Don't let that mistake come out

### Server Details

paper 1.20.4

### LuckPerms Version

v5.4.151

**Comment by underscore11code** [comment]
Don't replace the plugin jar while the server is running, Java can't handle that nicely. This applies to any plugin, not just LP. When updating any plugin, stop the server, replace the jar, *then* start the server back up.
