### ISSUE TITLE
warp command not working for non-op players

### ISSUE THREAD

**Issue by worthlessDARGON** [LuckPerms/LuckPerms#4013]
### Description

LuckPerms /warp command not working

### Reproduction Steps

please fix in the config files

### Expected Behaviour

warp cmd should be working

### Server Details

4344-Spigot MC: 1.21.1

### LuckPerms Version

v5.4.102

**Comment by ImDarkLaw** [comment]
LuckPerms doesn't have a `/warp` command and your issue lacks any detail to clarify how it's related to LuckPerms. As such, I'll have to close this issue. 

Feel free to provide more context or join our [Discord](https://discord.gg/luckperms), shall you require help running the plugin.
